### ISSUE TITLE
No block reward at pool

### ISSUE THREAD

**Issue by ricardomarlus** [turtlecoin/turtlecoin#1]
Hi! 
I'm trying to setup a pool for this coin, for solo mining or maybe open to community, but I have some problem. I'm getting all rewards on my wallet perfectly, but the pool front-end show all blocks as orphaned and 0 block rewards. Can you help me?

And simplewallet stucks at "Starting wallet rpc server". I have the same problem with forknote wallet with other cryptonote coins. So, how the pool can make payments? 

Thanks!

**Comment by JamesKegel** [comment]
This issue has been fixed, it's a mismatched block header off by 1 - https://i.imgur.com/bC9E9jb.png -
 https://github.com/forknote/forknote-pool/issues/48

**Comment by JamesKegel** [comment]
The correct codebase can be found here: https://github.com/CaptainMeatloaf/Turtlepool-Configs

**Comment by JamesKegel** [comment]
Thanks for setting up a pool :)

**Comment by ricardomarlus** [comment]
Thank you! :)
