### ISSUE TITLE
Why doesn't my "TurtleCoind" command run in the background

### ISSUE THREAD

**Issue by tzdadada** [turtlecoin/turtlecoin#1000]
The "TurtleCoind" command was started, but it did not run in the background, and I did not see related parameters like "--daemon" when using "--help"

**Comment by 0des** [comment]
You can do this a few ways:

- One way would be to run a multiplexer that will allow you to disconnect, like TMUX or SCREEN
- Another way would be to use ssh nohup
- another way would be to launch the process in the background with an ampersand like this `./TurtleCoind&`

There are other ways as well, try these and let us know what works best for you.

**Comment by tzdadada** [comment]
Thanks, I solved my problem with "TMUX"
