### ISSUE TITLE
f_block_json

### ISSUE THREAD

**Issue by BOBOKaa** [turtlecoin/turtlecoin#1003]
{"jsonrpc":"2.0","method":"f_block_json","params":{"hash":"83425888510706342942fccb12bfed3656eaf7d9f37ec38dced92dd8e6db99e4"},"id":1}HTTP/1.1 500 Internal Server Error
Content-Length: 59
Content-Type: application/json

{"status":"Failed","error":"Internal server error: stoull"}

**Comment by brandonlehmann** [comment]
Additional information:

```
2020-Jan-13 07:58:46.931815 FATAL   Caught unexpected exception: stoull argument out of range while processing /json_rpc request for User-Agent: 
2020-Jan-13 07:58:46.941817 FATAL   Body: {"jsonrpc":"2.0","method":"f_block_json","params":{"hash":"83425888510706342942fccb12bfed3656eaf7d9f37ec38dced92dd8e6db99e4"},"id":1}
```

Does appear to be coming from: https://github.com/turtlecoin/turtlecoin/blob/b938e21e3948270b098b14b4c04801c37fdd92c3/src/rpc/RpcServer.cpp#L1716

**Comment by zpalmtree** [comment]
Ahh, I see what is going on - the hash just happens to have enough leading numbers that `stoull` thinks it is a number, but is too large to fit in a uint64_t - when in fact it is a hex string, not a number. Perhaps we should also determine between a hash and a height by checking the length of the string.

**Comment by ngeojiajun** [comment]
is it possible to reverse the checking cases? like treat it as hex first then retry it as height when it fails. Finally fail the request if both fails.

**Comment by zpalmtree** [comment]
> is it possible to reverse the checking cases? like treat it as hex first then retry it as height when it fails. Finally fail the request if both fails.
Could do yep, need to be careful with `podToHex` though, as I don't think it will throw if the hash is not 64 chars.
