### ISSUE TITLE
what's the definition of 'type' in transfers array

### ISSUE THREAD

**Issue by past2017** [turtlecoin/turtlecoin#1005]
**version:**  turtlecoin-v0.22.0 from release
**steps:**:
run gettransaction rpc according to 'https://docs.turtlecoin.lol/developer/api/legacy-wallet-rpc-
api#gettransaction'

**the result is:**

> "transfers":[
>         {"address":"TRTLxxxx...","amount":5000,"type":0},
>         {"address":"","amount":-10000,"type":0},
>         {"address":"","amount":4990,"type":0}
>       ],

**Question:**
what's the definition of transfers array , especially what is the definition of 'type'
and where can I find the comment about these items
thank you very much

**Comment by brandonlehmann** [comment]
See https://github.com/turtlecoin/turtlecoin/blob/1fd306bbaa116a0ca8abc7aa679d6551230cfcd3/include/WalletGreenTypes.h#L88

```c
    enum class WalletTransferType : uint8_t
    {
        USUAL = 0,
        DONATION =1,
        CHANGE = 2
    };
```
