### ISSUE TITLE
Difficulty is zero

### ISSUE THREAD

**Issue by felixlandicho** [turtlecoin/turtlecoin#1006]
Hi,

I tried forking here to create new coin. (actually i did)
But not that I set my seed nodes, I getting this errors.

```
Cannot create block template, difficulty is zero. Oh shit, you fucked up hard!
```

Can you please tell me how to resolve this?
Thanks

**Comment by brandonlehmann** [comment]
You can’t stop mining. Rewind and try again or relaunch the chain.
