### ISSUE TITLE
How should I use the "/ transactions / hash / {hash}" API?

### ISSUE THREAD

**Issue by tzdadada** [turtlecoin/turtlecoin#1009]
I use the `/ transactions / hash / {hash}` API interface according to the `https://turtlecoin.github.io/wallet-api-docs/` document. After Execute,

Generate cURL: `curl -X GET http://127.0.0.1:8070/transactions/hash/783ab259b4aa80aba2cb9cc9b1a7201143bbaccd56d146a446844e8b17d28e1b "-H" accept: application / json`

Then the node server cURL reports an error: `Incoming GET request: / transactions / hash / 783ab259b4aa80aba2cb9cc9b1a7201143bbaccd56d146a446844e8b17d28e1b`
`Caught JSON exception, likely missing required json parameter: [json.exception.out_of_range.403] key 'transaction.transfers' not found `

The transaction has more than 5000 confirmations, and the transaction hash: `783ab259b4aa80aba2cb9cc9b1a7201143bbaccd56d146a446844e8b17d28e1b`

Am I using the API method incorrectly?

**Comment by zpalmtree** [comment]
For some reason this line is throwing - https://github.com/turtlecoin/turtlecoin/blob/development/src/walletapi/ApiDispatcher.cpp#L1482

Not sure what could cause that though

**Comment by tzdadada** [comment]
ok~~~

**Comment by zpalmtree** [comment]
Ok, I can reproduce the bug, lets figure out a fix! Apologies for the delay.
