### ISSUE TITLE
turtle-service wrong version

### ISSUE THREAD

**Issue by felixlandicho** [turtlecoin/turtlecoin#1010]
Hi guys,

I got stuck on this.
On my pool server, i'm starting turtle-service but it keep saying that my wallet version is wrong.

It's a new build on a new server, how can that be?

```
2020-Jan-16 22:42:57.490193 ERROR   Unsupported wallet version: 73
2020-Jan-16 22:42:57.490520 ERROR   Failed to init walletService reason: Unsupported wallet version: Wrong version
```

I saw the docs [website](https://docs.turtlecoin.lol/developer/api/rpc-api-error-conditions#wrong_version-wrong-version) referring to this kind of error but nothing seems to work.

Thanks

**Comment by zpalmtree** [comment]
Probably because you created your wallet with zedwallet instead of with turtle-service. Zedwallet uses a different (newer) file format that is compatible with wallet-api, instead.

You can generate a wallet with turtle-service like so:
```
./turtle-service --generate-container --container-file mywallet.wallet --container-password mypassword
```

**Comment by felixlandicho** [comment]
Got it, that's why.

Thanks @zpalmtree
