### ISSUE TITLE
"turtlecoin-v0.22.0" version can't use "`turtle-service`" command?

### ISSUE THREAD

**Issue by tzdadada** [turtlecoin/turtlecoin#1011]
"turtlecoin-v0.22.0" version can't use "`turtle-service`" command?

I use the cURL command as follows:

`curl -X POST "http://127.0.0.1:8448/transactions/send/basic" -H "accept: application / json" -H "X-API-KEY: password" -H "Content-Type: application / json "-d" {\ "destination \": \ "TRTLuxtk6uaAa2u8nbqhPU9Q1AHxzZsTAHmHzHZQSHzq9Zrc8xjtyhB9jLYBKwJmHYHvjgq5ZTRHgAEd7DdZ8GeXHm6yyjeNVn9VATeCd4kP9D9HDRmkBBjxaBJTnmaDM1BEf3KisXMcDAu2MigMGBexM5ZSqcgrCqT59MraqJTH7msKcECxMQe5gac \", \ "amount \": 1234} "`

But I can't transfer normally using the recommended "`wallet-api`" command,

details as following:

`curl -X POST "http://127.0.0.1:8448/transactions/send/basic" -H "accept: application / json" -H "X-API-KEY: password" -H "Content-Type: application / json "-d" {\ "destination \": \ "TRTLuxtk6uaAa2u8nbqhPU9Q1AHxzZsTAHmHzHZQSHzq9Zrc8xjtyhB9jLYBKwJmHYHvjgq5ZTRHgAEd7DdZ8GeXHm6yyjeNVn9VATeCd4kP9D9HDRmkBBjxaBJTnmaDM1BEf3KisXMcDAu2MigMGBexM5ZSqcgrCqT59MraqJTH7msKcECxMQe5gac \", \ "amount \": 1234} "`

Return error code:

```
{
    "errorCode": 30,
    "errorMessage": "We were not able to submit our request to the daemon. Ensure it is online and not frozen."
}
```

But I have activated "`TurtleCoind`" and "`wallet-api`"

My wallet balance is:

```
Available balance: 236,751.00 TRTL
Locked (unconfirmed) balance: 0.00 TRTL
Total balance: 236,751.00 TRTL
```

Then I used the "`zedwallet`" command on the server terminal to transfer the money normally, as follows:

```
What address do you want to transfer to ?: TRTLuxtk6uaAa2u8nbqhPU9Q1AHxzZsTAHmHzHZQSHzq9Zrc8xjtyhB9jLYBKwJmHYHvjgq5ZTRHgAEd7DdZ8GeXHm6yyjeNVn9VATeCd4kP9D9HDRmkBBjxaBJTnmaDM1BEf3KisXMcDAu2MigMGBexM5ZSqcgrCqT59MraqJTH7msKcECxMQe5gac

How much TRTL do you want to send ?: 1234


Confirm Transaction?
You are sending 1,234.00 TRTL, with a network fee of 15.00 TRTL,
and a node fee of 0.00 TRTL, for a total of 1,249.00 TRTL.

FROM: trtl.wallet
TO: TRTLuxtk6uaAa2u8nbqhPU9Q1AHxzZsTAHmHzHZQSHzq9Zrc8xjtyhB9jLYBKwJmHYHvjgq5ZTRHgAEd7DdZ8GeXHm6yyjeNVn9VATeCd4kP9D9HDRmkBBjxaBJTnmaDM1BEf3KisXMcDAu2MigMGBexM5ZSqcgrCqT59MraqJTH7msKcECxMQe5gac

Is this correct? (Y / n): y

Confirm your password: ********
Transaction has been sent!
Hash: 668aff2989f91fc0d34c3f747698d8e195d0da82d4dc400be86cf8ba348abf58
```

Do I need to roll back the version to use the transfer function?

**Comment by brandonlehmann** [comment]
In the first part, it looks like you’re trying to use wallet-api calls with turtle-service which is incorrect and won’t work. 

In the second part, are you running both wallet-api v0.22.0 and TurtleCoind v0.22.0?

Do the daemon or wallet-api logs reveal any information regarding the failure?

**Comment by tzdadada** [comment]
@brandonlehmann 
In the first part, I did not start the "`turtle-service`" command at all, and the "`turtlecoin-v0.22.0`" version does not support the "`turtle-service`" command. When I tried to start, I reported the following error:

`"Failed to init walletService reason: Unsupported wallet version: Wrong version"`

Therefore, what I transfer to access is actually the "`wallet-api`" service.


In the second part, I am running "`TurtleCoind`" and "`wallet-api`" at the same time. Both versions are:

`"TurtleCoin v0.22.0.1299 ()"`

**Comment by tzdadada** [comment]
The daemon and wallet-api have no errors. I currently have the following interfaces that can be called normally:

wallet-api:
/ wallet / open
/ addresses
/ addresses / create
/ transactions / {startHeight} / {endHeight}
/ transactions


TurtleCoind:
getblockcount
gettransaction


Now "/ transactions / send / basic" of "wallet-api" cannot be called normally

**Comment by brandonlehmann** [comment]
First off, v0.22.0 most certainly has support for turtle-service; however, as indicated, turtle-service can not open wallets created by zedwallet and wallet-api as the wallet formats are significantly different. If you wish to use turtle-service, you must create, open, and use only turtle-service with those wallet files. 

Secondly, please bump your log levels up for all applications and provide logs of the failure for further troubleshooting. 


Tip: no need to tag me each time, I’m set up to watch the repo including replies. :)

**Comment by tzdadada** [comment]
okay, thank you
