### ISSUE TITLE
send transaction some times occur error `Transaction has input with invalid signature` after upgrade to 0.22.0

### ISSUE THREAD

**Issue by inkbx** [turtlecoin/turtlecoin#1013]
### System Information

**Operating System**: Ubuntu 18.04 LTS

### TurtleCoin Build Information

**Version:**  0.22.0
**Binary Source:**  0.22.0 tag 
### Issue Report

**Binary Reported:** 

#### Expected Behavior

send transaction successful 

#### Current Behavior

send failed. the error message is Transaction has input with invalid signature.

after upgrade to 0.22.0, some tx is ok and some tx is error.

**Comment by brandonlehmann** [comment]
Which wallet application? Are you using a remote or local node? Is you wallet fully synced? Is your node fully synced? Have you tried resyncing the wallet? Do you have logs?

**Comment by niulingyun** [comment]
same error,  useing `wallet-api` with local turtlecoind.

**Comment by brandonlehmann** [comment]
Thank you for failing to answer all my questions.

**Comment by niulingyun** [comment]
> Thank you for failing to answer all my questions.

full synced, no tried resyncing the wallet

**Comment by inkbx** [comment]
Which wallet application?  wallet-api
Are you using a remote or local node?  local node
Is your wallet fully synced? 
Is your node fully synced?  Yes, the height is latest.
Have you tried resyncing the wallet?  No. 
Do you have logs?  yes, the daemon record this log message. 
` Failed to add transaction 811731b03a28ace80e63f720fa7b3d7cc21ebd14a1070266230f07948b9b41bc from /sendrawtransaction to pool: Transaction has input with invalid signature`

and, after upgrade, the are some transaction send successful, the the errror occur.

**Comment by RocksteadyTC** [comment]
@inkbx Sorry to hear that you're having issues. The general assumption is that you're having a sync-related issue. Some possible causes are:  

- improperly synced wallet and/or node
- wrong private ephemeral
-  random outputs are incorrect (not properly synced); when the daemon looks them up, they return bad public key sets that were used in mixing

**Comment by niulingyun** [comment]
> @inkbx Sorry to hear that you're having issues. The general assumption is that you're having a sync-related issue. Some possible causes are:
> 
> * improperly synced wallet and/or node
> * wrong private ephemeral
> * random outputs are incorrect (not properly synced); when the daemon looks them up, they return bad public key sets that were used in mixing

how to fix this?

**Comment by inkbx** [comment]
> @inkbx Sorry to hear that you're having issues. The general assumption is that you're having a sync-related issue. Some possible causes are:
> 
> * improperly synced wallet and/or node
> * wrong private ephemeral
> * random outputs are incorrect (not properly synced); when the daemon looks them up, they return bad public key sets that were used in mixing

how to check the node is synced ?

**Comment by brandonlehmann** [comment]
If this is still an issue, please tap this issue otherwise this issue is being closed.
