### ISSUE TITLE
Wrong height on block hash

### ISSUE THREAD

**Issue by felixlandicho** [turtlecoin/turtlecoin#1014]
Hi guys, 

After I reset my chain i'm receiving some strange output on blocks, for instance:

> HEIGHT **15963** have the BLOCK HASH **63c016e2298fe463921f70e4033cd3b46e8e4840cc72bf8542536ebc65cd4262**

But when i interrogate the _f_block_json_
```json
{
  "jsonrpc": "2.0",
  "id": "test",
  "method": "f_block_json",
  "params": {
    "hash": "63c016e2298fe463921f70e4033cd3b46e8e4840cc72bf8542536ebc65cd4262"
  }
}
```

it give me the **HEIGHT: 62**

**Comment by brandonlehmann** [comment]
See #1003
