### ISSUE TITLE
A node is much higher on height

### ISSUE THREAD

**Issue by felixlandicho** [turtlecoin/turtlecoin#1020]
Hi guys,

I'm having an issue with this particular node which have much higher height than the actual seed nodes and any other nodes.

And sync is not working, it's been 7 days since notice it and until now the sync process still says "(7 days) behind the current peer you're connected to".

And by this, wallet are not working how it should be.

Is there something I can do to force the sync? 

Thanks

**Comment by zpalmtree** [comment]
Can you provide the output of the `status` command in TurtleCoind.

In addition, can you provide the output of running your daemon launched with `--log-level 5` or `set_log 5` with the daemon already launched?

You can use a site like pastebin.com to upload your results.

Thanks.

**Comment by felixlandicho** [comment]
It's a fork issue, would that be ok too?

**Comment by zpalmtree** [comment]
This issue tracker is for issues with the TurtleCoin software suite only, sorry. I would recommend you contact the developers of the fork software, I'm sure they will be able to help you out.

Thank you!
