### ISSUE TITLE
Update user exposed file path opening with error messages

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#1025]
Where we take a filepath from the user and then subsequently open it, we should try and update all these usages with error messages.

For example, here:

https://github.com/turtlecoin/turtlecoin/blob/b4950d9aab6e9f0f0829b931a4cb362ebedcaf15/src/walletbackend/WalletBackend.cpp#L451-L457

we could update the code to something like this:

```cpp
 std::ifstream file(filename, std::ios_base::binary); 
  
 /* Check we successfully opened the file */ 
 if (!file) 
 { 
     return {Error(FILENAME_NON_EXISTENT, "The filename you are attempting to open does not exist, or the wallet does not have permission to open it. Error: " + strerror(errno)), nullptr}; 
 } 
```

This `strerror(errno)` bit gets the platform specific error code and converts it to a string, so for example, it might be something like 'Permission denied'. We're using the Error constructor here which takes a custom error message, instead of using the default error message.

This change will help users know why their filepath is invalid instead of having to guess.

**Comment by brandonlehmann** [comment]
Resolved in #1087
