### ISSUE TITLE
mac mining link broken

### ISSUE THREAD

**Issue by csd113** [turtlecoin/turtlecoin#103]
the mac mining link in the faq is broken

**Comment by BebopTC** [comment]
Can you provide a reference to the document you're referring to and where the link is?

**Comment by csd113** [comment]
https://github.com/turtlecoin/turtlecoin/wiki/Frequently-Asked-Questions#general-mining-questions

second question down has an external link that leads to a 404

**Comment by BebopTC** [comment]
ty

**Comment by csd113** [comment]
np, oh and if you get the chance, tell rocksteady that csd113 is sorry for spamming in the rain channel.

thank you

**Comment by raid5** [comment]
The link is still broken. Why was this closed?

**Comment by yamiM0NSTER** [comment]
Ereptor went on closing spree of old issues.
