### ISSUE TITLE
Enhance configuration for transaction-validation-threads option

### ISSUE THREAD

**Issue by polar-it** [turtlecoin/turtlecoin#1036]
Dumping the default configuration using '--dump-config' , transaction-validation-threads are absent, by the way could be correct if there are not a current default min/max value.
But if is used the '--save-config' option to dump the current settings in an configuration file, the "transaction-validation-threads" are not saved.
Could be great to have this feature enabled.

**Comment by zpalmtree** [comment]
#1034 should fix this, i added this member to the config while adding a few new config params.

**Comment by brandonlehmann** [comment]
Issue resolved in #1034
