### ISSUE TITLE
Not receiving turtles from mining?

### ISSUE THREAD

**Issue by Toni19944** [turtlecoin/turtlecoin#1041]
so first of all, it looks like everything is running just fine, so for that reason I'm leaving system specs out since I don't beleive they can really further help me or you in this case.

To the point, I'm a noob miner so I might ask stupid questions, sorry about that.
Issue: I've been now mining for around 3-days with 3.5kh/s rate and according to whattomine I should be mining around 30turtles/hour(?). I would love to know how/when I get paid since my wallet is empty, also would like to know how do I even check my worker stats?

Sorry for noob questions. I've been looking everywhere to find solutions but can't seem to find any.

**Comment by zpalmtree** [comment]
Looks like you got some help via discord, but for any future readers, the included miner is a solo miner. You'll only get payouts when you mine a full block, which when using CPU only, will take quite a long time.

Check out the mining guide for info on how to use pool and GPU miners: https://docs.turtlecoin.lol/guides/mining/mining
