### ISSUE TITLE
Node API Rewrite

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#1055]
To make the node API easier to work with, consider the following proposal to change the node API endpoints as follows.

|Current Endpoint|Current Method|New Endpoint|New Method|
|---|---|---|---|
|/info|GET|/info|GET|
|/fee|GET|/fee|GET|
|/height|GET|/height|GET|
|/peers|GET|/peers|GET|
|/sendrawtransaction|POST|/transaction|POST|
|/getrandom_outs|POST|/indexes/random|POST|
|/getwalletsyncdata|POST|/sync|POST|
|/get_global_indexes_for_range|POST|/indexes/{start}/{end}|GET|
|/queryblockslite|POST|||
|/get_transactions_status|POST|/transaction/status|POST|
|/get_pool_changes_lite|POST|/transaction/pool/delta|POST|
|/queryblocksdetailed|POST|/sync/detail|POST|
|/get_o_indexes|POST|/transaction/{hash}/indexes|GET|
|/getrawblocks|POST|/sync/raw|POST|
|||/block/{height}|GET|
|||/block/{hash}/raw|GET|
|||/block/{height}/raw|GET|
|||/transaction/{hash}/raw|GET|
|/json_rpc|---|---|---|
|&nbsp;&nbsp;&nbsp;&nbsp;*getblocktemplate*|POST|/block/template|POST|
|&nbsp;&nbsp;&nbsp;&nbsp;*submitblock*|POST|/block|POST|
|&nbsp;&nbsp;&nbsp;&nbsp;*getblockcount*|POST|/block/count|GET|
|&nbsp;&nbsp;&nbsp;&nbsp;*getlastblockheader*|POST|/block/header/top|GET|
|&nbsp;&nbsp;&nbsp;&nbsp;*getblockheaderbyhash*|POST|/block/header/{hash}|GET|
|&nbsp;&nbsp;&nbsp;&nbsp;*getblockheaderbyheight*|POST|/block/header/{height}|GET|
|&nbsp;&nbsp;&nbsp;&nbsp;*f_blocks_list_json*|POST|/block/headers/{height}|GET|
|&nbsp;&nbsp;&nbsp;&nbsp;*f_block_json*|POST|/block/{hash}|GET|
|&nbsp;&nbsp;&nbsp;&nbsp;*f_transaction_json*|POST|/transaction/{hash}|GET|
|&nbsp;&nbsp;&nbsp;&nbsp;*f_on_transactions_pool_json*|POST|/transaction/pool|GET|

**Note**: Response and request structures may change and are subject to alteration.

Swagger doc of how it all works at https://meta.turtlecoin.dev/proposals/daemon-api/

Source: https://github.com/turtlecoin/meta/tree/master/docs/proposals/daemon-api

**Comment by RocksteadyTC** [comment]
I support this

**Comment by brandonlehmann** [comment]
Updated OP with proposed replacement endpoints. Will work up a swagger.

**Comment by brandonlehmann** [comment]
Posted sample swagger docs to make it easier to look at at https://meta.turtlecoin.dev/proposals/daemon-api/

**Comment by brandonlehmann** [comment]
Tagged item for **To Do** for v1.0.0

**Comment by brandonlehmann** [comment]
// TODO: Push the broom
// TODO: Sanity check the responses
// TODO: Test stuff
// TODO: Make sure miner & Nigel are updated for API changes (including verbs)
// TODO: Fix all "off-by-one" errors and remove them entirely

**Comment by brandonlehmann** [comment]
See #1075

**Comment by brandonlehmann** [comment]
Merged.
