### ISSUE TITLE
Raise a warning if the daemon can't parse a config file

### ISSUE THREAD

**Issue by professor-l** [turtlecoin/turtlecoin#1058]
I run my daemon with a config file to avoid a United Nations Headquarters situation (way too many flags), but in editing said file I made a typo that prevented it from being parsed.  As it stands, that process fails silently and the daemon launches with default settings.  I think a user should be notified if a config file can't be parsed (I only noticed because I customize the data directory, which is information printed on launch).  Something like this:
```
WARNING: There was a problem with the configuration file provided at '/path/to/config.json' - launching daemon with default settings.
```
Optionally, more detailed information could be given.  Different warnings for a nonexistent file or one that simply can't be parsed would be nice, and potentially, depending on difficulty of implementation, pointing to a specific line of the config that caused the parsing error.

**Comment by brandonlehmann** [comment]
Being worked with #714

**Comment by brandonlehmann** [comment]
Handled in #1076
