### ISSUE TITLE
Zedwallet Error while compiling

### ISSUE THREAD

**Issue by vizx-enterprises** [turtlecoin/turtlecoin#1063]
### System Information

**Operating System**: Ubuntu
**OS Version**: 18 lts
**CPU Make, Model, & Speed**: Intel(R) Xeon(R) CPU E5-2643 v2 @ 3.50GHz
**Amount of RAM**: 4gb
**Hard Drive Type**: ssd
**Hard Drive Size**: 60gb
**Volume Type**: ?

### TurtleCoin Build Information

**Version:** v0.24.0
**Binary Source:** https://github.com/vizx-enterprises/viztercoin
**If self compiled, please provide all the build commands you used**
```
Please insert your build commands here. Example:

mkdir build && cd build
cmake ..
make
```

**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:
```

```

### Issue Report

**Binary Reported:**  While Compiling zedwallet

#### Expected Behavior

 To get it compile succesfully

#### Current Behavior

 Error in Zedwallet at 92%

#### Steps to Reproduce

1.  git clone https://github.com/vizx-enterprises/viztercoin.git 
2.  cd viztercoin
3. mkdir build
4.  cd build
5. cmake .. 
6. make

**Comment by brandonlehmann** [comment]
Sorry, we cannot support forks.

**Comment by vizx-enterprises** [comment]
So what about giving you some coins

**Comment by brandonlehmann** [comment]
We do not support forks.
