### ISSUE TITLE
[question] how to exit  TurtleCoind with the "exit" command

### ISSUE THREAD

**Issue by past2017** [turtlecoin/turtlecoin#1065]
Please tell me how to exit  TurtleCoind with the "exit" command, where to find the "exit" command
===[ TurtleCoin Tip! ]=============================
  Always exit TurtleCoind and zedwallet with the "exit" command to preserve your chain and wallet data.

**Comment by mrrovot** [comment]
Type in `exit` and hit enter

**Comment by brandonlehmann** [comment]
Or type exit in the daemon. 

Type help for all commands.

**Comment by past2017** [comment]
can I use kill command? @brandonlehmann @mrrovot

**Comment by brandonlehmann** [comment]
Your mileage may vary. Stunts performed by a professional driver on a closed course. 

Works on my machine.
