### ISSUE TITLE
turtlecoin-v0.26.0 - zedwallet - libssl/libcrypto missing

### ISSUE THREAD

**Issue by BKdilse** [turtlecoin/turtlecoin#1066]
### System Information

**Operating System**: Windows 10 Enterprise 64-bit
**OS Version**: 1909.18363.836
**CPU Make, Model, & Speed**: Intel i7-4770S 3.1GHz
**Amount of RAM**: 16GB
**Hard Drive Type**: SSD
**Hard Drive Size**: 512GB
**Volume Type**: NTFS

### TurtleCoin Build Information

**Version:** 0.26.0.1301
**Binary Source:** pre-compiled binaries https://github.com/turtlecoin/turtlecoin/releases/download/v0.26.0/turtlecoin-windows-v0.26.0.zip

### Issue Report

**Binary Reported:** zedwallet

#### Expected Behavior

Opens up

#### Current Behavior

The code execution cannot proceed because libssl-1_1-x64__.dll was not found.
The code execution cannot proceed because libcrypto-1_1-x64__.dll was not found.

#### Steps to Reproduce

1. Double click on zedwallet.exe

#### Possible Solution

Incorrect step during compile?

**Comment by brandonlehmann** [comment]
Confirmed. The CI/CD instructions were updated and now they are linking against static binaries of OpenSSL in the format of *.a versus *.lib MSVC binaries. Will correct.

For now, please compile locally and work with your own built release.

**Comment by brandonlehmann** [comment]
I've replaced the release binary packages with those from the updated CI/CD build. Please try the latest build from there <https://github.com/turtlecoin/turtlecoin/releases/download/v0.26.0/turtlecoin-windows-v0.26.0.zip>

**Comment by brandonlehmann** [comment]
Resolved in #1067
