### ISSUE TITLE
First of all, I'm sorry. This may not be an issue. Maybe it's because I don't know well. Genesis-block-reward-address is not found in the latest turtlecoin.

### ISSUE THREAD

**Issue by KimSungUg** [turtlecoin/turtlecoin#1069]
Genesis-block-reward-address is not found in the latest turtlecoin.

After I fork out the coin I created,

How should I pay the initial compensation?

**Comment by brandonlehmann** [comment]
First off, we don’t support forked projects. 

Second, you’re asking about functionality that doesn’t exist in TurtleCoin because it has never been used. Such functionality was remove a long, long time ago. 

This is not something we can help with.
