### ISSUE TITLE
Change the header image of the README.md file

### ISSUE THREAD

**Issue by l33d4n** [turtlecoin/turtlecoin#1079]
Based on the brand guide guidelines: https://github.com/turtlecoin/brand/blob/master/TurtleCoin%20Brand%20Guide%202020-2021.pdf

![image](https://user-images.githubusercontent.com/8020386/87237647-7db6ef00-c42b-11ea-8231-bb0eeb609e44.png)

![image](https://user-images.githubusercontent.com/8020386/87237638-552ef500-c42b-11ea-90f5-b133b418e938.png)

**Comment by brandonlehmann** [comment]
Just going to mark this one as not really an issue but more of a if it really needed done it would have been done already ;)
