### ISSUE TITLE
New simplewallet crashing on Windows

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtlecoin#108]
Simplewallet crashes on windows after finishing scanning the blockchain with an assertion fail of `GetCurrentThreadID() == threadId`.

This is littered everywhere around the code in https://github.com/turtlecoin/turtlecoin/blob/master/src/Platform/Windows/System/Dispatcher.cpp#L93 which I believe is responsible for the issue.

The reason it occurs is because the transaction watcher is launched on a background thread after the blockchain initial scan has finished. It periodically calls `wallet.updateInternalCache()` which makes the dispatcher yield to allow the blockchain synchronizer to update the values we get when we call functions on the wallet.

Without updating the internal cache/yielding the dispatcher the wallet can't function.
I'm not sure how to fix this so the transaction watcher only runs on the main thread or some other workaround. My initial though was to just run it periodically in `inputLoop()`, but we need the wallet to update in the background when we call a function like `optimize_wallet`, which needs to wait for transactions to be confirmed.

I'm not sure if there's some way to run code on a separate thread on the main thread without having to set up a complex queuing system. I'm also not sure if we could possibly get the Dispatcher code to run on another thread, it seems like some pretty platform specific code which is always a bit scary to dig into. I suppose we could just try removing the asserts() but intuition suggests that even if that worked it probably wouldn't be working well.

I don't really know how to fix this so some help would be great.

Thanks to @SoreGums for discovering this major issue...

To clarify, this only effects windows, linux works perfectly. Unsure about Mac but I assume the platform dependent code would be semi similar to linux.

**Comment by ZedPea** [comment]
Fixed.

**Comment by SoreGums** [comment]
no more crashes - woohoo 🎉
