### ISSUE TITLE
Error in build from fork

### ISSUE THREAD

**Issue by dagwood-Fenichuck** [turtlecoin/turtlecoin#1095]
Sorry this is not a bug but cant see anywhere else to get an answer 

std::tuple<Error, Crypto::Hash, WalletTypes::PreparedTransactionInfo> SendTransaction::sendTransactionAdvanced(std::vector<std::pair<std::__cxx11::basic_string<char>, long unsigned int> >, uint64_t, WalletTypes::FeeType, std::__cxx11::string, std::vector<std::__cxx11::basic_string<char> >, std::__cxx11::string, std::shared_ptr<Nigel>, std::shared_ptr<SubWallets>, uint64_t, std::vector<unsigned char>, bool, bool)’:walletbackend/Transfer.cpp:542:33: warning: ‘changeRequired’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             storeSentTransaction(txHash, actualFee, paymentID, ourInputs, changeAddress, changeRequired, subWallets);

can anyone tell me what the problem may be and point me in the right direction please i think i have a function wrong but dont know where any help appreciated and great coding from all

**Comment by brandonlehmann** [comment]
Sorry, we don’t support forks here.
