### ISSUE TITLE
Segmentation fault (core dumped) when launching TurtleCoind

### ISSUE THREAD

**Issue by rhanus** [turtlecoin/turtlecoin#1099]
### System Information

**Operating System**:
**OS Version**:
$ uname -srvo
Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 GNU/Linux

**CPU Make, Model, & Speed**:
$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               58
Model name:          Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Stepping:            9
CPU MHz:             2311.883
CPU max MHz:         3400.0000
CPU min MHz:         1200.0000
BogoMIPS:            4789.21
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

**Amount of RAM**:
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7861        1715         920           1        5225        5848
Swap:          4095           0        4095

**Hard Drive Type**:
ssd

**Hard Drive Size**:
$ sudo fdisk -l | grep sda
Disk /dev/sda: 238.5 GiB, 256060514304 bytes, 500118192 sectors
/dev/sda1     2048   1050623   1048576  512M EFI System
/dev/sda2  1050624 500115455 499064832  238G Linux filesystem

**Volume Type**: 
ext4

### TurtleCoin Build Information

**Version:** 
0.28.3

**Binary Source:** 
https://github.com/turtlecoin/turtlecoin/releases/download/v0.28.3/turtlecoin-linux-v0.28.3.tar.gz

### Issue Report

**Binary Reported:** 
TurtleCoind

#### Expected Behavior

be able to start TurtleCoind 

#### Current Behavior

Segmentation fault (core dumped)

#### Steps to Reproduce

$ /home/turtle/turtlecoin/TurtleCoind -c /home/turtle/TurtleCoind-config.json
Segmentation fault (core dumped)

**Comment by rhanus** [comment]
turtle@master:~$ /home/turtle/turtlecoin/TurtleCoind -c /home/turtle/TurtleCoind-config.json
TurtleCoind: /home/turtle/github/turtlecoin/external/rapidjson/document.h:1767: const Ch* rapidjson::GenericValue<Encoding, Allocator>::GetString() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::Ch = char]: Assertion `IsString()' failed.
Aborted (core dumped)
turtle@master:~$ coredumpctl gdb
           PID: 26423 (TurtleCoind)
           UID: 1001 (turtle)
           GID: 1001 (turtle)
        Signal: 6 (ABRT)
     Timestamp: Sun 2020-08-23 16:50:54 UTC (2s ago)
  Command Line: /home/turtle/turtlecoin/TurtleCoind -c /home/turtle/TurtleCoind-config.json
    Executable: /home/turtle/github/turtlecoin/build/src/TurtleCoind
 Control Group: /user.slice/user-1001.slice/session-c14.scope
          Unit: session-c14.scope
         Slice: user-1001.slice
       Session: c14
     Owner UID: 1001 (turtle)
       Boot ID: 69bc795ec82e44a0b8cbc771fe58ab4a
    Machine ID: 4cf9ee60aa0b4bd1b5316de3e9daf350
      Hostname: master
       Storage: /var/lib/systemd/coredump/core.TurtleCoind.1001.69bc795ec82e44a0b8cbc771fe58ab4a.26423.1598201454000000.lz4
       Message: Process 26423 (TurtleCoind) of user 1001 dumped core.
                
                Stack trace of thread 26423:
                #0  0x00007fbfa6ed6f47 raise (libc.so.6)
                #1  0x00007fbfa6ed88b1 abort (libc.so.6)
                #2  0x00007fbfa6ec842a n/a (libc.so.6)
                #3  0x00007fbfa6ec84a2 __assert_fail (libc.so.6)
                #4  0x000055e5a840e578 n/a (/home/turtle/github/turtlecoin/build/src/TurtleCoind)
                #5  0x000055e5a841c6fb n/a (/home/turtle/github/turtlecoin/build/src/TurtleCoind)
                #6  0x000055e5a83d990e n/a (/home/turtle/github/turtlecoin/build/src/TurtleCoind)
                #7  0x00007fbfa6eb9b97 __libc_start_main (libc.so.6)
                #8  0x000055e5a83d85ea n/a (/home/turtle/github/turtlecoin/build/src/TurtleCoind)

**Comment by zpalmtree** [comment]
Oh, it looks like there might be an issue with your config file. If you run without the config file, does it still crash? If not, please upload the config file here.

**Comment by rhanus** [comment]
ok I might have checked it before filling that issue...

$ /home/turtle/turtlecoin/TurtleCoind --data-dir /home/turtle/.TurtleCoin --log-file /home/turtle/TurtleCoind.log
2020-Aug-23 17:33:13.970419 INFO    

                                                                            
████████╗██╗  ██╗██████╗ ████████╗██╗    ██████╗ █████╗ █████╗ ██╗███╗   ██╗
╚══██╔══╝██║  ██║██╔══██╗╚══██╔══╝██║    ██╔═══╝██╔═══╝██╔══██╗██║████╗  ██║
   ██║   ██║  ██║██████╔╝   ██║   ██║    ████╗  ██║    ██║  ██║██║██╔██╗ ██║
   ██║   ██║  ██║██╔══██╗   ██║   ██║    ██╔═╝  ██║    ██║  ██║██║██║╚██╗██║
   ██║   ╚█████╔╝██║  ██║   ██║   ██████╗██████╗╚█████╗╚█████╔╝██║██║ ╚████║
   ╚═╝    ╚════╝ ╚═╝  ╚═╝   ╚═╝   ╚═════╝╚═════╝ ╚════╝ ╚════╝ ╚═╝╚═╝  ╚═══╝

 TurtleCoin v0.28.3.1305 ()
 This software is distributed under the General Public License v3.0

 Copyright 2018-2020, The TurtleCoin Developers

 Additional Copyright(s) may apply, please see the included LICENSE file for more information.
 If you did not receive a copy of the LICENSE, please visit:
 https://github.com/turtlecoin/turtlecoin/blob/master/LICENSE


2020-Aug-23 17:33:13.971149 INFO    Program Working Directory: "/home/turtle"
2020-Aug-23 17:33:13.971675 INFO    Loading Checkpoints for faster initial sync...
2020-Aug-23 17:33:13.972884 INFO    Loaded 547 default checkpoints
2020-Aug-23 17:33:13.972975 INFO    Opening DB in /home/turtle/.TurtleCoin/DB
2020-Aug-23 17:33:14.060594 INFO    DB opened in /home/turtle/.TurtleCoin/DB
2020-Aug-23 17:33:14.067369 INFO    Initializing core...
2020-Aug-23 17:33:14.232728 INFO    Core initialized OK
2020-Aug-23 17:33:14.233095 INFO    Initializing p2p server...
2020-Aug-23 17:33:14.234568 INFO    Binding on 0.0.0.0:11897
2020-Aug-23 17:33:14.234679 INFO    Net service bound on 0.0.0.0:11897
2020-Aug-23 17:33:14.234782 INFO    Attempting to add IGD port mapping.
2020-Aug-23 17:33:18.239507 INFO    No IGD was found.
2020-Aug-23 17:33:18.239849 INFO    P2p server initialized OK
2020-Aug-23 17:33:18.240122 INFO    Starting core rpc server on address 127.0.0.1:11898
2020-Aug-23 17:33:18.240933 INFO    Starting p2p net loop...
2020-Aug-23 17:33:18.241231 INFO    Starting node_server
2020-Aug-23 17:33:29.525239 INFO    [123.185.140.160:11897 OUT] Your TurtleCoin node is syncing with the network (99.55% complete) You are 12636 blocks (4 days) behind the current peer you're connected to. Slow and steady wins the race! 
2020-Aug-23 17:33:29.525410 INFO    New Top Block Detected: 2828619

**Comment by rhanus** [comment]
so the last question is what' s wrong in this config, worked fine untill 0.24

$ cat TurtleCoind-config.json 
{
    "data-dir": "/home/turtle/.TurtleCoin",
    "load-checkpoints": "default",
    "log-file": "/home/turtle/TurtleCoind.log",
    "log-level": 2,
    "no-console": false,
    "db-enable-compression": true,
    "db-max-open-files": 125,
    "db-read-buffer-size": 128,
    "db-threads": 4,
    "db-write-buffer-size": 256,
    "allow-local-ip": false,
    "hide-my-port": false,
    "p2p-bind-ip": "192.168.1.113",
    "p2p-bind-port": 11897,
    "p2p-external-port": 0,
    "p2p-reset-peerstate": false,
    "rpc-bind-ip": "192.168.1.113",
    "rpc-bind-port": 11898,
    "add-exclusive-node": [],
    "add-peer": [],
    "add-priority-node": [],
    "seed-node": [],
    "enable-cors": [],
    "enable-blockexplorer": false,
    "enable-blockexplorer-detailed": false,
    "fee-address": "TRTLv2XXX",
    "fee-amount": 0
}

**Comment by zpalmtree** [comment]
probably ` "enable-cors": [],`. Try changing that to `"enable-cors": "",`

**Comment by rhanus** [comment]
that's it :+1: thanks guys !
Slow and steady wins the race!

**Comment by zpalmtree** [comment]
Great. I'll open up an issue to give a better error message when the config file is invalid.
