### ISSUE TITLE
Daemon configuration file with incorrect JSON type causes crash

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#1100]
Launching the daemon with a config file that is valid JSON, but has an incorrect type for an expected key, causes a crash.

See https://github.com/turtlecoin/turtlecoin/issues/1099

In this case the `enable-cors` value was an array in the JSON file, but the parsing code expected a string value, so the daemon crashed. We should catch this error and provide a helpful message to the user instead of crashing.

**Comment by brandonlehmann** [comment]
This was already handled in #1026 which is in the v1.0.0 branch. Closing duplicate issue.

**Comment by brandonlehmann** [comment]
Typo #1076
