### ISSUE TITLE
Crash of  zedwallet v0.28.3

### ISSUE THREAD

**Issue by netmebtc** [turtlecoin/turtlecoin#1101]
### System Information

**Operating System**: 
ubuntu16.04
**OS Version**: 
4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**CPU Make, Model, & Speed**: 
**Amount of RAM**: 
16G
**Hard Drive Type**: 
**Hard Drive Size**: 
420G
**Volume Type**: 

### TurtleCoin Build Information
**Version:** 
 TurtleCoin v0.28.3.1305 ()

**Binary Source:** 
compiled by my self

**If self compiled, please provide all the build commands you used**
git clone https://github.com/turtlecoin/turtlecoin.git
cd turtlecoin
mkdir build && cd build
cmake .. 
make -j4

**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:
```
Please insert your default verbosity CMake output here
```

### Issue Report

when zedwallet restore a wallet ,it crashed

following is the screen said :

Unlock height: 2675522
Unlocks at approximately: 2020-07-01 03:42

Saving progress...

*** Error in `./0.28.3/zedwallet': malloc(): memory corruption: 0x00007f6f2aff9ab0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f6f423447e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8213e)[0x7f6f4234f13e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f6f42351184]
./0.28.3/zedwallet[0x8b1cd8]
./0.28.3/zedwallet[0x4de286]
./0.28.3/zedwallet[0x4de341]
./0.28.3/zedwallet[0x4d6c36]
./0.28.3/zedwallet[0x4da674]
./0.28.3/zedwallet[0x8dcccf]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f6f429a76ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f6f423d441d]
======= Memory map: ========
00400000-00b44000 r-xp 00000000 08:02 3801292                            /root/trtl/0.28.3/zedwallet
00d44000-00d6e000 r--p 00744000 08:02 3801292                            /root/trtl/0.28.3/zedwallet
00d6e000-00d7f000 rw-p 0076e000 08:02 3801292                            /root/trtl/0.28.3/zedwallet
00d7f000-00e0f000 rw-p 00000000 00:00 0
0186e000-02f11000 rw-p 00000000 00:00 0                                  [heap]
7f6f00000000-7f6f01ac8000 rw-p 00000000 00:00 0
7f6f01ac8000-7f6f04000000 ---p 00000000 00:00 0
7f6f08000000-7f6f0bfff000 rw-p 00000000 00:00 0
7f6f0bfff000-7f6f0c000000 ---p 00000000 00:00 0
7f6f10000000-7f6f13ff9000 rw-p 00000000 00:00 0
7f6f13ff9000-7f6f14000000 ---p 00000000 00:00 0
7f6f163ff000-7f6f18000000 rw-p 00000000 00:00 0
7f6f18000000-7f6f18169000 rw-p 00000000 00:00 0
7f6f18169000-7f6f1c000000 ---p 00000000 00:00 0
7f6f1c000000-7f6f1c192000 rw-p 00000000 00:00 0
7f6f1c192000-7f6f20000000 ---p 00000000 00:00 0
7f6f20000000-7f6f2019b000 rw-p 00000000 00:00 0
7f6f2019b000-7f6f24000000 ---p 00000000 00:00 0
7f6f24000000-7f6f24142000 rw-p 00000000 00:00 0
7f6f24142000-7f6f28000000 ---p 00000000 00:00 0
7f6f28000000-7f6f2b17e000 rw-p 00000000 00:00 0
7f6f2b17e000-7f6f2c000000 ---p 00000000 00:00 0
7f6f2c000000-7f6f2c1de000 rw-p 00000000 00:00 0
7f6f2c1de000-7f6f30000000 ---p 00000000 00:00 0
7f6f30000000-7f6f3018c000 rw-p 00000000 00:00 0
7f6f3018c000-7f6f34000000 ---p 00000000 00:00 0
7f6f34000000-7f6f37fff000 rw-p 00000000 00:00 0
7f6f37fff000-7f6f38000000 ---p 00000000 00:00 0
7f6f38ffa000-7f6f38ffb000 ---p 00000000 00:00 0
7f6f38ffb000-7f6f397fb000 rw-p 00000000 00:00 0
7f6f397fb000-7f6f397fc000 ---p 00000000 00:00 0
7f6f397fc000-7f6f39ffc000 rw-p 00000000 00:00 0
7f6f39ffc000-7f6f39ffd000 ---p 00000000 00:00 0
7f6f39ffd000-7f6f3a7fd000 rw-p 00000000 00:00 0
7f6f3a7fd000-7f6f3a7fe000 ---p 00000000 00:00 0
7f6f3a7fe000-7f6f3affe000 rw-p 00000000 00:00 0
7f6f3affe000-7f6f3afff000 ---p 00000000 00:00 0
7f6f3afff000-7f6f3b7ff000 rw-p 00000000 00:00 0
7f6f3b7ff000-7f6f3b800000 ---p 00000000 00:00 0
7f6f3b800000-7f6f3c000000 rw-p 00000000 00:00 0
7f6f3c000000-7f6f3c021000 rw-p 00000000 00:00 0
7f6f3c021000-7f6f40000000 ---p 00000000 00:00 0
7f6f400b1000-7f6f400c8000 r-xp 00000000 08:02 20709392                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f6f400c8000-7f6f402c7000 ---p 00017000 08:02 20709392                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f6f402c7000-7f6f402c8000 r--p 00016000 08:02 20709392                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f6f402c8000-7f6f402c9000 rw-p 00017000 08:02 20709392                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f6f402c9000-7f6f402ca000 ---p 00000000 00:00 0
7f6f402ca000-7f6f40aca000 rw-p 00000000 00:00 0
7f6f40aca000-7f6f40acb000 ---p 00000000 00:00 0
7f6f40acb000-7f6f412cb000 rw-p 00000000 00:00 0
7f6f412cb000-7f6f412cc000 ---p 00000000 00:00 0
7f6f412cc000-7f6f41acc000 rw-p 00000000 00:00 0
7f6f41acc000-7f6f41acd000 ---p 00000000 00:00 0
7f6f41acd000-7f6f422cd000 rw-p 00000000 00:00 0
7f6f422cd000-7f6f4248d000 r-xp 00000000 08:02 20709569                   /lib/x86_64-linux-gnu/libc-2.23.so
7f6f4248d000-7f6f4268d000 ---p 001c0000 08:02 20709569                   /lib/x86_64-linux-gnu/libc-2.23.so
7f6f4268d000-7f6f42691000 r--p 001c0000 08:02 20709569                   /lib/x86_64-linux-gnu/libc-2.23.so
7f6f42691000-7f6f42693000 rw-p 001c4000 08:02 20709569                   /lib/x86_64-linux-gnu/libc-2.23.so
7f6f42693000-7f6f42697000 rw-p 00000000 00:00 0
7f6f42697000-7f6f4279f000 r-xp 00000000 08:02 20709573                   /lib/x86_64-linux-gnu/libm-2.23.so
7f6f4279f000-7f6f4299e000 ---p 00108000 08:02 20709573                   /lib/x86_64-linux-gnu/libm-2.23.so
7f6f4299e000-7f6f4299f000 r--p 00107000 08:02 20709573                   /lib/x86_64-linux-gnu/libm-2.23.so
7f6f4299f000-7f6f429a0000 rw-p 00108000 08:02 20709573                   /lib/x86_64-linux-gnu/libm-2.23.so
7f6f429a0000-7f6f429b8000 r-xp 00000000 08:02 20709552                   /lib/x86_64-linux-gnu/libpthread-2.23                                                                                                                               .so
7f6f429b8000-7f6f42bb7000 ---p 00018000 08:02 20709552                   /lib/x86_64-linux-gnu/libpthread-2.23                                                                                                                               .so
7f6f42bb7000-7f6f42bb8000 r--p 00017000 08:02 20709552                   /lib/x86_64-linux-gnu/libpthread-2.23                                                                                                                               .so
7f6f42bb8000-7f6f42bb9000 rw-p 00018000 08:02 20709552                   /lib/x86_64-linux-gnu/libpthread-2.23                                                                                                                               .so
7f6f42bb9000-7f6f42bbd000 rw-p 00000000 00:00 0
7f6f42bbd000-7f6f42bc0000 r-xp 00000000 08:02 20709550                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f6f42bc0000-7f6f42dbf000 ---p 00003000 08:02 20709550                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f6f42dbf000-7f6f42dc0000 r--p 00002000 08:02 20709550                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f6f42dc0000-7f6f42dc1000 rw-p 00003000 08:02 20709550                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f6f42dc1000-7f6f42de7000 r-xp 00000000 08:02 20709551                   /lib/x86_64-linux-gnu/ld-2.23.so
7f6f42fcc000-7f6f42fd8000 rw-p 00000000 00:00 0
7f6f42fe5000-7f6f42fe6000 rw-p 00000000 00:00 0
7f6f42fe6000-7f6f42fe7000 r--p 00025000 08:02 20709551                   /lib/x86_64-linux-gnu/ld-2.23.so
7f6f42fe7000-7f6f42fe8000 rw-p 00026000 08:02 20709551                   /lib/x86_64-linux-gnu/ld-2.23.so
7f6f42fe8000-7f6f42fe9000 rw-p 00000000 00:00 0
7ffd93c3f000-7ffd93c60000 rw-p 00000000 00:00 0                          [stack]
7ffd93db3000-7ffd93db6000 r--p 00000000 00:00 0                          [vvar]
7ffd93db6000-7ffd93db8000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted

**Binary Reported:** 

#### Steps to Reproduce

1.   ./zedwallet --scan-coinbase-transactions
2.   select restore from seed
3.   imput 25 seed and sync from  2625379 height
4.   when synced at  2675522 height, it crashed

**Comment by brandonlehmann** [comment]
Please indicate CPU make, model, and specifications.

**Comment by netmebtc** [comment]
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               2199.996
BogoMIPS:              4399.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-5

**Comment by brandonlehmann** [comment]
If this issue remains with v1.0.0, please check your memory utilization and/or memory itself as a failure to malloc due to corruption is a machine dependent issue.
