### ISSUE TITLE
Forked to a new coin -Selacoin

### ISSUE THREAD

**Issue by deltatoken** [turtlecoin/turtlecoin#1104]
Forked to a new coin -Selacoin
The new age of crypto currencies is abut to go live on https://github.com/deltatoken/SelaCoin

https://sela-coin.com

Build from: 

Binaries for Testing:
  - Windows: 
  - Linux: 
  - MacOS: 
  - AARCH64: 

### Project
- [ ] Currently Passing Travis & AppVeyor build tests
- [ ] `Version.h.in` updated to correct semver value
- [ ] Release Notes Prepared ()

### TurtleCoind Tests
- Daemon connects to local DB
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Local DB does not require resync
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Peer ID assigned
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Connections to multiple peers are made
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon able to sync with external checkpoints
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon able to sync without external checkpoints
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon able to sync from 0 with external checkpoints
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon able to sync from 0 without external checkpoints
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon stays synchronized for 24 hours
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
 
### ZedWallet Tests
- Connect to local daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Connect to a remote daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Send a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Receive a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Perform a fusion transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Export keys and seeds
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Import from keys and seeds correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Perform a full reset
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Integrated Addresses work
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Scan From Height Works Correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS

### Turtle-Service Tests
- Connect to local daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Connect to a remote daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Send a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Receive a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Perform a fusion transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Export keys and seeds
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Import from keys and seeds correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Perform a full reset
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Integrated Addresses work
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- All RPC endpoints and methods are operational
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Scan From Height Works Correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS

**Comment by brandonlehmann** [comment]
We don’t support forks here and you using this platform to try to promote your coin is not cool.
