### ISSUE TITLE
Default directory for blockchain in CLI

### ISSUE THREAD

**Issue by DazedConfused-crypt** [turtlecoin/turtlecoin#1109]
_(I am not sure if this is the right place to enter this question. I looked around and [this](https://github.com/turtlecoin/meta/issues/83) is the closest entry I was able to find on this topic. Please direct me to that information if this issue already been addressed.)_

I would like to be able run my own node on my computer. Unfortunately, the default directory the Turtlecoind data storage does not have enough capacity for me to execute it properly. I used to run my own node before the turtlecoin data became too large for my humble setup to handle. Therefore, I would like to try using an external harddisk to download the turtlecoin data.

Is there a way to change the default directory for the CLI wallet? 

I tried the solution offered in the discussion mentioned above with no luck. The data is still stored in my computer's harddrive not the external harddisk.

Or should I just give up now, wait for v2 release at the end of the year, and pray it will include an option/'way around' for choosing data storage location?

### System Information

**Operating System**: Ubuntu
**OS Version**: 20.04 (LTS)
**Storage**: 96GB
**External Storage**: 150GB

**Comment by brandonlehmann** [comment]
> _(I am not sure if this is the right place to enter this question. I looked around and [this](https://github.com/turtlecoin/meta/issues/83) is the closest entry I was able to find on this topic. Please direct me to that information if this issue already been addressed.)_
> 
> I would like to be able run my own node on my computer. Unfortunately, the default directory the Turtlecoind data storage does not have enough capacity for me to execute it properly. I used to run my own node before the turtlecoin data became too large for my humble setup to handle. Therefore, I would like to try using an external harddisk to download the turtlecoin data.
> 
> Is there a way to change the default directory for the CLI wallet?
> 
> I tried the solution offered in the discussion mentioned above with no luck. The data is still stored in my computer's harddrive not the external harddisk.
> 
> Or should I just give up now, wait for v2 release at the end of the year, and pray it will include an option/'way around' for choosing data storage location?
> 
> ### System Information
> **Operating System**: Ubuntu
> **OS Version**: 20.04 (LTS)
> **Storage**: 96GB
> **External Storage**: 150GB

—help on the CLI has tons of options. You want —data-dir
