### ISSUE TITLE
simplewallet not support  --wallet-file --password -rpc-bind-port ...?

### ISSUE THREAD

**Issue by zhiapp-com** [turtlecoin/turtlecoin#111]
Commands:
  -h, --help                   Display this help message and exit
  -v, --version                Display the version information and exit
      --remote-daemon <url>    Connect to the remote daemon at <url> instead of the default: 0.0.0.0:11898

not support  --wallet-file --password -rpc-bind-port ...?

**Comment by ereptor81** [comment]
Use the code from the tagged release (0.3.2) for now instead of master.

**Comment by bobbieltd** [comment]
According recent changes, simplewallet won’t have RPC API. You should move to use walletd. For pool codes, update the pending Pull Request for paymentProcessor.js and config.json (two files).

**Comment by zhiapp-com** [comment]
tks, tags 0.3.2
