### ISSUE TITLE
Can not build on CentOS8 - Error

### ISSUE THREAD

**Issue by xsistema** [turtlecoin/turtlecoin#1110]
On CentOS8 I'm getting this error - build stops:

```
[  7%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/blake2b_simd.cpp.o
~/turtlecoin/turtlecoin/external/cryptopp/blake2b_simd.cpp: In function ‘void CryptoPP::BLAKE2_Compress64_SSE4(const byte*, CryptoPP::BLAKE2b_State&)’:
~/turtlecoin/turtlecoin/external/cryptopp/blake2b_simd.cpp:364:5: error: ‘_mm_roti_epi64’ was not declared in this scope
     _mm_roti_epi64(r, c)
```

**Comment by zpalmtree** [comment]
Looks like this error: https://github.com/weidai11/cryptopp/issues/859

Which has been fixed in the linked issue, but we are using an older version of cryptopp which doesn't have those changes.

**Comment by xsistema** [comment]
Problem solved by changing code in several files to:

```
#if defined(__XOP__)
# include <ammintrin.h>
# if defined(__GNUC__)
#  include <x86intrin.h>
# endif
#endif
```

But now another error:

```
~/turtlecoin/turtlecoin/external/argon2/arch/x86_64/lib/argon2-template-128.h: In function ‘fill_block’:
~/turtlecoin/turtlecoin/external/argon2/arch/x86_64/lib/argon2-xop.c:25:12: error: incompatible types when assigning to type ‘__m128i’ {aka ‘__vector(2) long long int’} from type ‘int’
         D0 = ror64(D0, 32); \
            ^
```

**Comment by brandonlehmann** [comment]
What version and which compiler are you using?

**Comment by xsistema** [comment]
It's GNU Make 4.2.1

**Comment by brandonlehmann** [comment]
> It's GNU Make 4.2.1

Compiler. Is it gcc-6? gcc-7? clang-6? The issue template asks for these things so that we can better assist.

**Comment by xsistema** [comment]
> 
> 
> > It's GNU Make 4.2.1
> 
> Compiler. Is it gcc-6? gcc-7? clang-6? The issue template asks for these things so that we can better assist.

gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)

**Comment by brandonlehmann** [comment]
Are you on a 32-bit machine? 64-bit?

What CPU made, model, etc. are you running on?

**Comment by xsistema** [comment]
64-bit, AMD Opteron(TM) Processor 6220

**Comment by xsistema** [comment]
Added `#include <x86intrin.h>` to file argon2-template-128.h and problem disappeared..

**Comment by brandonlehmann** [comment]
> Added `#include <x86intrin.h>` to file argon2-template-128.h and problem disappeared.. Perhaps would be better to add:
> 
> ```
> 
> # if defined(__GNUC__)
> #  include <x86intrin.h>
> # endif
> ```
> 
> Edit:
> Looks like only `#include <x86intrin.h>` would be enough (instead of `#include <immintrin.h>`) to cover all CPUs: https://stackoverflow.com/a/31185861/2111085

If this resolved your issue, please feel free to submit a PR and reference this issue.

**Comment by jsegura17** [comment]
I had the same problem, I added the line that @xsistema mentioned ...
Thanks, the issue was fixed. 👍
