### ISSUE TITLE
Generating genesis block hex gives 345 characters

### ISSUE THREAD

**Issue by dagwood-Fenichuck** [turtlecoin/turtlecoin#1114]
hi setting up a node when I do   ./TurtleCoind --print-genesis-tx I  get  345 characters  and am unable to store the genesis block transaction could you help and tell me what I need to do to get this right, please

**Comment by crappyrules** [comment]
sirs, this is not fork support

**Comment by dagwood-Fenichuck** [comment]
Hi Crappy rules thank you for your reply could you please tell me where I could get support for the Turtlecoin fork you guys have been brilliant and I am supporting Turtlecoin and want to make a fork for learning and pointers for help would be appreciated dagwood

**Comment by brandonlehmann** [comment]
We don’t provide support for forks, there is no place to find this.
