### ISSUE TITLE
Cannot Transfer

### ISSUE THREAD

**Issue by alfredosalzillo** [turtlecoin/turtlecoin#1122]
**Describe the bug**
Trying to transfer I get this error 

```
StatusCodeError: 409 -error":code": 65, 'message":"Transaction contains an input which has already been spent'}
```

**Environment**
- App version  v1.1.2]
- Android version, if known Android 11
- Phone model, if known Pixel 4xl

**Comment by brandonlehmann** [comment]
Duplicate issue from another repo and the issue can be handled via that wallet’s repo.
