### ISSUE TITLE
RPC server Not Starting

### ISSUE THREAD

**Issue by Tulasinathreddy** [turtlecoin/turtlecoin#1125]
### System Information

**Operating System**: Linux
**OS Version**: Ubuntu 20
**CPU Make, Model, & Speed**: 4 cores , 8 GB ram , 100 GB Disk Space
**Amount of RAM**: 8 GB
**Hard Drive Type**: SSD
**Hard Drive Size**: 100 GB

### TurtleCoin Build Information

**Version:** v3.0
**Binary Source:** https://github.com/turtlecoin/turtlecoin/releases/download/v1.0.0/turtlecoin-linux-v1.0.0.tar.gz

### Issue Report

**Binary Reported:** TurtleCoind

#### Expected Behavior

Before starting the Node Sync it says local server listening at 127.0.0.1:11898

#### Current Behavior

but when i goto my_vps_ip:11898 i see nothing
i have a apache2 server currently running and there is also a active SSL encrypted domain on the same server with same ip 
https://mrbean.dev

##### Screen Shots

nothing to show !!

**Comment by zpalmtree** [comment]
You need to launch with `--rpc-bind-ip 0.0.0.0` if you want the API to be available outside your local network.
