### ISSUE TITLE
UPNP AddPortMapping Failed

### ISSUE THREAD

**Issue by blast1987** [turtlecoin/turtlecoin#115]
Hello,
just a question, i am starting the daemon (TurtleCoind) in linux Ubuntu via command line but i am getting the error:

2018-Mar-23 11:14:32.095074 INFO    Net service binded on 0.0.0.0:11897
2018-Mar-23 11:14:32.095495 INFO    Attempting to add IGD port mapping.
**2018-Mar-23 11:14:33.114442 ERROR   UPNP_AddPortMapping failed.**
2018-Mar-23 11:14:33.114700 INFO    P2p server initialized OK
2018-Mar-23 11:14:33.115020 INFO    Starting core rpc server on address 127.0.0.1:11898
2018-Mar-23 11:14:33.115385 INFO    Core rpc server started o

So i Assume it fails to open port 11897, but is it a TCP or UDP port?
I need to know this so i can open it by myself

Thanks in advance

**Comment by yamiM0NSTER** [comment]
Unless you are using modified source it is trying to open port using TCP.

**Comment by BigslimVdub** [comment]
![upnp port maping failed](https://user-images.githubusercontent.com/30030687/42836421-a0c18f66-89c0-11e8-9e65-c10ee41e9a59.png)

same issue on 6.3 windows running --rpc-bind-ip 0.0.0.0

I get 0 In connections. May be related to https://github.com/turtlecoin/turtlecoin/issues/339  @RocksteadyTC

**Comment by brandonlehmann** [comment]
I get this all the time on my machine; however, I do not have a router that supports IGD or UPNP so the error is expected on my end.

Your router has to have UPNP enabled for the port mapping to complete. No all do.

**Comment by brandonlehmann** [comment]
Interesting as we haven’t touched the upnp code practically ever...

**Comment by BigslimVdub** [comment]
huh odd. I went to my router and moved the ethernet cable one port over and then restarted daemon and got no error prompt:
![igd port mapping](https://user-images.githubusercontent.com/30030687/42839537-a304032c-89c9-11e8-8b01-8719a204e002.png)
But still I am getting no In connections and now its going back to the issue from issue 399 not updating the blockchain. So I exit TurtleD and wait a minute and reopen turtleD and now get the same error of UPnP mapping fail:
![failing again to map](https://user-images.githubusercontent.com/30030687/42839833-83f6ec82-89ca-11e8-8c1c-5252df7c4e4f.png)
