### ISSUE TITLE
NETWORK is failed everywhere

### ISSUE THREAD

**Issue by Rndexspb** [turtlecoin/turtlecoin#116]
what's going on @RocksteadyTC ?
block 288709 was last and before there was a decrasing diff to ~600k
now pool shows looking for a block 288710 with diff 498m, but blocks r not coming

**Comment by Rndexspb** [comment]
and what was this fail?? mine2gether get all easy blocks...

**Comment by bobbieltd** [comment]
It’s over now. Thanks God !

**Comment by RocksteadyTC** [comment]
It seems that a user timewarped us briefly.
