### ISSUE TITLE
is there a case to be made for wallet name being the name without .wallet being added?

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtlecoin#117]
maybe not an issue now, as @ZedPea has altered how simplewallet handles opening wallet by filename.

previous version (0.3.2) irked me in that I would specify the name of the wallet to be "trtl.main" and it would get written as "trtl.main.wallet" then when i opened the wallet i had to specify "trtl.main.wallet".

ultimately I don't want .wallet files on my computer, unless i name them .wallet.

thoughts?

**Comment by ZedPea** [comment]
I'm fairly sure with the old version it would write it as `trtl.main.wallet`, but you would still be able to open it with `trtl.main`. My simplewallet has the same behaviour, and does append a .wallet extension.

**Comment by SoreGums** [comment]
you know after I pressed submit, i was like "hmm, lets just check" and sure enough v0.3.2 opens with or without the extension.

SO let's ignore that part...
Should filenames be what is specified or .wallet?
I see that SimpleWallet will open what is requested and attempt to open a .wallet variant if what is requested is not found.

**Comment by ZedPea** [comment]
As a linux user I prefer it to write just the specified filename. However, as the majority of our userbase are probably windows users, I think it's a good idea to add an extension by default.
If you see a .wallet file you'll probably remember what it is, but if not you might be wondering what the randomly named file with no extension is, and when you can't open it you might end up deleting it.

**Comment by SoreGums** [comment]
that makes sense, with regards to windows users.
probably will stay that way then :)
