### ISSUE TITLE
BUG daemon - colour not reset after INFO message

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtlecoin#123]
TurtleCoind-master
If you type directly after the INFO message about Successfully Sync'd, text is green still :)

![image](https://user-images.githubusercontent.com/317/38007035-b92a9ea4-3271-11e8-94b9-24c37c18702d.png)

```
2018-Mar-28 10:18:24.378870 INFO    [159.203.36.230:43683 INC] Successfully synchronized with the TurtleCoin Network.
set_log 3 << green
```

**Comment by SoreGums** [comment]
looks fixed to me.
![image](https://user-images.githubusercontent.com/317/38469781-5cb53fd2-3b84-11e8-9147-f5538a1ea4fe.png)

**Comment by yamiM0NSTER** [comment]
It is multithreading issue lol.
