### ISSUE TITLE
LWMA difficulty algorithm

### ISSUE THREAD

**Issue by zawy12** [turtlecoin/turtlecoin#131]
It looks like you're using Karbowanec's version of my old difficulty algorithm.  You should upgrade to my [LWMA algorithm](https://github.com/zawy12/difficulty-algorithms/issues/3).  Karbowanec has written code for it [here](https://github.com/zawy12/difficulty-algorithms/issues/3#issuecomment-375600752).

**Comment by RocksteadyTC** [comment]
Thanks for your work @zawy12. We will make the upgrade during our stage 2 upgrade phase of the current hashing algorithm transition. We'd like to talk more about your work, if you'd like to join us in #dev_general on chat.turtlecoin.lol for more realtime conversation.

**Comment by zawy12** [comment]
I joined.

**Comment by zawy12** [comment]
I'm there, it's just a 2 hour delay before I'm allowed to respond.
