### ISSUE TITLE
Daemon fails on pool again

### ISSUE THREAD

**Issue by Rndexspb** [turtlecoin/turtlecoin#133]
There was a network crash this night again, it was everywhere, but daemon is failing on pool always in random time...

working in while true do doesn't help, coz it's not closing, daemon just freeze and we getting orphaned blocks only... can't exit daemon in screen, @RocksteadyTC are u going to fix this fails of network and daemons???

**Comment by BKdilse** [comment]
I'm also getting regular daemon failures.

**Comment by UNIPOOL** [comment]
Same for me, I have compile the new version, and seems to get freeze , for blocks orphaned I remove the p2pstates.bin before to run again the remote node

**Comment by Rndexspb** [comment]
i've gone to public node... but in 51% attack it will be forked also, so there is no protection of network fails...

**Comment by Rndexspb** [comment]
and look steady's pool taking 60 blocks in raw...
http://slowandsteady.fun/#pool_blocks
from 16:17:00gmt

**Comment by Rndexspb** [comment]
![33](https://user-images.githubusercontent.com/36726780/38198797-dc3e9570-3696-11e8-9497-932d74efbcc6.jpg)

**Comment by Rndexspb** [comment]
what's going on, this pool HEIGHT differs from other pools, but blocks are not orphaned

**Comment by prox443** [comment]
I'm also getting regular daemon failures (1 by day) :'(

**Comment by SoreGums** [comment]
blocks in pools only orphan if the pool's daemon joins the network again and the blocks disappear.

said another way. orphan blocks only become orphan if they were known to be good 1st and then later found out to be not good (not in the main chain).

So if the pool doesn't report orphaned blocks and you know they should be, it means the pool's daemon has not caught up yet with the main chain.

**Comment by BKdilse** [comment]
Another failure last night.  Pool would not connect to daemon.  Ended up deleting blockchain download.  Currently re-synching.

Any advice on what to try in these situations?

**Comment by BKdilse** [comment]
lastest message whilst synching:

2018-Apr-08 13:52:10.312196 ERROR   Failed to query blocks: no blocks for this timestamp, too large
2018-Apr-08 13:52:12.050067 ERROR   Failed to query blocks: no blocks for this timestamp, too large
2018-Apr-08 13:52:16.526667 INFO    Block cf5530f03a0b304e97afeca826f4f60f3ca36f674586a1665dbdab531bb6b74d added to main chain. Index: 30200
*** stack smashing detected ***: /usr/local/src/turtlecoin/build/src/TurtleCoind terminated
Aborted (core dumped)

**Comment by SoreGums** [comment]
if plain restarting doesn't progress the daemon then:

stopping daemon, deleting peers.bin, starting daemon is one thing to do.

this means the daemon will contact seeds for peers and get a fresh list.
doing this means the chance of connecting to faulty peers is reduced.
mostly likely the issue is the daemon talking to faulty peers as well as other known issues.
however talking to insync/working peers is a first step at least to a working local daemon

**Comment by BKdilse** [comment]
Thanks I'll give that a go next time

**Comment by RocksteadyTC** [comment]
Please upgrade to 0.4.3 and reopen the issue if it persists. Thank you

**Comment by BKdilse** [comment]
Still a problem for me, crashed today

**Comment by bobbieltd** [comment]
@BKdilse  What do you mean “crash” ? Does it mean “out of sync” or “forking” ?
Turtlecoin  made my servers hang two times (hard reboot to back online). Do you have same problem ?

**Comment by BKdilse** [comment]
@bobbieltd by crash I mean daemon aborts.  I have not had server hangs or crashes.  I used to on other coins, so I increases ram and they seem ok.

**Comment by bobbieltd** [comment]
@BKdilse Good to hear your advice. Thanks. For daemon stopping syncing, it comes from new version and hard fork (still it’s better than old ones that keeped forking when it was lost), our pool notification mechanism can not detect that by defaut (It can only detect pool behind blocks or daemon died, still need to add codes to check with other pools’ height). Turtlecoin is the only coin that made me tired (I got to carefull survey only this pool for synchronisation).

**Comment by BKdilse** [comment]
I can handle turtlecoin, sumokoin was a pain in the ass.  Daemon was killing server, ended up getting rid of it.
