### ISSUE TITLE
[ERROR] --add-exclusive-node does not work

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#134]
TurtleCoin v0.4.2.1256 (0.1-g114aa3b)

  --add-exclusive-node arg              Specify list of peers to connect to
                                        only. If this option is given the
                                        options add-priority-node and seed-node
                                        are ignored

Daemon is connecting to other nodes via the P2P network even with the exclusive-node setting set.

**Comment by ereptor81** [comment]
It looks like this works, just not the way it seems like it should. It limits outgoing connections to the exclusive peer, but doesn't currently seem to do anything to limit incoming connections.

**Comment by brandonlehmann** [comment]
This was user error. I was not including the port in the command line arguments. This works as expected. Closing issue.
