### ISSUE TITLE
Latest Daemon - Which wallet to use in pool

### ISSUE THREAD

**Issue by BKdilse** [turtlecoin/turtlecoin#135]
Simplewallet looks too simple now, and I cannot use it as I did in the previous version, i.e. rpc bind, wallet file, password

I'm now trying walletd, but I can see warnings in the console such as:
WARNING Requested method not found: getbalance
WARNING Requested method not found: store

So I take it this will no longer work for my nodejs pool?

Could someone please clarify this?

**Comment by Bathmat** [comment]
I'm using an older version of simplewallet that seems to be working okay for now; however, I would like to see them put the rpc functionality back into simplewallet.

I suppose it won't matter if/when they switch to monero-based (assuming they also switch to that type of wallet).

I've also tried to get walletd to work with nodejs, but no luck so far.

**Comment by ZedPea** [comment]
You need to update turtle-pool to the latest version: https://github.com/turtlecoin/turtle-pool/pull/5/files

**Comment by BKdilse** [comment]
@ZedPea thanks for response, but I'm using Snipa22's pool repo, which is not the same.

@Bathmat thanks for the confirmation on using older wallet.  I was going to try that tonight, and now definitely will use it.

**Comment by BKdilse** [comment]
Can also confirm that using previous version of SimpleWallet works fine.

**Comment by krruzic** [comment]
Yes but you'll have to have that saved. Maybe a link to download the final version that supports json_rpc? This is a common issue and it should be settled. Supported or Not Supported. @ZedPea

**Comment by bobbieltd** [comment]
It seems devs will readd simplewallet as poolwallet for pool.
@Bathmat Your pool forked

**Comment by BKdilse** [comment]
Thanks @SoreGums I'm on previous version wallet for now, I'll wait for release.

**Comment by Bathmat** [comment]
I just built the latest; however, there is still no rpc functionality to use simplewallet as a pool rpc wallet. Specifically there is no `--rpc-bind-port` flag option.

**Comment by ZedPea** [comment]
If you built from source, the executable is now called poolwallet instead of simplewallet, so new users don't accidentally use it. @Bathmat

**Comment by Bathmat** [comment]
@ZedPea Ahh, I see that now.. apologies for the post.
