### ISSUE TITLE
TurtleCoind reports that it is synchronized when it's not

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#140]
At first glance, it appears that the logic falls down through this block to arrive at this block of code without confirming that at the very least ***context.m_state != CryptoNoteConnectionContext::state_synchronizing***

https://github.com/turtlecoin/turtlecoin/blob/114aa3bfc87d406106abb92e35825308e4556dac/src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp#L576

I'm flagging this here so I don't forget to take a closer look at this later.

**Comment by SoreGums** [comment]
Nice catch I've been watching this happen on my 8 nodes as well

**Comment by brandonlehmann** [comment]
@Jrel01 Please start with updating to the latest release. That being said, this is an active issue that is being tested against by multiple people.

**Comment by yamiM0NSTER** [comment]
@ereptor81 please Label as pending release
