### ISSUE TITLE
simplewallet rpc gone; getbalance not working on walletd

### ISSUE THREAD

**Issue by blakelapierre** [turtlecoin/turtlecoin#146]
With the new update, all RPC functionality seems to have disappeared from simplewallet; breaking systems relying on that functionality.

Also, 'getbalance' does not seem to work with walletd's RPC service.

How do we programatically get the balance of a wallet?

**Comment by ereptor81** [comment]
getBalance: https://wiki.bytecoin.org/wiki/Bytecoin_RPC_Wallet_JSON_RPC_API

There's currently a PR open to merge the old simplewallet back in to give people time to update, but it's deprecated in favor of walletd.
