### ISSUE TITLE
simplewallet no longer supports --wallet command line argument

### ISSUE THREAD

**Issue by marvin8** [turtlecoin/turtlecoin#153]
Current release (v0.4.2)[https://github.com/turtlecoin/turtlecoin/releases/tag/v0.4.2] version of simplewallet no longer supports --wallet command line argument.

Can this be re-enabled again, please?

Previously I was able to create an alias that included the simplewallet command and the path to the wallet file so I didn't need to type in the full wallet path when starting simplewallet.

**Comment by ZedPea** [comment]
Build from source, it has been re-added, and will be in the next release.

Sorry for the trouble.

**Comment by marvin8** [comment]
Awesome.... Thank you for the quick response!

Love TurtleCoin :)

**Comment by yamiM0NSTER** [comment]
@ereptor81 please Label as pending release
