### ISSUE TITLE
the command line option "--daemon-host" stopped working

### ISSUE THREAD

**Issue by browolf** [turtlecoin/turtlecoin#164]
Did this get removed or something? because since upgrading simplewallet at fork it's not worked. This was the 100% guaranteed way I could get simplewallet to work :(

**Comment by ZedPea** [comment]
Use `--remote-daemon` instead. If you're using simplewallet v0.4.3 you don't need to specify the port, if you're using v0.4.2 you do. 

For future reference, most command line programs support a `--help` flag which lists all available arguments.

**Comment by ZedPea** [comment]
Sorry about that. To used to linux :p
