### ISSUE TITLE
v0.4.3 crashing on launch for some people

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtlecoin#171]
As the title says, v0.4.3 has been crashing on launch for some users, whilst v0.4.2 is fine. 

It's reported to crash with TurtleCoind, and possibly walletd, but nothing else.

Some people appear to get a "TurtleCoind has stopped working" whilst for others it just instantly closes. The obvious difference between the two releases is the RocksDB upgrade. If someone who could reproduce this could do a `git bisect`, that would be great to confirm if it is due to RocksDB or not.

Nothing is seen in command prompt if the process is launched from there. I'm not sure if anyone has tried running with `--log-level 4` yet.

People who have this issue have also reported that compiling doesn't fix the issue. I have seen reports of this on both Windows 10 and Windows 7, but not anyone having it on GNU/Linux yet.

One person who experienced this suggested that the error message they were receiving indicated the crash was due to an "Illegal Instruction", which is commonly seen when software is ran on hardware it's not compiled for - This is not the case however if people can reproduce it when compiling themselves presumably.

**Comment by ZedPea** [comment]
Turtle? gave this error information, running walletd on Windows 7.

```
Problem signature:
  Problem Event Name:    APPCRASH
  Application Name:    walletd.exe
  Application Version:    0.0.0.0
  Application Timestamp:    5acea4cc
  Fault Module Name:    walletd.exe
  Fault Module Version:    0.0.0.0
  Fault Module Timestamp:    5acea4cc
  Exception Code:    c000001d
  Exception Offset:    00000000002e3d8b
  OS Version:    6.1.7601.2.1.0.256.1
  Locale ID:    2057
  Additional Information 1:    670f
  Additional Information 2:    670f4e457958ecb5a65cbae63a61a4ad
  Additional Information 3:    5498
  Additional Information 4:    549806130bd7a661512d53f284373a32
```

**Comment by brandonlehmann** [comment]
Does this occur if you nuke the DB folder and p2pstate.bin?

**Comment by ZedPea** [comment]
I'm fairly sure someone tried this yesterday and it still occurred. Clarification would be good though.

**Comment by ZedPea** [comment]
Just got Turtle? to test this, still occurs when no TurtleCoin folder is present

**Comment by brandonlehmann** [comment]
Can he confirm the file version when right clicking on the program, properties, details? Is he launching it with or without arguments?

**Comment by brandonlehmann** [comment]
And is he using precompiled or compile himself?

**Comment by ZedPea** [comment]
@brandonlehmann Both precompiled and self compiled failed, he's running a git bisect atm. Launching walletd with just `-h` crashed, which shouldn't be touching much code.

**Comment by ZedPea** [comment]
Closing as the cause has been found and fixed.
