### ISSUE TITLE
[Concept] TNS

### ISSUE THREAD

**Issue by yamiM0NSTER** [turtlecoin/turtlecoin#176]
I was discussing p2p protocol upgrade with others and we came to conclusion that leading daemon versioning is not enough to set a standard for the network (opinion of others), so here we are.

TNS - [T]urtlecoin [N]etwork [S]tandard

Basically, it's a list of requirements for any application that wants to be part of Network ecosystem.
Versioning would be split into:

- Major version (basically huge changes, forks)
- Minor version (deprecation of old methods, killing too old nodes support(?))

**NOTE:** TNS doesn't list application specific changes for example:

- database engine changes
- Whatever changes are in communication with user
- handling method change of received data (as long as it still meets network requirements in the end)

When p2p protocol would be upgraded information about supported TNS would be required in p2p handshake.

Pros:
- ability to deprecate anything.
- ability to cut off from outdated daemons
- available list of changes required for projects that want to be part of ecosystem.

Cons:
- somebody has to keep track of all the changes
- has to be always up to date with releases(if not sooner)

**Comment by SoreGums** [comment]
The biggest point of the versioning the network p2p protocol is to give peers the opportunity to continue or reject the connections. 

an older protocol peer could be supported by newer protocol peers if those newer peers wanted to talk to these older protocol peers. Right now there is no option available, newer peers simply have to deal with older peers until it gets to a point that the newer peer can recognise that they are chatting with an older protocol peer and kill the connection.

Going forward the protocol version will give peers the opportunity up front to continue or reject connections. 

I don't see the actual protocol changing too much in the future. The biggest point of it is to address fixes in the current daemon and stop being impacted negatively by older daemons that aren't upgraded.

Also doing it this way means any other peer written in any language can join the network and as long as they follow the p2p spec they should be able to communicate with all peers in the network.

Should we write up a formal spec now then?
What did you see happening next @yamiM0NSTER to make this concept a reality?

**Comment by yamiM0NSTER** [comment]
> The biggest point of the versioning the network p2p protocol is to give peers the opportunity to continue or reject the connections.

No. Right now p2p protocol version means nothing because every daemon has same version. What you are talking about is what I am trying to make happen.

>an older protocol peer could be supported by newer protocol peers if those newer peers wanted to talk to these older protocol peers. Right now there is no option available, newer peers simply have to deal with older peers until it gets to a point that the newer peer can recognise that they are chatting with an older protocol peer and kill the connection.

That's what this thing is about.

> Going forward the protocol version will give peers the opportunity up front to continue or reject connections.

That's not how protocols are constructed. Anyone serious will laugh at you if they hear you want to constantly change protocol version on weekly/monthly basis.

> I don't see the actual protocol changing too much in the future. The biggest point of it is to address fixes in the current daemon and stop being impacted negatively by older daemons that aren't upgraded.

Because that's not what protocol versioning is for.

> Also doing it this way means any other peer written in any language can join the network and as long as they follow the p2p spec they should be able to communicate with all peers in the network.

That's what TNS(placeholder name) is for, so people like you that don't acknowledge leading software as standard don't BabyRage. Looking forward to see you volunteer to maintain that thing.

> Should we write up a formal spec now then?

No?

> What did you see happening next @yamiM0NSTER to make this concept a reality?

Your post ensures me that you either don't care to read things or have no idea what you are talking about. This was posted way back on discord: https://i.imgur.com/5r7Aik2.jpg TNS replacing daemon version of course and some other things changed.

**Comment by SoreGums** [comment]
every time I read this https://i.imgur.com/5r7Aik2.jpg

I see this

1. peerA connects to another peerB
2. peerA is a cpp daemon asks for daemon version
3. peerB is not a cpp daemon and doesn't care what cpp daemon version peerA is - peerB just wants to send and receive blocks and transactions

Block and Transaction exchanging is all the p2p network is used for.

I keep going on about using a p2p protocol version because that is what it needs to be (no peer should care what version each other's code internally is at). Referring me to an image that says "a daemon version is requested" is going to yield a consistent response from me, the daemon version doesn't matter, it needs to be a p2p version. The code currently has a constant defined for a p2p version, however, it doesn't seem to be used. If it is used then we don't even need this concept, it already exists.

My post above was if p2p protocol version worked it could enable the things I talked about...

**Comment by brandonlehmann** [comment]
I agree with @SoreGums 

The Protocol version is independent of the program and/or service using it. This is no different than there are a variety of web browsers of many different versions; however, they all support HTTP 1.0 and (hopefully) HTTP 1.1 among other underlying protocols.

There is no reason to upgrade and/or *require* adoption of an updated protocol with every release of TurtleCoin. Even if there is no change. There would only need to be a protocol upgrade when we want to support something new, remove support for something old, or change some other fundamental structure of the protocol itself.

All that being said, it looks like the node data exchanged during the handshake already contains the version...

https://github.com/turtlecoin/turtlecoin/blob/a902436caf42f4dcd5a7d71b492db40e821b7907/src/P2p/P2pProtocolDefinitions.h#L64
https://github.com/turtlecoin/turtlecoin/blob/a902436caf42f4dcd5a7d71b492db40e821b7907/src/P2p/P2pProtocolDefinitions.h#L107
https://github.com/turtlecoin/turtlecoin/blob/a902436caf42f4dcd5a7d71b492db40e821b7907/src/P2p/P2pNode.cpp#L454

Then down here, the connections are handled... as we can see the node is rejected if the networkId doesn't match
https://github.com/turtlecoin/turtlecoin/blob/a902436caf42f4dcd5a7d71b492db40e821b7907/src/P2p/P2pNode.cpp#L536

To implement a new protocol version (even if just superficial):

https://github.com/turtlecoin/turtlecoin/blob/a902436caf42f4dcd5a7d71b492db40e821b7907/src/P2p/P2pProtocolDefinitions.h#L55

```c
  enum P2PProtocolVersion : uint8_t {
    V0 = 0,
    V1 = 1,
    V2 = 2,
    CURRENT = V2
  };
```

To block older versions once implemented, I believe all we'd need to do is update *P2pNode::handleNodeData* to the following:

```c
void P2pNode::handleNodeData(const basic_node_data& node, P2pContext& context) {
  if (node.network_id != m_cfg.getNetworkId()) {
    std::ostringstream msg;
    msg << context << "COMMAND_HANDSHAKE Failed, wrong network!  (" << node.network_id << ")";
    throw std::runtime_error(msg.str());
  }

  if (node.version < P2PProtocolVersion::CURRENT) {
    std::ostringstream msg;
    msg << context << "COMMAND_HANDSHAKE Failed, Invalid P2P Protocol Version!  (" << node.version<< ")";
    throw std::runtime_error(msg.str());
  }

  if (node.peer_id == m_myPeerId)  {
    throw std::runtime_error("Connection to self detected");
  }

  context.setPeerInfo(node.version, node.peer_id, static_cast<uint16_t>(node.my_port));
  if (!context.isIncoming()) {
    m_peerlist.set_peer_just_seen(node.peer_id, context.getRemoteAddress());
  }
}
```

Just some things to look at before we go too far down a different rabbit hole.

**Comment by yamiM0NSTER** [comment]
@brandonlehmann I think you took wrong nickname.

**Comment by brandonlehmann** [comment]
The p2p protocol would be included in the TurtleCoin Network Standard and you mentioned it in your original post...

If you're working under the premise that you're working for a **documentation standard** then I'm of the mindset that this issue doesn't belong under this repo. Perhaps the wiki is a better place.
