### ISSUE TITLE
How to use a Remote Node with CLI?

### ISSUE THREAD

**Issue by pikomule** [turtlecoin/turtlecoin#178]
Not work:
simplewallet.exe --daemon-host public.turtlenode.io --daemon-port 11898
=================================================
Result:
It looks like TurtleCoind isn't open!

Ensure TurtleCoind is open and has finished initializing.
If it's still not working, try restarting TurtleCoind. The daemon sometimes gets
 stuck.
Alternatively, perhaps TurtleCoind can't communicate with any peers.

The wallet can't function until it can communicate with the network.
=================================================

what is the problem? with other nodes the same problem

**Comment by brandonlehmann** [comment]
Simple Wallet CLI syntax changed. Please use:

v0.4.2+: simplewallet.exe --remote-daemon public.turtlenode.io:11898

**Comment by pikomule** [comment]
perfect. thanks

**Comment by SoreGums** [comment]
looks like issue is resolved, closing
