### ISSUE TITLE
New TurtleCoind (binary) crashes under Linux 

### ISSUE THREAD

**Issue by aleqx** [turtlecoin/turtlecoin#180]
Just like the one on WIndows which I reported earlier, TurtleCoind (from the released binaries) also crashes under Linux

```
# TurtleCoind
2018-Apr-16 23:45:10.517000 INFO    Welcome to TurtleCoin v0.4.3.1257 ()
2018-Apr-16 23:45:10.517271 INFO    Module folder: TurtleCoind
2018-Apr-16 23:45:10.517485 INFO    Opening DB in /root/.TurtleCoin/DB
2018-Apr-16 23:45:14.507715 INFO    DB opened in /root/.TurtleCoin/DB
2018-Apr-16 23:45:14.512374 INFO    Initializing core...
2018-Apr-16 23:45:14.537125 INFO    Importing blocks from blockchain storage
2018-Apr-16 23:45:19.358611 INFO    Imported block with index 357000 / 364247
2018-Apr-16 23:45:25.180082 INFO    Imported block with index 358000 / 364247
2018-Apr-16 23:45:31.474518 INFO    Imported block with index 359000 / 364247
2018-Apr-16 23:45:37.435545 INFO    Imported block with index 360000 / 364247
2018-Apr-16 23:45:43.464737 INFO    Imported block with index 361000 / 364247
2018-Apr-16 23:45:50.664070 INFO    Imported block with index 362000 / 364247
2018-Apr-16 23:45:57.293755 INFO    Imported block with index 363000 / 364247
2018-Apr-16 23:46:03.045761 INFO    Imported block with index 364000 / 364247
2018-Apr-16 23:46:04.476071 INFO    Core initialized OK
2018-Apr-16 23:46:04.476193 INFO    Initializing p2p server...
Illegal instruction (core dumped)
```

It seems that these binaries were not tested (enough). They shouldn't have been released as final. You should consider tagging these releases as `-alpha` so that folks expect bugs.

**Comment by ereptor81** [comment]
Is this from the static or non-static build ? Please try the other if you have not

**Comment by brandonlehmann** [comment]
Which OS are you running? Which release of that OS?

**Comment by aleqx** [comment]
Dynamic release. Ubuntu 16.04.3.

**Comment by brandonlehmann** [comment]
Try the static release.

**Comment by aleqx** [comment]
Static works.

Back to seeing wrong block versions, alternative chains, orphans, invalid tx (already in queue) ... is the chain (still) being attacked or are these yet more bugs?

```
2018-Apr-17 00:07:48.980162 INFO    Block b3ead21ea945adc310e675fde4dce3a581047200d0841c84520f2756bf04d93c added to main chain. Index: 374700
2018-Apr-17 00:41:45.429948 WARNING Failed to validate block bb1eb6053e11bf8f735484842a9e7be26483344382a3ca98aeaca743a3eb63e1: Wrong block version
2018-Apr-17 00:42:11.917676 WARNING Failed to validate block bb1eb6053e11bf8f735484842a9e7be26483344382a3ca98aeaca743a3eb63e1: Wrong block version
2018-Apr-17 00:58:16.605246 INFO    Block 1364d01a35a79e46e605c30ce616f9837c5852c5ef4c9bec04f60b81c8fba97e added to main chain. Index: 374800
2018-Apr-17 01:05:29.898338 WARNING Failed to validate block bb1eb6053e11bf8f735484842a9e7be26483344382a3ca98aeaca743a3eb63e1: Wrong block version
2018-Apr-17 01:08:17.393930 WARNING Transaction 3ecbd5c35d83e76ce73dd5b37ba6adce60387d4f711f5a48d0968dbb91478a17 is not valid. Reason: Transaction is already present in the queue
2018-Apr-17 01:08:30.793337 WARNING Transaction 3a427f3b71a7925c74f718e50cf8d9405d189d9eece628702914d260ea07e84b is not valid. Reason: Transaction is already present in the queue
2018-Apr-17 01:09:14.311712 WARNING Transaction c35adab77551fe6b059a93a630ffebb87760e847deea0fe65bf5d19d95de0013 is not valid. Reason: Transaction is already present in the queue
```

```
2018-Apr-17 00:02:13.025311 WARNING Block b76139ce731ddb1c244dab44277b4551cfa7cd66d465c17244ad74ff1bde007a rejected as orphaned
2018-Apr-17 00:02:13.025405 INFO    [2.25.39.145:11897 OUT] Block received at sync phase was marked as orphaned, dropping connection: Block rejected as orphaned
2018-Apr-17 00:02:20.734043 WARNING Block 8a7cae305e6bde1155e1adee72c5723c5cf516e27007b9d79231cb7662e5c081 added to alternative chain. Index: 373075
2018-Apr-17 00:02:20.745289 WARNING Block 834241206b0b89459a248446cc6aaf8d8483d3c004ed461e26740267bf97532c added to alternative chain. Index: 373076
2018-Apr-17 00:02:20.756906 WARNING Block 1757a035231a1a7c0ddd04523a4a6e3b782a694f97688e2f478c85f27e53edef added to alternative chain. Index: 373077
2018-Apr-17 00:02:20.767924 WARNING Block febb597ca577c41579ec7be37eaee71ea48ca743730a8a0a309a529fa71a6456 added to alternative chain. Index: 373078
```

**Comment by ereptor81** [comment]
That's all normal. The block version validation issues are just old clients who haven't updated.

**Comment by aleqx** [comment]
What about the `alternative chain` and `invalid tx (already in queue)` messages?

**Comment by ZedPea** [comment]
Invalid tx just refers to a transaction your daemon has already seen that was resubmitted by another daemon, it is already present in the memory pool so doesn't need to be readded.

You see the alternative chain messages reasonably frequently because with a fast block time of 30 seconds, it's quite common for two chains to find a block at once and then they have to compete to see which chain finds the next block first, and then the other is abandoned.

**Comment by ereptor81** [comment]
Invalid tx is peers broadcasting txns which you may have already seen and alt chain is going to show up occasionally as parallel chains pop up and go away. Both expected and normal. It's generally fine to just ignore Turtlecoind output unless it's not syncing.

**Comment by aleqx** [comment]
Thanks both for explaining. The invalid tx makes sense. Regarding the alternative chain messages, shouldn't there always be a message regarding orphan blocks after each alternative chain message? Or are the blocks that were found on the other chain silently dropped without any orphan message?

**Comment by ZedPea** [comment]
If another daemon submits one of the blocks on the dropped chain then you might see "Block rejected as orphaned" but that's only if you re-receive the block.

**Comment by SoreGums** [comment]
orphan blocks only work outside of the daemon as far as I can tell.

daemons don't really track it, other than to reject a block that is invalid due to that other daemon being out of sync.

a block explorer or pool can track orphan blocks if it keeps a list of blocks and verifies if they are in the current chain or not. daemon should discard alternative chains after some time since they just take up space and are useless once the main chain gets far enough ahead.

**Comment by aleqx** [comment]
@SoreGums my daemon lists a lot of `WARNING Block <hash> rejected as orphaned` messages, so it looks like it tracks them. but likely not all of them.

**Comment by ereptor81** [comment]
https://github.com/turtlecoin/turtlecoin/blob/master/scripts/build-release.sh#L51
