### ISSUE TITLE
Cannot exit daemon on Linux

### ISSUE THREAD

**Issue by Cat5TV** [turtlecoin/turtlecoin#183]
[https://media.discordapp.net/attachments/388915017963143169/435884453391237120/Screenshot_from_2018-04-17_15-26-15.png?width=501&height=393](https://media.discordapp.net/attachments/388915017963143169/435884453391237120/Screenshot_from_2018-04-17_15-26-15.png?width=501&height=393)

Typing exit in TurtleCoind acknowledges the request, but days later still has not exited. Then typing exit again does nothing, and ctrl-c again acknowledges the request but does nothing. Only option is to kill the daemon, which is hacky and not lovely.

Running 0.4.2 on Elementary (Ubuntu). Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yamiM0NSTER** [comment]
version 0.4.2 uses old version of rocksdb and is known to have issues exiting.

**Comment by mdiersma** [comment]
Had it once or twice also on the new daemon. 0.4.3

**Comment by brandonlehmann** [comment]
Any idea of how many connections were active on the p2p side?

**Comment by mdiersma** [comment]
No sorry, but I'll make a copy of the log next time

**Comment by brandonlehmann** [comment]
No problem. The more information you can provide on the state of the daemon when this occurs the more likely we'll be able to isolate the issue and resolve it.

**Comment by BKdilse** [comment]
I've also seen this a few times, and have lost patience, and ended up killing the process.  I'll try and grab details when it happens again.
