### ISSUE TITLE
Simplewallet Transfer Command

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#186]
Entering "transfer " (with a space, or any number of spaces after it, confuses the client. I'm aware I shouldn't do this... but in the event I have a heavy handed thumb, perhaps it would be a good idea to strip leading and trailing spaces and then verify argument counts?

**Comment by brandonlehmann** [comment]
Also...

```text
[TRTL blehmann-miner.bin]: transfer
What address do you want to transfer to?: Address is wrong length!Saving wallet and shutting down, please wait...
It should be 99 characters long, but it is 0 characters long!

What address do you want to Terminate batch job (Y/N)?
```

I am currently unsure how to answer this question.

**Comment by ZedPea** [comment]
Will fix this. 

I'm not sure the best way to cancel a transfer in a nice way, other than just cancelling on bad inputs but it seems preferable to reprompt if you're in the middle of a transfer. 

I suppose I could just let people enter "cancel" or something at every prompt, I don't think there's any situation where that would be a valid input so it wouldn't mess anything up.

Thanks for the report.

**Comment by brandonlehmann** [comment]
That would work. Some keyword to cancel/stop/abort would be awesome.
