### ISSUE TITLE
Trouble building on Ubuntu (src/CMakeFiles/Mnemonics.dir/Mnemonics/electrum-words.cpp.o' failed)

### ISSUE THREAD

**Issue by pgenho** [turtlecoin/turtlecoin#188]
> src/CMakeFiles/Mnemonics.dir/build.make:62: recipe for target 'src/CMakeFiles/Mnemonics.dir/Mnemonics/electrum-words.cpp.o' failed
> make[2]: *** [src/CMakeFiles/Mnemonics.dir/Mnemonics/electrum-words.cpp.o] Error 4
> CMakeFiles/Makefile2:478: recipe for target 'src/CMakeFiles/Mnemonics.dir/all' failed
> make[1]: *** [src/CMakeFiles/Mnemonics.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2

Built successfully before the fork using same system.

Possibly in this commit? Maybe type casting although I don't know enough c++ to say.

https://github.com/turtlecoin/turtlecoin/commit/b557777e27ce8cd9a032aca0f1bce19c6519bd5d

Perhaps I'm missing something but don't know what.

**Comment by ZedPea** [comment]
If you try building again (might need to do it a few times because the make throws out a ton of warnings) you should be able to get it to a state where it gives you the actual compilation error message, which could help track it down.

**Comment by pgenho** [comment]
This might have something to do with it.

![screenshot at 2018-04-20 23-23-36](https://user-images.githubusercontent.com/19272878/39080770-85f61228-44f2-11e8-89b4-f8eb2c977f1c.png)

**Comment by pgenho** [comment]
I think constrained resources (memory?) was the problem.

Killing some other processes allowed full build to occur. Strange it worked on earlier version of turtlecoin but maybe system had less going on at that time.

Closing issue.
