### ISSUE TITLE
Simple wallet turtle coin v0.4.4 osx 

### ISSUE THREAD

**Issue by alxgarza** [turtlecoin/turtlecoin#196]
Running simplewallet on OS 10.11.6 always crashes at launch with error: "Illegal instruction: 4"

**Comment by alxgarza** [comment]
More information....  The error: "Illegal instruction: 4".  Only crashes with the binary download.

If I build it.  It works fine.

**Comment by SoreGums** [comment]
I'm guessing that is the same issue that was encountered on windows - CPU features missing. However, Google results indicate an OS level optimisation. Maybe mac release binaries need the flag set to enable maximum compatibility: `-mmacosx-version-min=10.x ` 

see if anyone has any info.

btw, he said he was running El Capitan v10.11.6

**Comment by ereptor81** [comment]
Was built on same machine (10.12.6) w/ same make command as 0.4.3, so not really sure what changed to break it for some people. The only thing really different in the build is excluding the avx stuff, but that shouldn't matter. I'll look into the min version thing and see if I can find a machine w/ the problem to test on.

**Comment by alxgarza** [comment]
The binaries poolwallet, simple wallet, walletd and  Turtlecoind all give the error: "Illegal instruction: 4" at launch.

But all of them run fine if I build them from scratch.  
I built them as described on the readme: cmake ..  and make

**Comment by hensleyrob** [comment]
Same here, release binaries fail with "Illegal instruction: 4" but building from source works fine.

I'm running 10.11.6 on an iMac8,1.

**Comment by RocksteadyTC** [comment]
0.4.4 was a temporary release to test the CI toolchain. Closing this until the next 0.4.4 which may address this issue with proper compiles before being released.
