### ISSUE TITLE
Simplewallet transfer command is not strict enough

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtlecoin#240]
If you use `transfer mixin address amount` instead of just `transfer`, the error handling is a bit weak. For example, if you put a payment ID at the end of the string without a -p, the transfer will still continue, but no payment ID will be used.

It will show up with no payment ID in conformation, but should still be fixed. I will work on this at some point, just putting it here so I don't forget.

Could also be a good first issue for some new programmers, you would want to be looking at `transfer()` in `src/SimpleWallet/Transfer.cpp`

**Comment by RocksteadyTC** [comment]
Bounty 50k - Great idea Z, this would be a good entry for a new dev-turtle

**Comment by RocksteadyTC** [comment]
this has been pinned in Bounties
