### ISSUE TITLE
Latest Daemon and will not stay running

### ISSUE THREAD

**Issue by swanseahost** [turtlecoin/turtlecoin#246]
2018-May-28 12:19:35.858921 INFO    [165.227.194.76:11897 OUT] Your TurtleCoin node is syncing with the network. You are 52921 blocks (18 days) behind the Hare. Slow and steady wins the race!
2018-May-28 12:19:35.859208 INFO    New Top Block Detected: 489633
2018-May-28 12:19:36.673974 INFO    [94.177.190.223:11897 OUT] Your TurtleCoin node is syncing with the network. You are 52921 blocks (18 days) behind the Hare. Slow and steady wins the race!
2018-May-28 12:19:37.107685 INFO    [159.65.238.221:11897 OUT] Your TurtleCoin node is syncing with the network. You are 52921 blocks (18 days) behind the Hare. Slow and steady wins the race!
Bus error (core dumped)
miner@turtle:~/turtlecoin/build/src$

**Comment by SoreGums** [comment]
around this time is when we had issues. keep restarting and it'll eventually get past it.

you could also download the checkpoints file and start with checkpoints flag, available here

- https://github.com/turtlecoin/checkpoints

**Comment by swanseahost** [comment]
Thanks! Works!

**Comment by SoreGums** [comment]
good stuff, going to close this now - thanks for the update ! ;)
