### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by darutse** [turtlecoin/turtlecoin#251]
Arch Linux
./TurtleCoind
Illegal instruction (core dumped)

ldd ./TurtleCoind 
	linux-vdso.so.1 (0x00007fff423d7000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007fb27f7b2000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fb27f41d000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb27f1ff000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fb27ee43000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb27f9ba000)

Compiling also exits with an error

**Comment by darutse** [comment]
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-fassociative-math" -DCMAKE_CXX_FLAGS="-fassociative-math" -DSTATIC=true -DDO_TESTS=OFF

> -- BUILD TESTS: disabled
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- JNI library is disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/arch/downloads/turtlecoin-0.5.0/build/rocksdb
-- Configuring done
-- Generating done
-- Build files have been written to: /home/arch/downloads/turtlecoin-0.5.0/build

make
> [ 34%] Building CXX object CMakeFiles/rocksdb.dir/monitoring/thread_status_updater.cc.o
[ 34%] Building CXX object CMakeFiles/rocksdb.dir/monitoring/thread_status_util.cc.o
[ 34%] Building CXX object CMakeFiles/rocksdb.dir/monitoring/thread_status_util_debug.cc.o
[ 34%] Building CXX object CMakeFiles/rocksdb.dir/options/cf_options.cc.o
cc1plus: all warnings being treated as errors
make[6]: *** [CMakeFiles/rocksdb.dir/build.make:895: CMakeFiles/rocksdb.dir/memtable/skiplistrep.cc.o] Error 1
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [CMakeFiles/Makefile2:2780: CMakeFiles/rocksdb.dir/all] Error 2
make[4]: *** [CMakeFiles/Makefile2:2792: CMakeFiles/rocksdb.dir/rule] Error 2
make[3]: *** [Makefile:1059: rocksdb] Error 2
make[2]: *** [external/CMakeFiles/rocksdb.dir/build.make:57: external/CMakeFiles/rocksdb] Error 2
make[1]: *** [CMakeFiles/Makefile2:124: external/CMakeFiles/rocksdb.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by ZedPea** [comment]
Can you re-run make until you can isolate the actual compiler error, it usually prints out a lot of stuff after the error because it runs multiple threads, if you re-run it till it only fails on that that would help us diagnose the error . I am using arch and it builds correctly.

**Comment by darutse** [comment]
@ZedPea 

> ........
make[2]: *** [src/CMakeFiles/CryptoNoteCore.dir/build.make:375: src/CMakeFiles/CryptoNoteCore.dir/CryptoNoteCore/DatabaseBlockchainCache.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:696: src/CMakeFiles/CryptoNoteCore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

with make -j 12:
> ........
make[2]: *** [src/CMakeFiles/CryptoNoteCore.dir/build.make:375: src/CMakeFiles/CryptoNoteCore.dir/CryptoNoteCore/DatabaseBlockchainCache.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:696: src/CMakeFiles/CryptoNoteCore.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[5]: *** [CMakeFiles/Makefile2:2780: CMakeFiles/rocksdb.dir/all] Error 2
make[4]: *** [CMakeFiles/Makefile2:2792: CMakeFiles/rocksdb.dir/rule] Error 2
make[3]: *** [Makefile:1059: rocksdb] Error 2
make[2]: *** [external/CMakeFiles/rocksdb.dir/build.make:57: external/CMakeFiles/rocksdb] Error 2
make[1]: *** [CMakeFiles/Makefile2:124: external/CMakeFiles/rocksdb.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by ZedPea** [comment]
There should be an actual error further up in the output rather than the make[x] errors, giving the compilation fail error, file, and line number etc.

**Comment by darutse** [comment]
there is only one red error in the output:
/usr/include/boost/iterator/iterator_facade.hpp:562:13: error: ‘class CryptoNote::{anonymous}::DbOutputConstIterator’ has no member named ‘decrement’; did you mean ‘increment’?
           f.decrement();

**Comment by ZedPea** [comment]
Ok, this should have been fixed in master - are you using the latest source code?

**Comment by darutse** [comment]
I've been using the source code from latest release page.
Now have tied master, but it still spits the same error:

> /usr/include/boost/iterator/iterator_facade.hpp:562:13: error: ‘class CryptoNote::{anonymous}::DbOutputConstIterator’ has no member named ‘decrement’; did you mean ‘increment’?
           f.decrement();
           ~~^~~~~~~~~
           increment
make[2]: *** [src/CMakeFiles/CryptoNoteCore.dir/build.make:375: src/CMakeFiles/CryptoNoteCore.dir/CryptoNoteCore/DatabaseBlockchainCache.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:793: src/CMakeFiles/CryptoNoteCore.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by ZedPea** [comment]
How are you pulling the source code? If you go to `src/CryptoNoteCore/DataBaseBlockchainCache.cpp` you should see

```
void decrement() {
    --globalOutputIndex;
}
```

At line 306 if you have cloned the correct code.

**Comment by darutse** [comment]
Sorry, at second try it builds successfully, maybe I didn't purge the build directory or messed up the versions. All good now. Syncing.
