### ISSUE TITLE
Turtlecoin and Rasbian fix release - Update coming?

### ISSUE THREAD

**Issue by AIX-SSMOKED** [turtlecoin/turtlecoin#254]
Hey guys.. I saw that there was a fix release in xmrig version 2.6.2 the issue I'm experiencing below but I'm not finding a compiled version for Rasbian. Anyone know of a way to work around this? I'm running a Pi3 and followed the guide below (Which appears to have been updated recently). Any help would be greatly appreciated.
https://github.com/turtlecoin/turtlecoin/wiki/Mining-with-SBC

pi@raspberrypi:~/rPi-xmrig-gcc7.3.0-2.6.0-beta1 $ ./start.sh
./xmrig: error while loading shared libraries: libmicrohttpd.so.12: cannot open shared object file: No such file or directory

**Comment by ereptor81** [comment]
Try `apt-get install libmicrohttp-dev`  if that doesn't do it, you'll need to compile it yourself without the http stuff turned on.
