### ISSUE TITLE
.wallet extension 

### ISSUE THREAD

**Issue by ghost** [turtlecoin/turtlecoin#255]
TurtleCoin is the only coin I came across that appends .wallet extension to its wallet files automatically. When I created my wallet I named it TRTL.wallet out of habit, but later noticed that it actually calls TRTL.wallet.wallet
What is the reason of breaking common untold standards. If you ask the user to create a wallet file and that would be the only file with such name in the folder, there shouldn't be any possible misunderstanding?
And also while we at it, in the logged in wallet, the command prompt starts with TRTL, which becomes [TRTL TRTL] for me, something tells me I'm not that original in calling wallet file by coin ticker, that would mean that this [TRTL TRTL] thing is common for many other users too, shouldn't it be wallet name + first digits of a wallet instead?

**Comment by ZedPea** [comment]
This was done to maintain compatibility with legacy simplewallet, which a lot of coins use, and appends a .wallet to the end of the filename.

Furthermore, we did discuss removing it, but as a lot of users are windows users, and probably a little less tech savvy. If an extension is not added, it's a bit harder to tell what the actual file is when you perhaps come back to it later, I think a .wallet extension will help the users to remember "This is a wallet, don't delete it!"

In regards to the prompt, it was chosen somewhat arbitrarily. Can you expand on what you mean by "wallet name + first digits of a wallet"?

**Comment by RocksteadyTC** [comment]
I assume he means the name he gave the wallet, let's say it's called `ornary.wallet` then his prompt would be `[Ornary TRTL]` since TRTL is the "first digits" of every address

**Comment by ZedPea** [comment]
This would still result in his wallet being called [TRTL TRTL] if he chose TRTL as the name, which I think is his gripe.

**Comment by RocksteadyTC** [comment]
@darutse can you refine said gripe with a few examples plz

**Comment by ZedPea** [comment]
For me it helps tell what wallet I'm currently using. I usually name my testnet wallets `testnet` or `lwma` so I can easily tell I'm not accidentally sending funds from a mainnet wallet.

I don't particularly see the other suggestions having much utility over the current prompt, it doesn't really gain you anything showing a small amount of your address. I suppose you could just drop the leading "TRTL" and just show the wallet name but it helps increase brand awareness, and now and also helps you know you're using a TRTL wallet and not some other wallet that has forked our code.
