### ISSUE TITLE
build fails without additional CXX_FLAGS

### ISSUE THREAD

**Issue by paulie-g** [turtlecoin/turtlecoin#26]
trtl/src/turtlecoin/src/BlockchainExplorer/BlockchainExplorer.cpp:149:1: error: ‘CryptoNote::BlockchainExplorer::database’ is initialized with itself [-Werror=init-self]
BlockchainExplorer::BlockchainExplorer(INode& node, Logging::ILogger& logger) :

Passing CXX_FLAGS="-Wno-init-self" to make kludge-fixes it, but the error ought to be checked. If it isn't meaningful, remove -Werror=init-self from CXX_FLAGS in cmake or apply syntax fix; if it is, fix it substantively.

**Comment by SoreGums** [comment]
Builds have been working fine for a while now - will close if no response received in 24hrs
