### ISSUE TITLE
Turtlecoind killed 9 on startup / memory leak?

### ISSUE THREAD

**Issue by fexra** [turtlecoin/turtlecoin#261]
Some unix users been receiving killed 9 error when starting Turtlecoind, when I just worked fine before (nothing changed). Screenshot below is an example. I think this could be related to the recent troubles we been having with the walledt where it won't sync and eats up a lot of RAM.

![error](https://cdn.discordapp.com/attachments/400081078473326603/453493632612171796/Screen_Shot_2018-06-05_at_11.41.14.png)

Block the user (in above screenshot) got stuck on.

``ab13c376730a2d4c8d46152af23d0ede6f36c5ff24edf8de8823b90b2bfdfe56``

Seems a weird size. I tried looking at the transaction through walletd:

```curl -X POST -i -H "Accept: application/json" -d '{"params": {"transactionHash":"ab13c376730a2d4c8d46152af23d0ede6f36c5ff24edf8de8823b90b2bfdfe56"},"jsonrpc": "2.0", "id": "test","method":"getTransaction"}' http://localhost:8070/json_rpc```

which outputs the following

```
{"error":{"code":-32700,"data":{"application_code":23},"message":"Object not found"},"id":"test","jsonrpc":"2.0"}
```

However,[ it does exist on the block explorer.](https://blocks.turtle.link/?hash=ab13c376730a2d4c8d46152af23d0ede6f36c5ff24edf8de8823b90b2bfdfe56#blockchain_transaction)

**Comment by bobbieltd** [comment]
+2, I have this issue on two servers, memory leak.

**Comment by fexra** [comment]
@bobbieltd could you please elaborate? Share some output and information like on what block it gets stuck?

**Comment by fexra** [comment]
I looked up the transactionHash ``ab13c376730a2d4c8d46152af23d0ede6f36c5ff24edf8de8823b90b2bfdfe56`` which seems to not exist.

**Comment by plscks** [comment]
I have had RAM issues with TutrleCoind, right around block 508000+ yesterday it started consuming RAM until it had allocated ALL system RAM and the system went unresponsive Out Of Memory. 

I left it over night and it stabilized though those blocks and resumed normal RAM usage. But while scanning blocks with simplewallet, TurtleCoind RAM use sky rocketed and simplewallet could not progress past block 508538.

**Comment by bx549** [comment]
I have the same memory issues as plscks. TurtleCoind is consuming all RAM. This morning my machine was paging out and TurtleCoind was 29G virtual size.

I am running v0.5.0.1260 on debian 9.

**Comment by bobbieltd** [comment]
I have two servers with Turtlecoind running OK but two others keeps get killed.
Ubuntu 16.04 x64, (tested on servers from 2Gb RAM to 6Gb RAM, tried to increase memory but still get killed), here is screenshot for server 6Gb RAM + 6 Gb swap, command line : TurtleCoind without any parameters, (tried both with old version TurtleCoind and the latest version TurtleCoind, repeating running keep get killed with memory leak in some minutes very quickly , no chance of overcoming the issue) : 
![turtlecoindaemonkilled](https://user-images.githubusercontent.com/29669374/40994640-f5d678aa-6926-11e8-9af0-9841d7eb4940.png)

**Comment by thinkpol2** [comment]
@bobbieltd What is different between the machines that work and those that don't? Both Ubuntu?

**Comment by IgnacioLPM** [comment]
I have the same issue on Mac OS 10.13.5 with 16GB Ram...

**Comment by theassyrian** [comment]
Here is log from win

2018/06/05-17:19:52.153131 cdc RocksDB version: 4.11.2
2018/06/05-17:19:52.153131 cdc Git sha rocksdb_build_git_sha:0
2018/06/05-17:19:52.153131 cdc Compile date Apr  1 2018
2018/06/05-17:19:52.153131 cdc DB SUMMARY
2018/06/05-17:19:52.168731 cdc CURRENT file:  CURRENT
2018/06/05-17:19:52.168731 cdc IDENTITY file:  IDENTITY
2018/06/05-17:19:52.168731 cdc MANIFEST file:  MANIFEST-002516 size: 51244 Bytes
2018/06/05-17:19:52.168731 cdc SST files in C:\Users\root\AppData\Roaming/TurtleCoin/DB dir, Total Num: 409, files: 000290.sst 000291.sst 000292.sst 000293.sst 000294.sst 000296.sst 000297.sst 000688.sst 000768.sst 
2018/06/05-17:19:52.168731 cdc Write Ahead Log file in C:\Users\root\AppData\Roaming/TurtleCoin/DB: 002517.log size: 0 ; 
2018/06/05-17:19:52.168731 cdc          Options.error_if_exists: 0
2018/06/05-17:19:52.168731 cdc        Options.create_if_missing: 0
2018/06/05-17:19:52.168731 cdc          Options.paranoid_checks: 1
2018/06/05-17:19:52.168731 cdc                      Options.env: 00000000029331A0
2018/06/05-17:19:52.168731 cdc                 Options.info_log: 0000000000C83580
2018/06/05-17:19:52.168731 cdc           Options.max_open_files: 100
2018/06/05-17:19:52.168731 cdc Options.max_file_opening_threads: 16
2018/06/05-17:19:52.168731 cdc       Options.max_total_wal_size: 0
2018/06/05-17:19:52.168731 cdc        Options.disableDataSync: 0
2018/06/05-17:19:52.168731 cdc              Options.use_fsync: 0
2018/06/05-17:19:52.168731 cdc      Options.max_log_file_size: 0
2018/06/05-17:19:52.168731 cdc Options.max_manifest_file_size: 18446744073709551615
2018/06/05-17:19:52.168731 cdc      Options.log_file_time_to_roll: 0
2018/06/05-17:19:52.168731 cdc      Options.keep_log_file_num: 1000
2018/06/05-17:19:52.168731 cdc   Options.recycle_log_file_num: 0
2018/06/05-17:19:52.168731 cdc        Options.allow_os_buffer: 1
2018/06/05-17:19:52.168731 cdc       Options.allow_mmap_reads: 0
2018/06/05-17:19:52.168731 cdc       Options.allow_fallocate: 1
2018/06/05-17:19:52.168731 cdc      Options.allow_mmap_writes: 0
2018/06/05-17:19:52.168731 cdc          Options.create_missing_column_families: 0
2018/06/05-17:19:52.168731 cdc                              Options.db_log_dir: 
2018/06/05-17:19:52.168731 cdc                                 Options.wal_dir: C:\Users\root\AppData\Roaming/TurtleCoin/DB
2018/06/05-17:19:52.168731 cdc                Options.table_cache_numshardbits: 6
2018/06/05-17:19:52.168731 cdc     Options.delete_obsolete_files_period_micros: 21600000000
2018/06/05-17:19:52.168731 cdc              Options.base_background_compactions: 1
2018/06/05-17:19:52.168731 cdc              Options.max_background_compactions: 1
2018/06/05-17:19:52.168731 cdc                      Options.max_subcompactions: 1
2018/06/05-17:19:52.168731 cdc                  Options.max_background_flushes: 1
2018/06/05-17:19:52.168731 cdc                         Options.WAL_ttl_seconds: 0
2018/06/05-17:19:52.168731 cdc                       Options.WAL_size_limit_MB: 0
2018/06/05-17:19:52.168731 cdc             Options.manifest_preallocation_size: 4194304
2018/06/05-17:19:52.168731 cdc                          Options.allow_os_buffer: 1
2018/06/05-17:19:52.168731 cdc                         Options.allow_mmap_reads: 0
2018/06/05-17:19:52.168731 cdc                        Options.allow_mmap_writes: 0
2018/06/05-17:19:52.168731 cdc                      Options.is_fd_close_on_exec: 1
2018/06/05-17:19:52.168731 cdc                    Options.stats_dump_period_sec: 600
2018/06/05-17:19:52.168731 cdc                    Options.advise_random_on_open: 1
2018/06/05-17:19:52.168731 cdc                     Options.db_write_buffer_size: 0d
2018/06/05-17:19:52.168731 cdc          Options.access_hint_on_compaction_start: NORMAL
2018/06/05-17:19:52.168731 cdc   Options.new_table_reader_for_compaction_inputs: 0
2018/06/05-17:19:52.168731 cdc                Options.compaction_readahead_size: 0d
2018/06/05-17:19:52.168731 cdc                Options.random_access_max_buffer_size: 1048576d
2018/06/05-17:19:52.168731 cdc               Options.writable_file_max_buffer_size: 1048576d
2018/06/05-17:19:52.168731 cdc                       Options.use_adaptive_mutex: 0
2018/06/05-17:19:52.168731 cdc                             Options.rate_limiter: 0000000000000000
2018/06/05-17:19:52.168731 cdc      Options.sst_file_manager.rate_bytes_per_sec: 0
2018/06/05-17:19:52.168731 cdc                           Options.bytes_per_sync: 0
2018/06/05-17:19:52.168731 cdc                       Options.wal_bytes_per_sync: 0
2018/06/05-17:19:52.168731 cdc                        Options.wal_recovery_mode: 2
2018/06/05-17:19:52.168731 cdc                   Options.enable_thread_tracking: 0
2018/06/05-17:19:52.168731 cdc          Options.allow_concurrent_memtable_write: 0
2018/06/05-17:19:52.168731 cdc       Options.enable_write_thread_adaptive_yield: 0
2018/06/05-17:19:52.168731 cdc              Options.write_thread_max_yield_usec: 100
2018/06/05-17:19:52.168731 cdc             Options.write_thread_slow_yield_usec: 3
2018/06/05-17:19:52.168731 cdc                                Options.row_cache: None
2018/06/05-17:19:52.168731 cdc        Options.wal_filter: None
2018/06/05-17:19:52.168731 cdc                     Options.avoid_flush_during_recovery: 0
2018/06/05-17:19:52.168731 cdc               Options.comparator: rocksdb.InternalKeyComparator:leveldb.BytewiseComparator
2018/06/05-17:19:52.168731 cdc           Options.merge_operator: None
2018/06/05-17:19:52.168731 cdc        Options.compaction_filter: None
2018/06/05-17:19:52.168731 cdc        Options.compaction_filter_factory: None
2018/06/05-17:19:52.168731 cdc         Options.memtable_factory: SkipListFactory
2018/06/05-17:19:52.168731 cdc            Options.table_factory: BlockBasedTable
2018/06/05-17:19:52.168731 cdc            table_factory options:   flush_block_policy_factory: FlushBlockBySizePolicyFactory (000000000292CD00)
  cache_index_and_filter_blocks: 0
  pin_l0_filter_and_index_blocks_in_cache: 0
  index_type: 0
  hash_index_allow_collision: 1
  checksum: 1
  no_block_cache: 0
  block_cache: 0000000002934FB0
  block_cache_size: 134217728
  block_cache_compressed: 0000000000000000
  block_size: 4096
  block_size_deviation: 10
  block_restart_interval: 16
  index_block_restart_interval: 1
  filter_policy: nullptr
  whole_key_filtering: 1
  skip_table_builder_flush: 0
  format_version: 2
2018/06/05-17:19:52.168731 cdc        Options.write_buffer_size: 134217728
2018/06/05-17:19:52.168731 cdc  Options.max_write_buffer_number: 6
2018/06/05-17:19:52.168731 cdc        Options.compression[0]: NoCompression
2018/06/05-17:19:52.168731 cdc        Options.compression[1]: NoCompression
2018/06/05-17:19:52.168731 cdc        Options.compression[2]: NoCompression
2018/06/05-17:19:52.168731 cdc        Options.compression[3]: NoCompression
2018/06/05-17:19:52.168731 cdc        Options.compression[4]: NoCompression
2018/06/05-17:19:52.168731 cdc        Options.compression[5]: NoCompression
2018/06/05-17:19:52.168731 cdc        Options.compression[6]: NoCompression
2018/06/05-17:19:52.168731 cdc        Options.compression[7]: NoCompression
2018/06/05-17:19:52.168731 cdc        Options.compression[8]: NoCompression
2018/06/05-17:19:52.168731 cdc        Options.compression[9]: NoCompression
2018/06/05-17:19:52.168731 cdc                  Options.bottommost_compression: Disabled
2018/06/05-17:19:52.168731 cdc       Options.prefix_extractor: nullptr
2018/06/05-17:19:52.168731 cdc             Options.num_levels: 10
2018/06/05-17:19:52.168731 cdc        Options.min_write_buffer_number_to_merge: 2
2018/06/05-17:19:52.168731 cdc     Options.max_write_buffer_number_to_maintain: 0
2018/06/05-17:19:52.168731 cdc            Options.compression_opts.window_bits: -14
2018/06/05-17:19:52.168731 cdc                  Options.compression_opts.level: -1
2018/06/05-17:19:52.168731 cdc               Options.compression_opts.strategy: 0
2018/06/05-17:19:52.168731 cdc         Options.compression_opts.max_dict_bytes: 0
2018/06/05-17:19:52.168731 cdc      Options.level0_file_num_compaction_trigger: 20
2018/06/05-17:19:52.168731 cdc          Options.level0_slowdown_writes_trigger: 30
2018/06/05-17:19:52.168731 cdc              Options.level0_stop_writes_trigger: 40
2018/06/05-17:19:52.168731 cdc                   Options.target_file_size_base: 13421772
2018/06/05-17:19:52.168731 cdc             Options.target_file_size_multiplier: 2
2018/06/05-17:19:52.168731 cdc                Options.max_bytes_for_level_base: 134217728
2018/06/05-17:19:52.168731 cdc Options.level_compaction_dynamic_level_bytes: 0
2018/06/05-17:19:52.168731 cdc          Options.max_bytes_for_level_multiplier: 10
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[0]: 1
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[1]: 1
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[2]: 1
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[3]: 1
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[4]: 1
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[5]: 1
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[6]: 1
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[7]: 1
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[8]: 1
2018/06/05-17:19:52.168731 cdc Options.max_bytes_for_level_multiplier_addtl[9]: 1
2018/06/05-17:19:52.168731 cdc       Options.max_sequential_skip_in_iterations: 8
2018/06/05-17:19:52.168731 cdc              Options.expanded_compaction_factor: 25
2018/06/05-17:19:52.168731 cdc                Options.source_compaction_factor: 1
2018/06/05-17:19:52.168731 cdc          Options.max_grandparent_overlap_factor: 10
2018/06/05-17:19:52.168731 cdc                        Options.arena_block_size: 16777216
2018/06/05-17:19:52.168731 cdc   Options.soft_pending_compaction_bytes_limit: 68719476736
2018/06/05-17:19:52.168731 cdc   Options.hard_pending_compaction_bytes_limit: 274877906944
2018/06/05-17:19:52.168731 cdc       Options.rate_limit_delay_max_milliseconds: 1000
2018/06/05-17:19:52.168731 cdc                Options.disable_auto_compactions: 0
2018/06/05-17:19:52.168731 cdc           Options.verify_checksums_in_compaction: 1
2018/06/05-17:19:52.168731 cdc                         Options.compaction_style: 0
2018/06/05-17:19:52.168731 cdc                           Options.compaction_pri: 0
2018/06/05-17:19:52.168731 cdc  Options.compaction_options_universal.size_ratio: 1
2018/06/05-17:19:52.168731 cdc Options.compaction_options_universal.min_merge_width: 2
2018/06/05-17:19:52.168731 cdc Options.compaction_options_universal.max_merge_width: 4294967295
2018/06/05-17:19:52.168731 cdc Options.compaction_options_universal.max_size_amplification_percent: 200
2018/06/05-17:19:52.168731 cdc Options.compaction_options_universal.compression_size_percent: -1
2018/06/05-17:19:52.168731 cdc Options.compaction_options_fifo.max_table_files_size: 1073741824
2018/06/05-17:19:52.168731 cdc                   Options.table_properties_collectors: 
2018/06/05-17:19:52.168731 cdc                   Options.inplace_update_support: 0
2018/06/05-17:19:52.168731 cdc                 Options.inplace_update_num_locks: 10000
2018/06/05-17:19:52.168731 cdc               Options.min_partial_merge_operands: 2
2018/06/05-17:19:52.168731 cdc               Options.memtable_prefix_bloom_size_ratio: 0.000000
2018/06/05-17:19:52.168731 cdc   Options.memtable_huge_page_size: 0
2018/06/05-17:19:52.168731 cdc                           Options.bloom_locality: 0
2018/06/05-17:19:52.168731 cdc                    Options.max_successive_merges: 0
2018/06/05-17:19:52.168731 cdc                Options.optimize_filters_for_hits: 0
2018/06/05-17:19:52.168731 cdc                Options.paranoid_file_checks: 0
2018/06/05-17:19:52.168731 cdc                Options.report_bg_io_stats: 0

**Comment by cryptonote-social** [comment]
Same issues here on Ubuntu 16.04 LTS.... Both daemon and simplewallet eating a shit-ton of RAM.  Finally got the daemon up and running again but still can't get my wallet to sync with it.

**Comment by gageshort** [comment]
I have the same issue with the most recent versions of simplewallet and nest on Mac OSX 10.13.4

**Comment by crashpower** [comment]
i have same issue 
![turtle](https://user-images.githubusercontent.com/38284320/41027309-e2b456be-69a0-11e8-8791-87f21598f5a7.jpg)

**Comment by bobbieltd** [comment]
@thinkpol2 All are Ubuntu 16.04 x64. If you want a DIFFERENCE to trace the issue, it is the location. Servers are based on different country. I guess it is luck that OK daemons did not eat bad data from bad peers.
@fexra You are on the right path to debug it but I'm dumb with logs / coding. There is some shit data in blockchain of killed daemons + memory bug in daemon codes. C++ is very slow and hard to debug, memory leak is even harder to trace.

Temporary solution : Downloading blockchain from OK daemons. If devs update latest blockchain, you can bootstrap from this guide https://github.com/turtlecoin/turtlecoin/wiki/Bootstrapping-the-Blockchain
If blockchain is too old (less than 51xxxx), go to Discord and ask them for new one. For my part, I copied blockchain data from my OK daemons to killed daemons and it works.

**Comment by brandonlehmann** [comment]
@bobbieltd It appears that you can also get around it by using full checkpoints if necessary you can find the latest from today at https://github.com/brandonlehmann/checkpoints/raw/201806061533/checkpoints.csv

Also note, that @ZedPea  is currently testing a patch to *hopefully* resolve this with a little more grace.

**Comment by bobbieltd** [comment]
@brandonlehmann Thanks. I learn a new thing. 
TurtleCoind --load-checkpoints https://github.com/brandonlehmann/checkpoints/raw/201806061533/checkpoints.csv

**Comment by ZedPea** [comment]
You can try out this patch if you want, hopefully it works, it has worked for me in my tests: https://github.com/turtlecoin/turtlecoin/pull/266

`git clone https://github.com/ZedPea/turtlecoin.git`
`cd turtlecoin`
`git checkout fix-memory-leak`
`mkdir build && cd build && cmake .. && make`

I'm not sure if resyncing the bad blocks is needed to prevent leaks, or if you get past them you are fine...

**Comment by bobbieltd** [comment]
@ZedPea Incroyable ! Fast & Furious ! You fixed it (this kind of leak bug often takes days to trace ).
I test it on killed bugged daemon, no more memory leaks, no need to resync, it returned back to normal.
Issue solved now.

![turtlecoindaemonfixed](https://user-images.githubusercontent.com/29669374/41071478-2068a2a4-6a22-11e8-8e75-e5ec83702c3d.png)

**Comment by ZedPea** [comment]
Great! Thanks for testing it out.

**Comment by plscks** [comment]
@ZedPea I tested your patch also with my old broken copy of the blockchain, it moved right past those problem block with no issues, thanks!

**Comment by bx549** [comment]
I checked out the patch. I'm starting Turtlecoind and building from block zero with the checkpoints provided by brandonlehman.

**Comment by crashpower** [comment]
Great ... my problem  solved  now my pool run again, thx dev

**Comment by fexra** [comment]
Great work @ZedPea - you're truly a wizard :boom:

**Comment by theassyrian** [comment]
Thanks Zed ! 
Should can we use this for our production wallet ?

**Comment by ZedPea** [comment]
@theassyrian I would suggest building from master, this patch added a slight bug causing wallets to have to resync upon relaunching, and that has been since fixed. If you want binaries, we're in the process or making a release now :)

**Comment by theassyrian** [comment]
Thanks Zed Ill do it for windows than

**Comment by theassyrian** [comment]
Nice work brother !
