### ISSUE TITLE
Ensure the core builds cleanly

### ISSUE THREAD

**Issue by paulie-g** [turtlecoin/turtlecoin#28]
The reason source code is provided for all these coin projects is that it is meaningless to have a distributed consensus ledger with a closed source implementation - it loses the verifiability property. Now, very few users are actually capable of auditing the implementation or have the time to do so. However, providing a copy of the source that builds and can be used instead of the binary releases published by the project is a very important circumstantial indicator that the implementation isn't doing anything that isn't cricket.

I attempted to build the master today on an up to date Arch system and ran into a multitude of issues, see #25 #26 #27. While I am capable of both fixing them, at least locally, and understanding that they are oversights/bugs/results of having a small dev team/whatever rather than malfeasance, someone else may well take the absence of a functional source tree that builds without surgery as a negative sign. This would be unfortunate, since the devs have gone to great lengths to do things "right" (as they define "right" anyway), eg by not doing a premine. The issues are small and easily fixable and it is worth doing so they don't undermine trust in the implementation of the coin.

I would suggest adding this issue to a milestone, say 0.4, and slowly working towards it. It may not be as sexy as adding new features, but I would argue it is nevertheless quite important.

**Comment by SoreGums** [comment]
Builds have been working fine for a while now - will close if no response received in 24hrs
