### ISSUE TITLE
CoinGecko listing has wrong info about blockchain

### ISSUE THREAD

**Issue by mysticaltech** [turtlecoin/turtlecoin#283]
Here https://www.coingecko.com/en/price_charts/turtlecoin/usd, it is mentioned:

`Blockchain/Supply   https://turtle-coin.com/`

This is not correct yes? If someone here are in contact with them, would be great to rectify the info.

**Comment by fexra** [comment]
Don't see a problem with it. The link redirects too http://blocks.turtle.link/ which is a block explorer and states the total supply, emission, difficulty and hash rate. If you believe you have a better link, contact them.

**Comment by fexra** [comment]
@close0ne I see now. I told tom about it :+1:

**Comment by close0ne** [comment]
You can told tham about...https://turtle.land/...

Just kidding :) :D

**Comment by fexra** [comment]
@close0ne I like what you're doing with turtle.land a lot. Looking good! I have no problem with it if you contact coingecko and tell them about your explorer, but hey who am I :+1:

**Comment by mysticaltech** [comment]
Thanks Guys. We need the official one there! http://blocks.turtle.link/

**Comment by fexra** [comment]
Hey @mysticaltech we don't have any official block explorer. blocks.turtle.link is ran by Tom and has been one of the first to be online, but is not the official in any way or form :)

**Comment by mysticaltech** [comment]
Ok great, so any would be fine then! Anyone is charge of updating coingecko.com with the right data?

**Comment by Tom7003** [comment]
I updated the redirect on my site so http://blocks.turtle.link goes to https://blocks.turtle.link correctly now. CoinGecko should use http://explorer.turtlecoin.lol as that is the main URL under control of the project for the block explorer.

**Comment by mysticaltech** [comment]
@Tom7003 Thanks for the info, that’s great
