### ISSUE TITLE
OSX high sierra gets stuck at block 508465 sync

### ISSUE THREAD

**Issue by BigslimVdub** [turtlecoin/turtlecoin#284]
using 0.5.0 simple wallet gets stuck on sync on this block
![screen shot 2018-06-11 at 5 20 39 pm](https://user-images.githubusercontent.com/30030687/41260223-234a87bc-6d9c-11e8-9ee2-5876357885a3.png)

**Comment by BigslimVdub** [comment]
Yea I can build on cmake. I will try when I get a chance.

**Comment by MaxwellJK** [comment]
Thanks, been able to go over block 508k. For the record, I built the master on a mac.
