### ISSUE TITLE
Walletd In-Process Node Hangs on sendTransaction

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#286]
@woodyjon and I tested this a bunch today. This issue occurs back to v0.5.0 and possibly earlier.

When running walletd with the --local option (in-process node) and then sending a transaction via the RPC once fully synced, walletd hangs and appears to deadlock.

Jon was able to trace it as best as possible to https://github.com/turtlecoin/turtlecoin/blob/7af7f150977f947d3704e5e6b06316d8a8f441ca/src/InProcessNode/InProcessNode.cpp#L533 and I can confirm that's where it appears to hang up. This does *not* occur when using a remote node with walletd.

I think we can get this resolved pretty quickly if we spin up the RpcServer for the daemon in conjunction with the InProcessNode and then use the NodeRpcProxy to connect to the in-process node.

Thoughts? Or would someone like to go down this rabbit hole and try to hammer this bad boy out?

**Comment by woodyjon** [comment]
Easy to reproduce: launch walletd in local:

`./walletd -w yourwallet.wallet -p test1 --local --rpc-password test`

in another terminal window, run:

`curl -d '{"jsonrpc":"2.0","method":"sendTransaction","params":{"anonymity":5,"fee":10,"paymentId":"","transfers":[{"address":"TRTLuyTmC1mdSPXcyvxWL2H9e8cjvnLbi8oJUkamvUf4iY3tPNL2PGFhnzhtDx97D6KkdmVryh9DwDvQu3Q5DT9qhZBB7gAWSz7","amount":100}]},"password":"test","id":0}' http://localhost:8070/json_rpc`
(change the address to one of yours)

@SoreGums "good first issue", I don't think so ;-) But if a noob fixes it, respect!
