### ISSUE TITLE
Mixin vs ring size

### ISSUE THREAD

**Issue by woodyjon** [turtlecoin/turtlecoin#287]
I believe that in the code, proper semantic must be used between mixin and ring size to avoid problems, confusions and future potential bugs.

We already saw the problem with (https://github.com/turtlecoin/turtlecoin/issues/274)
```
uint64_t maxMixin = std::numeric_limits<uint64_t>::max()
maxMixin++;
```

But also here https://github.com/turtlecoin/turtlecoin/blob/7af7f150977f947d3704e5e6b06316d8a8f441ca/src/CryptoNoteCore/Core.cpp#L1029 , we did `maxMixin++;` to account for the fact that we are considering ring size, then we print maxMixin to the user, forgetting that we did `maxMixin++;`.

I believe there could be other problems because of this.

I propose to use mixin and ringSize. Mixin being the number of other outputs we want to be mixed with, ringSize being the total number of outputs in the ring signatures (ringSize = mixin + 1). Ref: https://getmonero.org/resources/moneropedia/ring-size.html

**Comment by ZedPea** [comment]
Great idea, there are a few things like this in the code base which are a bit confusing.

**Comment by ZedPea** [comment]
https://github.com/turtlecoin/turtlecoin/pull/288 Addresses it, i'm sure there's other places where it's used but I don't really want to go poking around in those deep parts of the codebase.
