### ISSUE TITLE
Simplewallet -> zedwallet

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/turtlecoin#300]
./src/Simplewallet should be ./src/Zedwallet

Zedwallet shouldn't ask for mixin anymore when given `transfer` command, and should ignore mixin field in the `transfer [mix] [address] [amount]` syntax

**Comment by ZedPea** [comment]
This is already done. `transfer mixin address amount` syntax was removed.

**Comment by ZedPea** [comment]
https://github.com/turtlecoin/turtlecoin/pull/301
