### ISSUE TITLE
http://ppa.launchpad.net/ethcore/ethcore/ubuntu xenial Release'

### ISSUE THREAD

**Issue by Stardock2018** [turtlecoin/turtlecoin#324]
W: The repository 'http://ppa.launchpad.net/ethcore/ethcore/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/ethcore/ethcore/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by brandonlehmann** [comment]
I don't think I ever even followed that dependency listing. Can someone else confirm its actually required?

**Comment by RocksteadyTC** [comment]
it is not required
