### ISSUE TITLE
Ubuntu Compile Error

### ISSUE THREAD

**Issue by swanseahost** [turtlecoin/turtlecoin#335]
miner@poolserver:~/daemons/turtlecoin/build$ cmake ..
-- BUILD TESTS: enabled
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Readline (missing: Readline_INCLUDE_DIR Readline_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindReadline.cmake:26 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:65 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by ZedPea** [comment]
Install `libreadline-dev` (assuming ubuntu) or run cmake as follows: `cmake .. -DFORCE_READLINE=FALSE`

**Comment by swanseahost** [comment]
You sir are a genius! Thanks
