### ISSUE TITLE
v0.6.3.1263 binaries turtleD shows "use turtlecoinD and Simplewallet" not "Zedwallet"

### ISSUE THREAD

**Issue by BigslimVdub** [turtlecoin/turtlecoin#338]
After TurtlecoinD makes connection to the network it displays the help message that reads to use "simplewallet".  v0.6.3 uses "zedwallet"
![simplewallet not zedwaller](https://user-images.githubusercontent.com/30030687/42405745-da023630-8160-11e8-98dc-8ae5f556a49d.png)

**Comment by RocksteadyTC** [comment]
I believe this has been changed already and is pending release in 0.6.4
