### ISSUE TITLE
TurtlecoinD fails to "catch up" unsynced blocks when running --data-dir=D:/turtlecoin

### ISSUE THREAD

**Issue by BigslimVdub** [turtlecoin/turtlecoin#339]
TurtleD does recognize and load the blockchain but fails to start sync of the missing blocks from a few days since sync. It DOES sync new blocks as they are found but does not catch up an older sync. 
Windows 10
Database was loaded from another windows 10 machine to an external HDD. That HDD is the datadir path for the turtlecoinD
![screen_shot_2018-07-06_at_8 58 13_pm](https://user-images.githubusercontent.com/30030687/42405788-c4c791ce-8161-11e8-9906-90e1b18ffce1.png)

**Comment by RocksteadyTC** [comment]
Is it able to sync a fresh chain on a remote directory using checkpoints?

**Comment by BigslimVdub** [comment]
I changed directory to just D:/ and it starts to sync just fine sync from 0

**Comment by BigslimVdub** [comment]
Yea, that worked. Its not too slow but it is now 100% and updating as needed. 
![Sync is now good](https://user-images.githubusercontent.com/30030687/42416097-3d0e8fe2-822b-11e8-9da0-252e2c0dee41.png)

@RocksteadyTC if you didn't find anything unrelated to this formatting, please close.

**Comment by RocksteadyTC** [comment]
If the filesystem type were the issue, I'd have to say it'd be the first time. I've used this software on quite a number of them. It's not outside the real of possibilities but I appreciate your efforts in narrowing down what possibly could be the cause. 

Here's a guess, I'm curious if the peer ID for the two computers has anything to do with this.

**Comment by BigslimVdub** [comment]
I have had issues using exfat/fat32 and larger than 4gb files. The blocks.bin is 5.7gb? Or so. Possibly there is an issue there. The first try after formatting and loading the db files it synced fine. I will let it get behind a day and retry and see if it still syncs fine. Computers are on the same network so unsure why I would have a different peer id.

**Comment by RocksteadyTC** [comment]
Ah, you know what, that's something I didn't think of, large files would be a problem.

**Comment by BigslimVdub** [comment]
When running this now on internal drive (using sata port on motherboard not running external drive on usb) I get 0 in connections.  While running this via external usb to hdd I would get 10-15 in connections. While running right off C: drive I would get 40-50 in connections.

**Comment by BigslimVdub** [comment]
Now since the fork I can barely get a few out connections and now they drop.
![shutdown crash](https://user-images.githubusercontent.com/30030687/42736818-13f39406-8832-11e8-991f-7c3b042a85c8.png)

And when I try to exit, turtleD crashes
![dropping connections](https://user-images.githubusercontent.com/30030687/42736803-ab3fe5d6-8831-11e8-9bb0-868d6a5a8fde.png)

**Comment by brandonlehmann** [comment]
@BigslimVdub have you noticed any improvement?

**Comment by BigslimVdub** [comment]
Is there an updated daemon? I last ran Monday night and still had zero in connections.

**Comment by brandonlehmann** [comment]
Not after 0.6.3 yet but hopefully more have updated for the fork that was included.

**Comment by BigslimVdub** [comment]
Unsure how that would be since I have 3 other daemon running with zero issues and multiple in connections on the identical drive and dB location.

**Comment by brandonlehmann** [comment]
This isn't a software issue. This is a deployment issue for a single user.

**Comment by brandonlehmann** [comment]
@BigslimVdub 

Take a look at https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits or http://www.ntfs.com/ntfs_vs_fat.htm

FAT32 has a maximum filesize of 4GB. Stop trying to put the files on there.
exFAT has a limit of 16EB, which should work but who uses that?
NTFS goes to 16TB

Stop using file systems that don't support file sizes the software needs to operate.

@RocksteadyTC  please close this, again.
