### ISSUE TITLE
Periodic segfault of TurtleCoind

### ISSUE THREAD

**Issue by dprestegard** [turtlecoin/turtlecoin#340]
Every few days my TurtleCoind 0.6.3 segfaults on Ubuntu 16.04.

LMK if there's any debugging information I can provide.

**Comment by System96** [comment]
Can you provide any log files or anything of the sort? If memory serves me right the daemon/wallet logging info is held in the same folder as the blockchain but

**Comment by dprestegard** [comment]
I'd be happy to, there's a log file in the same directory as TurtleCoind but it doesn't appear to show anything useful, and I don't see anything in the folder as the blockchain.

If there's a debug mode I can run the node in I'd be happy to do that. LMK what I can do to help! :)

**Comment by dprestegard** [comment]
This is definitely still happening every few days.

Can I turn up log verbosity or something?

**Comment by brandonlehmann** [comment]
Try running with ```--log-level 4```

**Comment by System96** [comment]
If you can, tell us what it says when it segfaults with --log-level 4

**Comment by brandonlehmann** [comment]
@dprestegard Any updates on providing the update log files?

**Comment by dprestegard** [comment]
Sorry guys, I ended up nuking my crypto VM and don't plan to rebuild turtlecoin hosting on it due to the enormous size of the block chain :)

GL!
