### ISSUE TITLE
UNnable to open wallet on MAC (GUI)

### ISSUE THREAD

**Issue by fireheadman** [turtlecoin/turtlecoin#342]
fresh download... GUI from here for macOS
I used the wallet generator online (https://turtlecoin.lol/wallet/)

When attempting to open my wallet that was generated I get this error:

![image](https://user-images.githubusercontent.com/19847195/42422139-00f40b54-829e-11e8-8483-00fcde4a5a43.png)

I've tried using Seed, from private keys... even tried creating a new wallet.... all result in the same error.
I am on macOS 10.13.5

![image](https://user-images.githubusercontent.com/19847195/42422145-2ca52c74-829e-11e8-8210-0a6da358c3bf.png)

Unsure if I am missing a step?
I have been successfully mining to my generated wallet address and can see it on the pool.

**Comment by BigslimVdub** [comment]
Are on the correct public node? 
Have you tried installing turtleD on another computer and running remote IP address to that computers local IP 192.168.1.x ?

I have no issues with this on OS X high Sierra and gui wallet.

**Comment by brandonlehmann** [comment]
@fireheadman Are you running the latest version of Nest? https://github.com/turtlecoin/turtle-wallet-go/releases/tag/0.30

**Comment by fireheadman** [comment]
I wanted to apologize in advance.... I lost interest in mining this coin. so if I was the only person having this issue this thread could be closed

**Comment by RocksteadyTC** [comment]
@fireheadman I understand, if you come back I hope we can serve you better next time. Take care

**Comment by BigslimVdub** [comment]
Figured out this one. Had the same issue with the default node in Nest so...

I chose a Public node based off [THIS](https://turtlenode.io) website and all is well. Issue fixed.

**Comment by brandonlehmann** [comment]
Excellent. I run those public nodes and with the influx of new users I wasn't expecting the loads a bit higher than *normal*. I'll get them boosted in the coming days.
