### ISSUE TITLE
Daemon stuck on block 518683 on Linux

### ISSUE THREAD

**Issue by auto-joe** [turtlecoin/turtlecoin#345]
I tried syncing for the first time in a while, and my daemon got stuck after 500k. I deleted everything under ~/.Turtlecoin and retried twice with checkpoints. Both times it got stuck on block 518683. 
With debug on I see `Exception in connectionHandler: SwappedVector::push_back`
I’m on discord if I can help debug

This is with 0.6.3 compiled from source

**Comment by brandonlehmann** [comment]
Try restarting the daemon a few times. We had some very large transactions with lots in the extra field back around that time. Typically, restarting a few times would allow the node to work through the blocks.

**Comment by jgrabenstein** [comment]
Sorry but this is a different issue. That was way back around 437k-440k block height. This is NOT a crash. The daemon sits there running and gets further and further behind, never getting past block 518683.
This is with the latest code (0.6.3.1263) and updates on Ubuntu 16.04

**Comment by auto-joe** [comment]
Sorry but this is a different issue. That was way back around 437k-440k block height. This is NOT a crash. The daemon sits there running and gets further and further behind, never getting past block 518683.
This is with the latest code (0.6.3.1263) and updates on Ubuntu 16.04

**Comment by brandonlehmann** [comment]
Are you syncing with checkpoints or no? It seems to me that around 510-530k or so is when we saw the oversized extra information in the transactions. The best way to power through them is to make sure you have tons of ram available in your system or use checkpoints. If necessary, you may also want to add a priority peer using a known good peer.

**Comment by auto-joe** [comment]
The first time was without checkpoints. The next 2 times were with checkpoints after starting over. 
It’s a quad core/4gb ram machine running nothing else when I do this. It just sits there for hours on the same exact block.

**Comment by brandonlehmann** [comment]
Try launching with ```--add-priority-node 165.227.252.132:11897```

**Comment by auto-joe** [comment]
tried that, this is all i get (same behavior):
```2018-Jul-24 19:32:51.197866 INFO    [185.134.22.3:11897 OUT] Your TurtleCoin node is syncing with the network. You are 131245 blocks (45 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:32:58.383772 INFO    [142.44.242.106:11897 OUT] Your TurtleCoin node is syncing with the network. You are 131245 blocks (45 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:33:08.933629 INFO    [207.180.192.55:11897 OUT] Your TurtleCoin node is syncing with the network. You are 101398 blocks (35 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:33:19.783810 INFO    [62.210.169.191:11897 OUT] Your TurtleCoin node is syncing with the network. You are 131245 blocks (45 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:33:57.524260 INFO    [142.44.242.106:11897 OUT] Your TurtleCoin node is syncing with the network. You are 131246 blocks (45 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:33:57.524721 INFO    New Top Block Detected: 649929
2018-Jul-24 19:34:28.597905 INFO    [207.180.192.55:11897 OUT] Your TurtleCoin node is syncing with the network. You are 101398 blocks (35 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:34:36.192134 INFO    [142.44.242.106:11897 OUT] Your TurtleCoin node is syncing with the network. You are 131248 blocks (45 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:34:36.192592 INFO    New Top Block Detected: 649931
2018-Jul-24 19:34:47.439313 INFO    [192.121.108.70:51312 OUT] Your TurtleCoin node is syncing with the network. You are 131248 blocks (45 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:34:58.707751 INFO    [185.134.22.3:11897 OUT] Your TurtleCoin node is syncing with the network. You are 131248 blocks (45 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:35:03.827037 INFO    New Top Block Detected: 649932
2018-Jul-24 19:35:09.157793 INFO    [94.177.190.223:11897 OUT] Your TurtleCoin node is syncing with the network. You are 131249 blocks (45 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:35:16.615164 INFO    [142.44.242.106:11897 OUT] Your TurtleCoin node is syncing with the network. You are 131249 blocks (45 days) behind the Hare. Slow and steady wins the race! 
2018-Jul-24 19:35:27.174545 INFO    [192.121.108.70:51312 OUT] Your TurtleCoin node is syncing with the network. You are 131249 blocks (45 days) behind the Hare. Slow and steady wins the race! ```

**Comment by brandonlehmann** [comment]
Try

```--add-priority-node 165.227.252.132:11897 --hide-my-port```

**Comment by auto-joe** [comment]
Same :(

**Comment by xlp0rk0lx** [comment]
You can have a try using the checkpoint. I'm currently syncing with them and the checkpoint is passed.

![image](https://user-images.githubusercontent.com/30440412/43422495-28debf34-944a-11e8-836e-24978fd48d4d.png)

https://github.com/turtlecoin/checkpoints/raw/master/checkpoints.csv.tar.gz

This is the official link of the current  checkpoint.

You can import by running your daemon with the ./TurtleCoind --load-checkpoints checkpoints.csv (yes, you have to unizp)

In my opinion will be better to move the chain in another dir, and let the checkpoint do the work.

cheers

**Comment by SoreGums** [comment]
or that ^^ look into [turtlecoind-ha](https://github.com/turtlecoin/turtlecoind-ha), it is a really great wrapper for the current daemon 👍
