### ISSUE TITLE
Bug when syncing blockchain

### ISSUE THREAD

**Issue by beezTEM** [turtlecoin/turtlecoin#35]
I was recently starting my TurtleCoind (yes I know I'm really far behind) and I ran into a slight issue, it said it was synced before it was truly synced. I have been a user of TRTL for a while now but this may be confusing for new users. Please look into this!

![Says synced before synced](http://i1.tf/00Aqep.png)

Edit: Fixed the image

**Comment by BigslimVdub** [comment]
I see this as well on 3.2 when there are a few hundred blocks left to sync.

**Comment by RocksteadyTC** [comment]
This is fixed in Master
