### ISSUE TITLE
Cannot determine current (GIT) version

### ISSUE THREAD

**Issue by 2acoin** [turtlecoin/turtlecoin#377]
I know this is going to be a simple one... Something I don't have configured correctly somewhere.

When I run Make, I get the following error;
![Image of Error](https://i.imgur.com/JvJRiev.png)

I have GIT installed on the machine and I have cloned the GIT resource and can run GIT commands without any issues. What can I check to fix this error?

This error is on Ubuntu 16.04 with all pre-requisites installed and up-to-date.

**Comment by ZedPea** [comment]
I get a similar error but I don't think it's anything to worry about, the code still compiles fine :woman_shrugging: 

```
fatal: No annotated tags can describe '7e23998eb5edb24c680af0e6624680c7937fc09a'.
However, there were unannotated tags: try --tags.
[ 32%] Built target NodeRpcProxy
CMake Warning at src/version.cmake:3 (message):
  Cannot determine current revision.  Make sure that you are building either
  from a Git working tree or from a source archive.
```

Is this issue preventing you from building?

**Comment by 2acoin** [comment]
Nope, I am able to build fine... Just a little annoying that when I compile and run I see versions live v0.6.3 () instead of the expected v0.6.3 (####) or (####-dirty).

**Comment by ZedPea** [comment]
Ok, cool. I'll yield to someone with more git/make knowledge.

**Comment by 2acoin** [comment]
It looks like the issue is related to un-annotated and annotated tags. Therefore, I am testing with the inclusion of the --tags parameter in the version.cmake file;

`
execute_process(COMMAND "${GIT}" describe --tags --dirty --match "v*" RESULT_VARIABLE RET OUTPUT_VARIABLE DESCRIPTION OUTPUT_STRIP_TRAILING_WHITESPACE)
if(RET)
    message(WARNING "Cannot determine current revision. Make sure that you are building either from a Git working tree or from a source archive.")
    set(VERSION "${COMMIT}")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/src/version.h.in" "${TO}")
else()
    string(REGEX MATCH "([0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f])?(-dirty)? $" COMMIT "${DESCRIPTION} ")
    string(STRIP "${COMMIT}" COMMIT)
    set(VERSION "${COMMIT}")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/src/version.h.in" "${TO}")
endif()
`

I'll let you know how it works for me...

**Comment by SoreGums** [comment]
I started work on this and didn't finish - it annoys me as well.

If you figure it out please PR :D 
![image](https://user-images.githubusercontent.com/317/43370952-70d19796-93b2-11e8-9593-2c735f1af47b.png)
