### ISSUE TITLE
Issue building zedwallet Ubuntu

### ISSUE THREAD

**Issue by Bathmat** [turtlecoin/turtlecoin#391]
System: Ubuntu 16.04
Turtlecoin version: release binaries for v0.7.0 (`Source code (tar.gz)`)

`make zedwallet` gives error:
```
/usr/bin/ld: cannot open output file zedwallet: Is a directory
collect2: error: ld returned 1 exit status
src/CMakeFiles/zedwallet.dir/build.make:397: recipe for target 'src/zedwallet' failed
make[3]: *** [src/zedwallet] Error 1
CMakeFiles/Makefile2:992: recipe for target 'src/CMakeFiles/zedwallet.dir/all' failed
make[2]: *** [src/CMakeFiles/zedwallet.dir/all] Error 2
CMakeFiles/Makefile2:1004: recipe for target 'src/CMakeFiles/zedwallet.dir/rule' failed
make[1]: *** [src/CMakeFiles/zedwallet.dir/rule] Error 2
Makefile:446: recipe for target 'zedwallet' failed
make: *** [zedwallet] Error 2
```

`TurtleCoind` and `turtle-service` build without issues.

**Comment by ZedPea** [comment]
Did you `mkdir build; cd build` before running make?

**Comment by Bathmat** [comment]
@ZedPea yes, but using `cmake ..` and then `make` in `/build` doesn't build: 
```
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by ZedPea** [comment]
To clarify, the build directory is in the root turtlecoin folder? What files are present in the build directory after running `cmake ..` ?

**Comment by Bathmat** [comment]
Yes: `/turtlecoin-0.7.0/build$`
There are no files in `/build` after running `cmake ..`

**Comment by brandonlehmann** [comment]
```Build files have been written to: /home/bathmat/turtlecoin-0.7.0/rocksdb```

You are not in the build directory when you ran ```cmake ..```

**Comment by brandonlehmann** [comment]
Sorry, copied wrong line. message still the same

**Comment by Bathmat** [comment]
Yeah, must have ran `cmake ..` somewhere else... Oops... retrying now
