### ISSUE TITLE
Unable to run zedwallet 0.7.0 CLI on Pop OS 18.04

### ISSUE THREAD

**Issue by coreagile** [turtlecoin/turtlecoin#400]
Given:

    $ uname -a
    Linux pop-os 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

    $ cat /etc/issue
    Ubuntu 18.04.1 LTS \n \l

    $ dpkg --list | grep libreadline
    ii  libreadline-dev:amd64                            7.0-3                                   amd64        GNU readline and 
    history libraries, development files
    ii  libreadline5:amd64                               5.2+dfsg-3build1                        amd64        GNU readline 
    and history libraries, run-time libraries
    ii  libreadline7:amd64                               7.0-3                                   amd64        GNU readline and 
    history libraries, run-time libraries

When:

    $ ./zedwallet --remote-daemon public.turtlenode.io:11898

Expected:

    Something to prompt me to open a new wallet

Actual:

    ./zedwallet: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

Workaround:

    mkdir lib
    ln -s /lib/x86_64-linux-gnu/libreadline.so.7 lib/libreadline.so.6
    export LD_LIBRARY_PATH=./lib

Note:

<https://utcc.utoronto.ca/~cks/space/blog/linux/Ubuntu1804ReadlineMess>

**Comment by brandonlehmann** [comment]
Please try compiling from scratch on your system and report back the results.

**Comment by plscks** [comment]
I just tested this on a Pop OS 18.04 live USB stick, compiling from scratch allows zedwallet to function as expected.

**Comment by brandonlehmann** [comment]
@zedpea is already fixing the readline dependency for static linkage in #394

**Comment by coreagile** [comment]
Excellent!
