### ISSUE TITLE
Publish arbitrary p2p Peer IP and TCP Port

### ISSUE THREAD

**Issue by Tom7003** [turtlecoin/turtlecoin#41]
Hi,

I am running a public node service. To effectively load balance the service I want to run multiple instances of TurtleCoind behind a load balancer. 

The --p2p-bind-ip and port options attempt to bind do an address configured on the vm or container, but that address does not exist there.

Can we extend functionality to cover this use case? This will allow inbound p2p connections to work and to service the requests from other nodes on the p2p network. Outbound connections work fine.

```2018-Feb-05 23:13:49.727994 INFO    TurtleCoin v0.3.1.1252 ()
2018-Feb-05 23:13:49.728266 INFO    Module folder: /usr/local/bin/TurtleCoind
2018-Feb-05 23:13:49.728468 INFO    Opening DB in /var/lib/turtlecoind/DB
2018-Feb-05 23:13:52.140557 INFO    DB opened in /var/lib/turtlecoind/DB
2018-Feb-05 23:13:52.144635 INFO    Initializing core...
2018-Feb-05 23:13:52.158621 INFO    Importing blocks from blockchain storage
2018-Feb-05 23:13:54.374705 INFO    Imported block with index 162000 / 163298
2018-Feb-05 23:13:57.421980 INFO    Imported block with index 163000 / 163298
2018-Feb-05 23:13:57.974352 INFO    Core initialized OK
2018-Feb-05 23:13:57.974478 INFO    Initializing p2p server...
2018-Feb-05 23:13:57.976202 INFO    Binding on 30.40.50.60:11897
SwappedVector cache hits: 1, misses: 2021 (99.95%)
SwappedVector cache hits: 1, misses: 2021 (99.95%)
2018-Feb-05 23:13:57.977128 INFO    Closing DB.
2018-Feb-05 23:13:58.688591 ERROR   Exception: TcpListener::TcpListener, bind failed, result=99, Cannot assign requested address```

**Comment by brandonlehmann** [comment]
Recently discussed this on discord -- I believe this would be better suited as a separate set of options that allow for controlling the IP:port announced to the rest of the P2Pnet.

Perhaps the following:

--p2p-masq-ip
--p2p-masq-port

That way the underlying network stack bindings are unaffected.

**Comment by brandonlehmann** [comment]
Discussed further on discord... proceed with caution. This may have unforeseen side effects.

**Comment by SoreGums** [comment]
unforseen like in one packet gets block 320,001 then in the next one gets 319,989 ?

Yeah load balancing this kind of connection is not so straight forward. Sticky sessions should help on the Load Balancer. As long as the load balancer can kill these sticky sessions everything should be fine.

Then there is the whole amplification attack angle. if an operator was able to somehow co-ordinate 10+ nodes to connect to all other nodes then switch out and announce "hey everyone I've switched to this IP:port, go connect there instead" - that's not cool.

This is the whole, we can't have nice things issue that plagues Microsoft ;) (active desktop anyone?)

**Comment by brandonlehmann** [comment]
The more I’ve thought about this one, publishing an arbitrary IP or Port for P2P doesn’t solve a load balancing issue. The connections to the rest of the network don’t need load balanced. It’s the RPC calls from clients that benefit from load balancing. That being said, I’ve had a dozen+ daemons running behind load balancers without an issue for over a month.

**Comment by RocksteadyTC** [comment]
@Tom7003 Please
