### ISSUE TITLE
Release Candidate v0.8.0 Test Log

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#430]
# TurtleCoin v0.8.0 Test Log

### Project
- [x] Currently Passing Travis & AppVeyor build tests
- [x] `Version.h.in` updated to correct semver value
- [x] Release Notes Prepared (https://hackmd.io/s/Bkl_X1FVLX)

### TurtleCoind Tests
- Daemon connects to local DB
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Local DB does not require resync
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Peer ID assigned
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Connections to multiple peers are made
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Daemon able to sync with external checkpoints
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Daemon able to sync without external checkpoints
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Daemon able to sync from 0 with external checkpoints
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Daemon able to sync from 0 without external checkpoints
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
 
### ZedWallet Tests
- Connect to local daemon
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Connect to a remote daemon
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Send a transaction
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Receive a transaction
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Perform a fusion transaction
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Export keys and seeds
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Import from keys and seeds correctly
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Perform a full reset
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Integrated Addresses work
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS

### Turtle-Service Tests
- Connect to local daemon
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Connect to a remote daemon
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Send a transaction
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Receive a transaction
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Perform a fusion transaction
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Export keys and seeds
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Import from keys and seeds correctly
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Perform a full reset
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Integrated Addresses work
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- All RPC endpoints and methods are operational
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS

### GUI Wallet Testing
- Connect to local daemon
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Connect to a remote daemon
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Send a transaction
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Receive a transaction
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Perform a fusion transaction
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Export keys and seeds
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Import from keys and seeds correctly
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Perform a full reset
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS
- Integrated Addresses work
  - [x] Windows
  - [x] Ubuntu
  - [x] MacOS

**Comment by ZedPea** [comment]
:thinking:

**Comment by brandonlehmann** [comment]
Okey doke

**Comment by woodyjon** [comment]
Daemon connects to local DB
 OK MacOS

Local DB does not require resync
 OK MacOS

Peer ID assigned
OK  MacOS

Connections to multiple peers are made
OK  MacOS

Daemon able to sync without external checkpoints
OK  MacOS

**Comment by woodyjon** [comment]
Turtle-Service Tests

Connect to local daemon
OK  MacOS

Connect to a remote daemon
OK  MacOS

Send a transaction
OK  MacOS

Receive a transaction
OK  MacOS

Perform a fusion transaction
  MacOS

Export keys and seeds
 OK MacOS

Import from keys and seeds correctly
OK  MacOS

Perform a full reset
  MacOS

Integrated Addresses work
OK  MacOS

All RPC endpoints and methods are operational
OK  MacOS

**Comment by brandonlehmann** [comment]
@woodyjon thanks. I've updated the task list with those marked as complete.

**Comment by RocksteadyTC** [comment]
Looks like we just lack the macos zedwallet tests

**Comment by RocksteadyTC** [comment]
shit boys, is this going to be the first good release we do without any wuddabouts?

**Comment by woodyjon** [comment]
I'm doing gui ones. almost done.
I can then do zedwallet on mac.

**Comment by woodyjon** [comment]
GUI wise, everything ok, for all 3 platforms

**Comment by RocksteadyTC** [comment]
this is great news, thanks

**Comment by RocksteadyTC** [comment]
updated it

**Comment by woodyjon** [comment]
Let's go?

**Comment by woodyjon** [comment]
I've done the zedwallet tests on mac. Everything works fine. 
But I did not test fusion transaction and reset.

**Comment by brandonlehmann** [comment]
Fun. I think that’s what we were waiting for. I’ll read through and check in a few hours.

**Comment by brandonlehmann** [comment]
Just two more checks need cleared. 

Also need to update the default 5k checkpoints to current. I’ll get that put together.

**Comment by woodyjon** [comment]
I think it's ok without the 2 remaining mac checks. 0.7.0 does not work at all for most mac users. So even if there are small issues, 0.8.0 will be much better for them.

**Comment by woodyjon** [comment]
zedwallet mac reset ok

**Comment by brandonlehmann** [comment]
Thanks @woodyjon 

building updated checkpoints now...

**Comment by brandonlehmann** [comment]
https://github.com/turtlecoin/turtlecoin/releases/tag/v0.8.0

**Comment by RocksteadyTC** [comment]
Needs to add the following:
[x] Daemon has stayed in sync for 24h

**Comment by brandonlehmann** [comment]
Y u reopen? This is released. If not staying synced new issue 👍
