### ISSUE TITLE
[ZEDWALLET] [BUG] Integrated address in confirmation screen is not the same as entered integrated address

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtlecoin#431]
```
What address do you want to transfer to?: TRTLuy9PaPhAQSYAjmMapG9Zk5BWa7pNw9aJzuwT6PRPBuZRuRKPAiR9jSjCtmxrZiC57Jyqtt8xSCaQKvWJjqj1AQk2325kKmQ2eeNaty9F3VXnU8GXwoVRvTvHaVVafpGKTfBJXYGySdQ5C7uwFkx7uSJpp4fwwkv3nUQ54MbFStQmjaC8yGuWXMb

How much TRTL do you want to send?: 6

What fee do you want to use?
Hit enter for the default fee of 0.10 TRTL:

Confirm Transaction?
You are sending 6 TRTL, with a network fee of 0.10 TRTL and a node fee of 0.00 TRTL.

FROM: sajo.wallet
TO: TRTLuyy1vpXAQSpAbYHXjE9Zk5BXPZTqD9bXLHnoiTkRHFzxMFXAfiD9jSjCubQTbJHRYqRg6rLvnHvqrNMKxwkPARxMUUqCDEv2eeNaty9F3VXnU8GXwoVRvTvHaVVafpGKTfBJXYGySdQ5C7uwFkx7uSJpp4fwwkv3nUQ54MbFStQmjaC8yGZht9b
```

**Comment by brandonlehmann** [comment]
```
[TRTL test.bin]: make_integrated_address
Creating an integrated address from an address and payment ID pair...

Address: TRTLuxN6FVALYxeAEKhtWDYNS9Vd9dHVp3QHwjKbo76ggQKgUfVjQp8iPypECCy3MwZVyu89k1fWE2Ji6EKedbrqECHHWouZN6g

Payment ID: 80EC855EEF7DF4BCE718442CABE086F19DFDD0D03907C7768EDDB8ECA8C5A667

TRTLuxuwKhUAQHcmumthJKCk4wxavpynX9jShjwJqwDHAQKxgX2bsNTCQWpy6vvCo8CF5RrbbsbJsC5R5KUzU6drBudsrLJYfz8LYxeAEKhtWDYNS9Vd9dHVp3QHwjKbo76ggQKgUfVjQp8iPypECCy3MwZVyu89k1fWE2Ji6EKedbrqECHHWpmjvke

[TRTL test.bin]: make_integrated_address
Creating an integrated address from an address and payment ID pair...

Address: TRTLuxN6FVALYxeAEKhtWDYNS9Vd9dHVp3QHwjKbo76ggQKgUfVjQp8iPypECCy3MwZVyu89k1fWE2Ji6EKedbrqECHHWouZN6g

Payment ID: 80ec855eef7df4bce718442cabe086f19dfdd0d03907c7768eddb8eca8c5a667

TRTLuxuwN9GAQHcqXzXcJXJ6WkQGuYLpo9jShoZXUteBAQLEckbGQ7uHkxdMAhBQFYHbWxJRoqqj1HRrsmAyBW7NHG5QJAWL8YgLYxeAEKhtWDYNS9Vd9dHVp3QHwjKbo76ggQKgUfVjQp8iPypECCy3MwZVyu89k1fWE2Ji6EKedbrqECHHWrnqfeZ
```

cAsE sEnSiTiViTy At WoRk

**Comment by ZedPea** [comment]
fk u mom grammer is for nerds

**Comment by ZedPea** [comment]
Brain not running at full speed, can we upper/lowercase the payment ID before dealing with it or will that not work since we don't know if it was upper or lower before encoding.

**Comment by brandonlehmann** [comment]
In zedwallet ? Could compare it against what the user typed in and upper or lower it til you find it... but alas I could create mixed case payment ids before I create the integrated addresses I distribute it to someone and you’d never find it. 

Or... we change the creation of integrated addresses to force upper or lower but that kind of sets an arbitrary limit on the number of possible payment ids

**Comment by ZedPea** [comment]
Well, the easy way is just to print the confirmation as the same as the input - just pass the integrated address through. Ugly but probably the best choice

**Comment by SoreGums** [comment]
Not really ugly though.

If an app wants to print the confirmation of input yet the input is transformed to no longer exist with all the other outputs then yeah, just use the input.

Yo user, you put all this in and we confirm that given these inputs, these are the resulting outputs.

**Comment by brandonlehmann** [comment]
I tend to agree with this. As I mentioned on discord, I ran into this unexpectedly while working on an app using payment IDs, as a result, I went for subaddresses.  It *looks* like another well known bytecoin fork  *may* actually have the same issue. That fork is actually moving away from integrated addresses towards subaddresses in their gui wallet... *coincidence*?

**Comment by SoreGums** [comment]
Subaddresses have their own set of concerns meaning one needs to store more private keys. Unless they can be done in a deterministic way. Such that the first, to nth address is always the same given the first lot of keys/seed.

If subaddress is not deterministic, it probably is the same amount of effort between integrated address and subaddress.

**Comment by brandonlehmann** [comment]
Let’s just regurgitate the input. :)
