### ISSUE TITLE
simplewallet.exe hangs after upgrading to v0.3.1

### ISSUE THREAD

**Issue by BannedForLife** [turtlecoin/turtlecoin#45]
After upgrading to to v0.3.1 simplewallet.exe hangs with the following output:

`Sync from timestamp: 0`

If I kill the program and try opening my wallet again I recieve:

`2018-Feb-07 14:57:07.015861 ERROR   Error: failed to load wallet: can't load wallet file 'myWall.bin.wallet', check password`
`2018-Feb-07 14:57:07.015861 ERROR   Failed to initialize wallet`

My password and wallet name are definitely correct.

**Comment by pypper** [comment]
@BannedForLife are you still seeing this issue on the 0.4.2 release?

**Comment by SoreGums** [comment]
there are going to be other issues people run into now that 0.4.x is out.
this particular issue is no longer possible due to the format change.
let's close this one :)
