### ISSUE TITLE
After Upgrade to 0.3.1 Simplewallet has Zero Balance

### ISSUE THREAD

**Issue by optonerd50** [turtlecoin/turtlecoin#46]
I upgraded this morning.  Am sure I have the proper address and keys.  The wallet shows zero balance.  I had only a trivial amount  in this one, no big deal.  But I need to make sure I know what I'm doing before importing more to it.  Also,  have been getting of lot of these: "[BlockchainSynchronizer]Failed to query blocks: NodeErrorCategory:5, Internal node error".   I'm a Windows 10 user.  Thanks

**Comment by pavelprudnikov** [comment]
the same, reset has no effect

**Comment by nnamon** [comment]
Restart both the daemon and the simplewallet. `reset` in simplewallet.

**Comment by pavelprudnikov** [comment]
Thanks, but I have tried several times, no effect.. keep trying...

**Comment by nnamon** [comment]
Try resyncing the blockchain.

**Comment by optonerd50** [comment]
It is working now and showing proper balance. First, I typed "reset" within simplewallet.exe.    Then, before running simplewallet.exe,  I deleted the  walletname.wallet and walletname .address files  (of course i had named them something else besides walletname).  This because perhaps they were corrupted somehow.  Then when starting up simplewallet, I typed "I" for import rather than "O" for open.  Then when asked I loaded the appropriate addresses.  Works fine now.

**Comment by pavelprudnikov** [comment]
Rebuilt from source, resync blockchain, created new file, imported wallet, but i still have zero balance and no transfers and this error:
[wallet TRTLv2]: 2018-Feb-10 12:43:35.265406 ERROR   [BlockchainSynchronizer] Failed to query blocks: NodeErrorCategory:5, Internal node error

**Comment by pavelprudnikov** [comment]
Finally, that helped.

**Comment by SoreGums** [comment]
Looks like issue is resolved - will close if no response received in 24hrs
