### ISSUE TITLE
TurtleCoind - turtle-service

### ISSUE THREAD

**Issue by R00dNet** [turtlecoin/turtlecoin#480]
Why have you included mentioned services with versions 0.7x when they are both 0.8x now?

https://github.com/turtlecoin/turtlecoin/releases/tag/v0.8.3 released today too.

**Comment by brandonlehmann** [comment]
What?

**Comment by fexra** [comment]
We renamed walletd to turtle-service in v0.7.0. See the [release notes](https://github.com/turtlecoin/turtlecoin/releases/tag/v0.7.0).

**Comment by R00dNet** [comment]
![trtl0 7x](https://user-images.githubusercontent.com/37847231/45301203-5e399d00-b508-11e8-8850-95a5f37661e9.jpg)
![trtl0 8x](https://user-images.githubusercontent.com/37847231/45301209-61348d80-b508-11e8-8b7e-b437a669b4d2.jpg)

**Comment by R00dNet** [comment]
ugh my bad. this was meant for nest. sorry was not paying attention
