### ISSUE TITLE
Error exec xaria zedwallet in Ubuntu 16.04

### ISSUE THREAD

**Issue by yoburtu** [turtlecoin/turtlecoin#481]
Hello,

When I try exec xaria zedwallet 0.02 version linux cli in Ubuntu 16.04, I have got this error:

zedwallet: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory.

Best regards.

**Comment by crappyrules** [comment]
Well? Umm.

**Comment by zpalmtree** [comment]
Please try the latest release: https://github.com/turtlecoin/turtlecoin/releases/tag/v0.8.3

**Comment by crappyrules** [comment]
@yogurt you should ask your coin developer for assistance

**Comment by brandonlehmann** [comment]
@yoburtu Perhaps you mean to open an issue over at https://github.com/xaria-coin/xaria 

Might want to check out their discord listed on their website at http://xaria.xyz/ : https://discord.gg/kDmqsZT

Unfortunately, we don't have anything to do with that project aside from the fact that they forked our repo.

**Comment by xaria-coin** [comment]
Hi
Sorry thanks for letting me know, not sure why issues were turned off
Sorted now
