### ISSUE TITLE
Transaction Pool Cleaner

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#492]
https://github.com/turtlecoin/turtlecoin/blob/8c8641c2c249120563c06dc5b646a6e3f9beeed1/src/CryptoNoteCore/TransactionPoolCleaner.cpp#L84

This needs turned up a notch to validate the mixin of transactions and clear out those that don't match the current network state.

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/45589001-b3e4bf80-b8e3-11e8-8e83-ad9abc6b83b9.png)

**Comment by zpalmtree** [comment]
haha, what a funny image. Can I save it?

**Comment by brandonlehmann** [comment]
Look. It’s @fexra

**Comment by brandonlehmann** [comment]
PR is ready for this as #495 -- awaiting CI test completion.
