### ISSUE TITLE
0.8.3 Windows Daemon Crashes on Ivy Bridge CPU

### ISSUE THREAD

**Issue by dschroth** [turtlecoin/turtlecoin#496]
### System Information

**Operating System**: Windows
**OS Version**: 7
**CPU Make, Model, & Speed**: VM running on E5-2695 v2
**Amount of RAM**: 16GB
**Hard Drive Type**: Drive Storage is on platter based RAID 10
**Hard Drive Size**: 250GB
**Volume Type**: NTFS

### TurtleCoin Build Information

**Version:** v0.8.3.1275
**Binary Source:** Used both 0.8.3 windows binaries AND compiled from source
**If self compiled, please provide all the build commands you used**
``` Followed 0.8.3 build instructions for Windows 10
Please insert your build commands here. :

Use the start menu or similar to open 'x64 Native Tools Command Prompt for vs2017' command prompt.
cd <your_turtlecoin_directory>
mkdir build
cd build
cmake -G "Visual Studio 14 Win64" .. -DBOOST_ROOT=D:/Boost/boost_1_59_0 (Or your boost installed dir.)
MSBuild TurtleCoin.sln /p:Configuration=Release
```

**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:
```

Please insert your default verbosity CMake output here
```
[CMakeOutput.log](https://github.com/turtlecoin/turtlecoin/files/2386306/CMakeOutput.log)
[CMakeCache.txt](https://github.com/turtlecoin/turtlecoin/files/2386307/CMakeCache.txt)
### Issue Report

**Binary Reported:** TurtleCoind

#### Expected Behavior

Daemon is expected to start and run.

#### Current Behavior

Daemon crashes opening the DB within the RocksDBWrapper. Tried deleting existing DB with no change.

##### Screen Shots

![image](https://user-images.githubusercontent.com/14900108/45593006-f04b0680-b949-11e8-9b12-86c1429a5b71.png)

#### Steps to Reproduce

1. Execute Turtlecoind on an IvyBridge generation Intel CPU running Windows.
2. ...
3. No profit.

#### Possible Solution

CPU instructions present in Haswell (daemon works) but missing from Ivy Bridge (doesn't work) - VT-x, AVX2, FMA3

Based on Discord conversation - 

GNU/iburnmycd™Today at 12:20 AM
Thanks.
Are you sure you built from release source ? And totally blew away any previous builds in the folder ?
I’m seeing stuff in there that doesn’t match the current default build Params

schroToday at 12:27 AM
Fairly sure - I've never built anything on this VM before now.
Installed VS 2017/bonus pack things, copied from github and ran the instructions...

GNU/iburnmycd™Today at 12:30 AM
However, I think I see a possible laziness in MSVC.

**Comment by brandonlehmann** [comment]
@dschroth PR #509 is currently open that I **believe** will resolve this issue for you.

**Comment by dschroth** [comment]
Awesome!  Looking forward to testing it!

**Comment by brandonlehmann** [comment]
@dschroth Please give [turtlecoin-7f3e531d4cfa19c364eb8cad0e46fe6f1c5d755a-windows.zip](https://github.com/turtlecoin/turtlecoin/files/2416279/turtlecoin-7f3e531d4cfa19c364eb8cad0e46fe6f1c5d755a-windows.zip) (AppVeyor build) a go when you get a moment and reopen the issue if it doesn't fix the issue for you.

**Comment by dschroth** [comment]
1. Downloaded.
2. Extracted executables.
3. Ran turtlecoind.
4. ...
5. No profit.

![image](https://user-images.githubusercontent.com/14900108/46100839-69432d00-c198-11e8-8e71-7e2eb038c397.png)

**Comment by brandonlehmann** [comment]
What was the last binary release that “just worked” for you?

**Comment by dschroth** [comment]
0.7.0 is the last release that worked. I jumped from there to 0.8.3.  I just pulled down 0.8.0 and that also crashes for me.

**Comment by brandonlehmann** [comment]
And can you also click that “view problem details” option and send in what it says ?

**Comment by dschroth** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	TurtleCoind.exe
  Application Version:	0.8.4.1276
  Application Timestamp:	5baa6b6b
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.24024
  Fault Module Timestamp:	5a58e5b7
  Exception Code:	c0000005
  Exception Offset:	000000000000b2b2
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	cc93
  Additional Information 2:	cc93dcd169c042239634a9f80beacfaf
  Additional Information 3:	7f5b
  Additional Information 4:	7f5b3cfd23d7c94855306b7bd9a0f47e

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by brandonlehmann** [comment]
Interesting. 

https://stackoverflow.com/questions/17168982/exception-error-c0000005-in-vc

**Comment by dschroth** [comment]
That is interesting. Maybe I'll try a good old fashioned reboot...

**Comment by brandonlehmann** [comment]
Still doing some looking around on this side. Just to confirm here in the issue, you also get the error when building from source or no?

**Comment by dschroth** [comment]
I built 0.8.3 from source and got the same error, I have not built the Test version from source. If you'd like me to give that a spin, I can try it if I can be directed to the right branch to copy from.

**Comment by brandonlehmann** [comment]
@dschroth we'll see if https://github.com/turtlecoin/turtlecoin/pull/526 does it :)

**Comment by brandonlehmann** [comment]
Awesome! Thanks man! I'm gonna close this issue again.
