### ISSUE TITLE
multi_installer.sh fails to run on ubuntu 17.10

### ISSUE THREAD

**Issue by CaptainMeatloaf** [turtlecoin/turtlecoin#50]
I tried using the multi_installer.sh script to build the latest version of turtlecoin on a VirtualBox Virtual Machine, running 17.10.

Upon running it, I get the following error:
![image](https://user-images.githubusercontent.com/3893247/35982397-9e32dd1e-0ce7-11e8-8c75-c796d1897758.png)

Looks like some of the required packages are missing on the latest version.

**Comment by nnamon** [comment]
I think we could remove the version numbers from the apt-get packages. They work as well on the latest versions.
