### ISSUE TITLE
TODO: Reorder zedwallet transfer prompt arguments

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#502]
A user was concerned that he wasn't going to have the chance to put in his payment ID, after he got to the fee confirmation. We should probably put the payment ID prompt right after the address prompt, as they set the 'destination'.

**Comment by zpalmtree** [comment]
Actually, should we remove fee whilst we're there? There's not really any reason to use anything other than 0.1 TRTL.

**Comment by brandonlehmann** [comment]
Don’t remove it. I use it. The daemon does use fee as a metric when building block templates.

**Comment by zpalmtree** [comment]
>The daemon does use fee as a metric when building block templates.

Not sure how this relates, I'm just talking about the option in zedwallet, not removing fee completely

**Comment by brandonlehmann** [comment]
If you remove the option in zedwallet how am I meant to pick a different fee? Now I have to fire up turtle-service and go through all that or box-turtle just to be able to pick a few other than the default? Doesn’t seem right to me. Selecting the fee and the ability to do such when sending a transaction is a fundamental need. Removing it feels bad all around.

**Comment by brandonlehmann** [comment]
IRT OP: yes. Moving the payment ID makes sense :)

To be clear: removing the fee option does not make sense IMO

**Comment by zpalmtree** [comment]
OK. Just trying to make things more streamlined since you have to actively input something if you want to skip an option in CLI's.

**Comment by brandonlehmann** [comment]
I’m pretty sure I can just mash the enter key and it takes the default. The only thing I **must** enter is address and amount. Are you saying I must key in 0.1 for the fee?

**Comment by zpalmtree** [comment]
No, just that hitting enter is in itself an action, and if you're new to the program it takes time to read through that.

**Comment by brandonlehmann** [comment]
a little bit of complexity never hurts when we explain what the option is for. If the choices are “educate the users” versus anything else... I think educating the users always wins. 

Transaction fees are a core part of a crypto currency network. We have to keep it in their face at all times to help educate... not hide it because it’s confusing.

**Comment by rixombea** [comment]
or maybe add new command line argument, something like `--advance` or `--expert` 
default to dumb down mode, which remove most of the 'confusing' options, and show 2 pages warning for every action.

In advance mode, show every possible options and maybe skip all the warning and confirmations

**Comment by brandonlehmann** [comment]
Again, I believe this takes away something that users **need** to know about. Specifying the network fee for a transaction isn’t “advanced” by any stroke of imagination. To call it that (advanced or expert), does a disservice to the user base and fails to educate them which is part of the core goal of the project. 

Users don’t need coddled... they need educated.
