### ISSUE TITLE
Incorrect additional command on daemon start causes daemon to crash and force close

### ISSUE THREAD

**Issue by BigslimVdub** [turtlecoin/turtlecoin#524]
v0.8.3.1275
windows 10

Running a batch file to open TurtlecoinD while using unknown command causes daemon to attempt to load help command list then crashes and force closes.

I found this after forgetting -- before the command only putting -.

Example: 
`C:\Users\TurtleUser\Desktop\TurtleCoin\TurtleCoind.exe -datadir-*file location* `
-Causes daemon to attempt to display help commands then crashes and force closes

Expected output:
`C:\Users\TurtleUser\Desktop\TurtleCoin\TurtleCoind.exe --datadir-*file location* `
-Causes daemon to load correctly and start to sync

Same issue here https://github.com/aeonix/aeon-legacy/issues/131

**Comment by brandonlehmann** [comment]
You mean giving an invalid CLI argument displays the help and then closes the program? For shame. 

What you you prefer it do?

**Comment by BigslimVdub** [comment]
Daemon should not close itself if incorrect cli argument is given. It should either prompt the error of incorrect argument or prompt the help commands as if user is prompting - -help

**Comment by zpalmtree** [comment]
That's not how CLI programs work
