### ISSUE TITLE
[BUG] view_wallet incorrect balance count (FUSION trx are added to balance)

### ISSUE THREAD

**Issue by polar-it** [turtlecoin/turtlecoin#531]
### System Information

**Operating System**:  Ubuntu
**OS Version**:  16.04.5 LTS (Xenial Xerus) 
**CPU Make, Model, & Speed**: Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz
**Amount of RAM**: 8GB
**Hard Drive Type**: SDD
**Hard Drive Size**: 200GB
**Volume Type**: /ext4

### TurtleCoin Build Information

**Version:** TurtleCoin v0.8.3.1275 ()
**Binary Source:**  local build
```
Please insert your build commands here. Example:

mkdir build && cd build
cmake .. -DBOOST_ROOT=/root/boost_1_68_0
make -j4
```

**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:
```
Please insert your default verbosity CMake output here
```

### Issue Report

**Binary Reported:** zedwallet 

#### Expected Behavior

On a new generated view_wallet balance is incorrect, view_wallet was reset from 0.

Checking on the view_wallet FUSION transaction are added to the balance and are present in the list of incoming transaction.

 

Here are the two wallet: the first is a full wallet the second is a view_wallet

[TRTL full_wallet]: address
TRTLv1ioHt8Eyo8u**************************************************************FFD
[TRTL full_wallet]: balance
Available balance: 131,799.90 TRTL
Locked (unconfirmed) balance: 0.00 TRTL
Total balance: 131,799.90 TRTL
[TRTL full_wallet]: exit

Your view only wallet TRTLv1ioHt8Eyo8u**************************************************************FFD has been successfully opened!
[TRTL read_view]: balance
Available balance: 367,869.90 TRTL
Locked (unconfirmed) balance: 0.00 TRTL
Total balance: 367,869.90 TRTL

#### Steps to Reproduce

On two zedwallet instance open a full wallet and a view wallet

On the full wallet execute  optimize  ( option number 16 ) of zedwallet

On the view wallet are shown as incoming fusion trx and added to the balance

**Comment by zpalmtree** [comment]
I think the best way to solve this is to calculate the view wallet by iterating through the transactions and only adding the amounts of transactions with a non zero fee - This does however make the count incorrect if a user has sent a fusion from one subwallet to another subwallet.

**Comment by rashedmyt** [comment]
what about coinbase transactions..? @zpalmtree

**Comment by zpalmtree** [comment]
I think we can check for that with `bool isBase;`

**Comment by zpalmtree** [comment]
@polar-it Can you test if #561 solves your issue?
