### ISSUE TITLE
cryptotest, turtle-service shouldnt be in default build

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/turtlecoin#537]
builds should generate the files that users need. Daemon and CLI-wallet. 

devs and services should compile a different target `make dev` or something similar that triggers an inclusive build that compiles daemon, wallet, services, cryptotest

normal users should compile the vanilla make target `make` and that should build only daemon and cli-wallet.

**Comment by zpalmtree** [comment]
I think if you want to go this path then we should at least include turtle-service. I would wager the majority of users of standard compilation are service operators, developers, and interested parties.
They'll also all mostly be linux users, who are the most likely to want to touch turtle-service.

We already have `make cli` that makes just the `daemon` and `zedwallet` - you could perhaps update the instructions to point to that?

**Comment by brandonlehmann** [comment]
I tend to agree with Zpalm. 

Updating the directions versus updating the build is a far easier path. 

Defining targets in CMake is kind of goofy to be honest. If you only wanted to build a subset of the targets, those options would have to be cmake flags, not make flags. Which gets weird IMO. 

Also... IMO general users rely on the posted binaries... if you want to package up smaller packs that’s not a bad idea as well but even then it becomes a bit “bloaty”. 

The lions time of a build is spent on rocksdb and the underlying cryptonotecode which every target relies on. 

`make cli` in the directions is better...

**Comment by brandonlehmann** [comment]
This conversation belongs on META
