### ISSUE TITLE
[ENHANCEMENT] Report invalid command line arguments in zedwallet

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#557]
If someone enters an invalid argument, the program will continue fine. We should probably error out. Then if you typo --remote-daemon or something, you won't wonder why it's not connecting.

**Comment by brandonlehmann** [comment]
Shouldn't it print out a *help* and then exit? listing all the CLI arguments?

**Comment by zpalmtree** [comment]
Yeah, that's what I mean.

**Comment by zpalmtree** [comment]
Fixed by #562
