### ISSUE TITLE
[ENHANCEMENT] Give a better error if genesis_tx_hex is wiped

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#558]
If you set it to the empty string, zedwallet will crash with 'Failed to initialize currency object'. Easy if() can fix this.

**Comment by brandonlehmann** [comment]
Are you saying if https://github.com/turtlecoin/turtlecoin/blob/b23314b0b31e89aac45775793c9a695ec5239eb0/src/config/CryptoNoteConfig.h#L71 is empty ("") that it throws a fit?

**Comment by zpalmtree** [comment]
Yes

**Comment by brandonlehmann** [comment]
Is there any use case where that would (or should) be empty?

**Comment by zpalmtree** [comment]
Quite often people wipe it when they're forking

**Comment by brandonlehmann** [comment]
Dumb question then... shouldn't they generate a new one for their fork?

**Comment by zpalmtree** [comment]
Using the default genesis tx works fine, they sometimes mess it up when trying to setup a premine and empty it

**Comment by brandonlehmann** [comment]
I guess I phrased that wrong.

Is a genesis transaction (premine or not) required for proper chain operation?

**Comment by zpalmtree** [comment]
A genesis transaction is required, yes. We can generate one if it's not given, though. That would probably not work too well with reading back in.

**Comment by brandonlehmann** [comment]
Gotcha.
