### ISSUE TITLE
TurtleCoin v0.8.4 RC2 Release Candidate Test Log

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#568]
# TurtleCoin v0.8.4 RC2 Release Candidate Test Log

Build from: https://github.com/turtlecoin/turtlecoin/tree/v0.8.4-RC2

Binaries for Testing:
  - Windows: [turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-windows.zip](https://github.com/turtlecoin/turtlecoin/files/2499413/turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-windows.zip)
  - Linux: [turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-linux.tar.gz](https://github.com/turtlecoin/turtlecoin/files/2499409/turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-linux.tar.gz)
  - MacOS: [turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-osx.tar.gz](https://github.com/turtlecoin/turtlecoin/files/2499410/turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-osx.tar.gz)
  - AARCH64: [turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-aarch64.tar.gz](https://github.com/turtlecoin/turtlecoin/files/2499411/turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-aarch64.tar.gz)

### Project
- [x] Currently Passing Travis & AppVeyor build tests
- [x] `Version.h.in` updated to correct semver value
- [x] Release Notes Prepared (https://hackmd.io/s/ryaWKXcj7)

### TurtleCoind Tests
- Daemon connects to local DB
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Local DB does not require resync
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Peer ID assigned
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Connections to multiple peers are made
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Daemon able to sync with external checkpoints
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Daemon able to sync without external checkpoints
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Daemon able to sync from 0 with external checkpoints
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Daemon able to sync from 0 without external checkpoints
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Daemon stays synchronized for 24 hours
  - [x] Windows
  - [x] Linux
  - [x] MacOS
 
### ZedWallet Tests
- Connect to local daemon
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Connect to a remote daemon
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Send a transaction
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Receive a transaction
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Perform a fusion transaction
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Export keys and seeds
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Import from keys and seeds correctly
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Perform a full reset
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Integrated Addresses work
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Scan From Height Works Correctly
  - [x] Windows
  - [x] Linux
  - [x] MacOS

### Turtle-Service Tests
- Connect to local daemon
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Connect to a remote daemon
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Send a transaction
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Receive a transaction
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Perform a fusion transaction
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Export keys and seeds
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Import from keys and seeds correctly
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Perform a full reset
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Integrated Addresses work
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- All RPC endpoints and methods are operational
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Scan From Height Works Correctly
  - [x] Windows
  - [x] Linux
  - [x] MacOS

### GUI Wallet Testing
- Connect to local daemon
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Connect to a remote daemon
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Send a transaction
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Receive a transaction
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Perform a fusion transaction
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Export keys and seeds
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Import from keys and seeds correctly
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Perform a full reset
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Integrated Addresses work
  - [x] Windows
  - [x] Linux
  - [x] MacOS
- Scan From Height Works Correctly
  - [x] Windows
  - [x] Linux
  - [x] MacOS

**Comment by brandonlehmann** [comment]
Release notes added/updated from RC1

**Comment by brandonlehmann** [comment]
Travis binaries have been uploaded. Appveyor binary in progress

**Comment by brandonlehmann** [comment]
Windows binaries ready

**Comment by rashedmyt** [comment]
**Windows 10 1803**

### TurtleCoind Tests

- [ ] Daemon connects to local DB
- [ ] Local DB does not require resync
- [ ] Peer ID assigned
- [ ] Connections to multiple peers are made
- [ ] Daemon able to sync with external checkpoints
- [ ] Daemon able to sync without external checkpoints
- [ ] Daemon able to sync from 0 with external checkpoints
- [ ] Daemon able to sync from 0 without external checkpoints
- [ ] Daemon stays synchronised for 24 hours

### ZedWallet Tests

- [ ] Connect to local daemon
- [ ] Connect to a remote daemon
- [ ] Send a transaction
- [ ] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [ ] Integrated Addresses work
- [ ] Scan From Height Works Correctly

### Turtle-Service Tests

- [ ] Connect to local daemon
- [ ] Connect to a remote daemon
- [ ] Send a transaction
- [ ] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [ ] Integrated Addresses work
- [ ] All RPC endpoints and methods are operational
- [ ] Scan From Height Works Correctly

### GUI Wallet Tests

- [ ] Connect to local daemon
- [ ] Connect to a remote daemon
- [ ] Send a transaction
- [ ] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [ ] Integrated Addresses work
- [ ] Scan From Height Works Correctly

**Comment by Sajo8** [comment]
**Windows 10 1803**

*Builds successfully*

### TurtleCoind Tests

- [x] Daemon connects to local DB
- [ ] Local DB does not require resync
- [x] Peer ID assigned
- [x] Connections to multiple peers are made
- [x] Daemon able to sync with external checkpoints
- [ ] Daemon able to sync without external checkpoints
- [ ] Daemon able to sync from 0 with external checkpoints
- [ ] Daemon able to sync from 0 without external checkpoints
- [ ] Daemon stays synchronised for 24 hours

### ZedWallet Tests

- [ ] Connect to local daemon
- [ ] Connect to a remote daemon
- [ ] Send a transaction
- [ ] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [ ] Integrated Addresses work
- [ ] Scan From Height Works Correctly

### Turtle-Service Tests

- [ ] Connect to local daemon
- [ ] Connect to a remote daemon
- [ ] Send a transaction
- [ ] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [ ] Integrated Addresses work
- [ ] All RPC endpoints and methods are operational
- [ ] Scan From Height Works Correctly

### GUI Wallet Tests

- [ ] Connect to local daemon
- [ ] Connect to a remote daemon
- [ ] Send a transaction
- [ ] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [ ] Integrated Addresses work
- [ ] Scan From Height Works Correctly

**Comment by mrlahaye** [comment]
I will update my comment as testing continues.

 Windows 10 X64 Build 1709 version 17134.228 (**In Progress**)

**TurtleCoind Tests** (**In Progress**)
- [x] Daemon connects to local DB
- [ ] Local DB does not require resync -> In Progress
- [x] Peer ID assigned -> Generated new peer ID: 7071193942218808264
- [x] Connections to multiple peers are made -> In Progress
- [ ] Daemon able to sync with external checkpoints
- [ ] Daemon able to sync without external checkpoints -> In Progress
- [ ] Daemon able to sync from 0 with external checkpoints
- [ ] Daemon able to sync from 0 without external checkpoints
- [ ] Daemon stays synchronised for 24 hours  -> In Progress

**ZedWallet Tests** (**In Progress**)
- [ ] Connect to local daemon
- [x] Connect to a remote daemon
- [x] Send a transaction
- [x] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [x] Integrated Addresses work
- [ ] Scan From Height Works Correctly

Ubuntu 18.04.1 LTS (**In Progress**)

**ZedWallet Tests** 
- [ ] Connect to local daemon
- [x] Connect to a remote daemon
- [x] Send a transaction
- [x] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [x] Integrated Addresses work
- [ ] Scan From Height Works Correctly

Ubuntu Server 16.04.1 LTS (**In Progress**)

**TurtleCoind Tests**
- [x] Daemon connects to local DB
- [ ] Local DB does not require resync
- [x] Peer ID assigned -> Generated new peer ID: 14972077689722305938
- [x] Connections to multiple peers are made
- [ ] Daemon able to sync with external checkpoints 
- [ ] Daemon able to sync without external checkpoints
- [ ] Daemon able to sync from 0 with external checkpoints
- [ ] Daemon able to sync from 0 without external checkpoints -> In Progress
- [ ] Daemon stays synchronised for 24 hours -> In Progress

**Comment by SoreGums** [comment]
**Linux Arch - prebuilt binary**


### TurtleCoind Tests

- [x] Daemon connects to local DB
- [x] Local DB does not require resync
- [x] Peer ID assigned
- [x] Connections to multiple peers are made
- [] Daemon able to sync with external checkpoints
- [] Daemon able to sync without external checkpoints
- [] Daemon able to sync from 0 with external checkpoints
- [] Daemon able to sync from 0 without external checkpoints
- [] Daemon stays synchronised for 24 hours

### ZedWallet Tests

- [] Connect to local daemon
- [] Connect to a remote daemon
- [] Send a transaction
- [] Receive a transaction
- [] Perform a fusion transaction
- [] Export keys and seeds
- [] Import from keys and seeds correctly
- [] Perform a full reset
- [] Integrated Addresses work
- [] Scan From Height Works Correctly

### Turtle-Service Tests

- [] Connect to local daemon
- [] Connect to a remote daemon
- [] Send a transaction
- [] Receive a transaction
- [] Perform a fusion transaction
- [] Export keys and seeds
- [] Import from keys and seeds correctly
- [] Perform a full reset
- [] Integrated Addresses work
- [] All RPC endpoints and methods are operational
- [] Scan From Height Works Correctly

### GUI Wallet Tests

- [ ] Connect to local daemon
- [ ] Connect to a remote daemon
- [ ] Send a transaction
- [ ] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [ ] Integrated Addresses work
- [ ] Scan From Height Works Correctly

**Comment by fexra** [comment]
**Ubuntu 18.04 LTS 1 - prebuilt binary**

### TurtleCoind Tests
* [x]  Daemon connects to local DB
* [x]  Local DB does not require resync
* [x]  Peer ID assigned
* [x]  Connections to multiple peers are made
* [x]  Daemon able to sync with external checkpoints
* [ ]  Daemon able to sync without external checkpoints
* [ ]  Daemon able to sync from 0 with external checkpoints
* [ ]  Daemon able to sync from 0 without external checkpoints
* [ ]  Daemon stays synchronised for 24 hours

### ZedWallet Tests
* [x]  Connect to local daemon
* [x]  Connect to a remote daemon
* [x]  Send a transaction
* [x]  Receive a transaction
* [x]  Perform a fusion transaction
* [x]  Export keys and seeds
* [x]  Import from keys and seeds correctly
* [ ]  Perform a full reset
* [ ]  Integrated Addresses work
* [x]  Scan From Height Works Correctly

### Turtle-Service Tests
* [x]  Connect to local daemon
* [x]  Connect to a remote daemon
* [x]  Send a transaction
* [x]  Receive a transaction
* [x]  Perform a fusion transaction
* [x]  Export keys and seeds
* [x]  Import from keys and seeds correctly
* [ ]  Perform a full reset
* [ ]  Integrated Addresses work
* [ ]  All RPC endpoints and methods are operational
* [x]  Scan From Height Works Correctly

### GUI Wallet Tests
* [ ]  Connect to local daemon
* [ ]  Connect to a remote daemon
* [ ]  Send a transaction
* [ ]  Receive a transaction
* [ ]  Perform a fusion transaction
* [ ]  Export keys and seeds
* [ ]  Import from keys and seeds correctly
* [ ]  Perform a full reset
* [ ]  Integrated Addresses work
* [ ]  Scan From Height Works Correctly

**Comment by rixombea** [comment]
**Linux (NixOS 18.09)**

Build from: https://github.com/turtlecoin/turtlecoin/tree/v0.8.4-RC2

### TurtleCoind Tests
- [x] Daemon connects to local DB
- [x] Local DB does not require resync
- [x] Peer ID assigned
- [x] Connections to multiple peers are made
- [x] Daemon able to sync with external checkpoints
- [x] Daemon able to sync without external checkpoints
- [ ] Daemon able to sync from 0 with external checkpoints
- [ ] Daemon able to sync from 0 without external checkpoints
- [x] Daemon stays synchronised for 24 hours

### ZedWallet Tests
- [x] Connect to local daemon
- [x] Connect to a remote daemon
- [x] Send a transaction
- [x] Receive a transaction
- [x] Perform a fusion transaction
- [x] Export keys and seeds
- [x] Import from keys and seeds correctly
- [x] Perform a full reset
- [x] Integrated Addresses work
- [x] Scan From Height Works Correctly

### Turtle-Service Tests
- [x] Connect to local daemon
- [x] Connect to a remote daemon
- [x] Send a transaction
- [x] Receive a transaction
- [x] Perform a fusion transaction
- [x] Export keys and seeds
- [x] Import from keys and seeds correctly
- [x] Perform a full reset
- [x] Integrated Addresses work
- [x] All RPC endpoints and methods are operational
- [x] Scan From Height Works Correctly

### GUI Wallet Tests
- [ ] Connect to local daemon
- [ ] Connect to a remote daemon
- [ ] Send a transaction
- [ ] Receive a transaction
- [ ] Perform a fusion transaction
- [ ] Export keys and seeds
- [ ] Import from keys and seeds correctly
- [ ] Perform a full reset
- [ ] Integrated Addresses work
- [ ] Scan From Height Works Correctly

**Comment by brandonlehmann** [comment]
Test results updated. Where's our MAC users at?

**Comment by brandonlehmann** [comment]
Still need Linux GUI testing and **all** MAC tests

**Comment by woodyjon** [comment]
## TurtleCoind Tests
- Daemon connects to local DB
    - [x] MacOS
- Local DB does not require resync
    - [x] MacOS
- Peer ID assigned
    - [x] MacOS
- Connections to multiple peers are made
    - [x] MacOS
- Daemon able to sync with external checkpoints
    - [x] MacOS
- Daemon able to sync without external checkpoints
    - [x] MacOS
- Daemon able to sync from 0 with external checkpoints
    - [ ] MacOS
- Daemon able to sync from 0 without external checkpoints
    - [ ] MacOS
- Daemon stays synchronized for 24 hours
    - [ ] MacOS

## Turtle-Service Tests
- Connect to local daemon
    - [x] MacOS
- Connect to a remote daemon
    - [x] MacOS
- Send a transaction
    - [x] MacOS
- Receive a transaction
    - [x] MacOS
- Perform a fusion transaction
    - [ ] MacOS
- Export keys and seeds
    - [x] MacOS
- Import from keys and seeds correctly
    - [x] MacOS
- Perform a full reset
    - [ ] MacOS
- Integrated Addresses work
    - [x] MacOS
- All RPC endpoints and methods are operational
    - [x] MacOS
- Scan From Height Works Correctly
    - [x] MacOS

## GUI Wallet Testing
- Connect to local daemon
    - [x] MacOS
- Connect to a remote daemon
    - [x] MacOS
- Send a transaction
    - [x] MacOS
- Receive a transaction
    - [x] MacOS
- Perform a fusion transaction
    - [ ] MacOS
- Export keys and seeds
    - [x] MacOS
- Import from keys and seeds correctly
    - [x] MacOS
- Perform a full reset
    - [ ] MacOS
- Integrated Addresses work
    - [x] MacOS
- Scan From Height Works Correctly
    - [x] MacOS

**Comment by brandonlehmann** [comment]
Results updated.

Looks like we're still missing MacOS zedwallet tests and a few MacOS stragglers

**Comment by mrlahaye** [comment]
Seems you missed updating zedwallet tests for Mac? all checkboxes are empty.

**Comment by jerme404** [comment]
> ## TurtleCoind Tests
> * Daemon connects to local DB
>   
>   * [x]  MacOS
> * Local DB does not require resync
>   
>   * [x]  MacOS
> * Peer ID assigned
>   
>   * [x]  MacOS
> * Connections to multiple peers are made
>   
>   * [x]  MacOS
> * Daemon able to sync with external checkpoints
>   
>   * [x]  MacOS
> * Daemon able to sync without external checkpoints
>   
>   * [x]  MacOS
> * Daemon able to sync from 0 with external checkpoints
>   
>   * [x]  MacOS
> * Daemon able to sync from 0 without external checkpoints
>   
>   * [x]  MacOS
> * Daemon stays synchronized for 24 hours
>   
>   * [ ]  MacOS
> 
> ## Turtle-Service Tests
> * Connect to local daemon
>   
>   * [x]  MacOS
> * Connect to a remote daemon
>   
>   * [x]  MacOS
> * Send a transaction
>   
>   * [x]  MacOS
> * Receive a transaction
>   
>   * [x]  MacOS
> * Perform a fusion transaction
>   
>   * [ ]  MacOS
> * Export keys and seeds
>   
>   * [x]  MacOS
> * Import from keys and seeds correctly
>   
>   * [x]  MacOS
> * Perform a full reset
>   
>   * [ ]  MacOS
> * Integrated Addresses work
>   
>   * [x]  MacOS
> * All RPC endpoints and methods are operational
>   
>   * [x]  MacOS
> * Scan From Height Works Correctly
>   
>   * [x]  MacOS
> 
> ## GUI Wallet Testing
> * Connect to local daemon
>   
>   * [x]  MacOS
> * Connect to a remote daemon
>   
>   * [x]  MacOS
> * Send a transaction
>   
>   * [x]  MacOS
> * Receive a transaction
>   
>   * [x]  MacOS
> * Perform a fusion transaction
>   
>   * [ ]  MacOS
> * Export keys and seeds
>   
>   * [x]  MacOS
> * Import from keys and seeds correctly
>   
>   * [x]  MacOS
> * Perform a full reset
>   
>   * [ ]  MacOS
> * Integrated Addresses work
>   
>   * [x]  MacOS
> * Scan From Height Works Correctly
>   
>   * [x]  MacOS

**Comment by jerme404** [comment]
> # TurtleCoin v0.8.4 RC2 Release Candidate Test Log
> Build from: https://github.com/turtlecoin/turtlecoin/tree/v0.8.4-RC2
> 
> Binaries for Testing:
> 
> * Windows: [turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-windows.zip](https://github.com/turtlecoin/turtlecoin/files/2499413/turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-windows.zip)
> * Linux: [turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-linux.tar.gz](https://github.com/turtlecoin/turtlecoin/files/2499409/turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-linux.tar.gz)
> * MacOS: [turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-osx.tar.gz](https://github.com/turtlecoin/turtlecoin/files/2499410/turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-osx.tar.gz)
> * AARCH64: [turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-aarch64.tar.gz](https://github.com/turtlecoin/turtlecoin/files/2499411/turtlecoin-63db3a4706b7082b6ea23c52c036cf2a57149e86-aarch64.tar.gz)
> 
> ### Project
> * [x]  Currently Passing Travis & AppVeyor build tests
> * [x]  `Version.h.in` updated to correct semver value
> * [x]  Release Notes Prepared (https://hackmd.io/s/ryaWKXcj7)
> 
> ### TurtleCoind Tests
> * Daemon connects to local DB
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Local DB does not require resync
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Peer ID assigned
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Connections to multiple peers are made
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Daemon able to sync with external checkpoints
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Daemon able to sync without external checkpoints
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Daemon able to sync from 0 with external checkpoints
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Daemon able to sync from 0 without external checkpoints
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Daemon stays synchronized for 24 hours
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> 
> ### ZedWallet Tests
> * Connect to local daemon
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Connect to a remote daemon
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Send a transaction
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Receive a transaction
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Perform a fusion transaction
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Export keys and seeds
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Import from keys and seeds correctly
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Perform a full reset
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Integrated Addresses work
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Scan From Height Works Correctly
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> 
> ### Turtle-Service Tests
> * Connect to local daemon
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Connect to a remote daemon
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Send a transaction
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Receive a transaction
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Perform a fusion transaction
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Export keys and seeds
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Import from keys and seeds correctly
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Perform a full reset
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Integrated Addresses work
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * All RPC endpoints and methods are operational
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Scan From Height Works Correctly
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> 
> ### GUI Wallet Testing
> * Connect to local daemon
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Connect to a remote daemon
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Send a transaction
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Receive a transaction
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Perform a fusion transaction
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Export keys and seeds
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Import from keys and seeds correctly
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Perform a full reset
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Integrated Addresses work
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS
> * Scan From Height Works Correctly
>   
>   * [x]  Windows
>   * [x]  Linux
>   * [x]  MacOS

**Comment by brandonlehmann** [comment]
Thank you @jerme404 

RC tests complete. Closing issue. Release is imminent.
