### ISSUE TITLE
WARNING Proof of work too weak for block 5

### ISSUE THREAD

**Issue by GerryMosha** [turtlecoin/turtlecoin#570]
I have been getting the error ``WARNING Proof of work too weak for block 5`` for over a week now. It does not matter how few things I change. It happens when ever it gets to the block after what UPGRADE_HEIGHT_V5 is set to. I have tried everything possible and the only thing that fixes it is adding back the turtlecoin checkpoints. If the turtlecoin checkpoints are in CryptoNoteCheckpoints.h it works, if CryptoNoteCheckpoints.h has no checkpoints set it fails. I have tested almost every value in CryptoNoteConfig.h by only changing one at a time and it always fails. I have also tried doing ``./miner --address <address> --threads --limit 1`` every few seconds and that does not work either. If anyone knows a solution that would be great. Thank you.

Edit: My CryptoNoteConfig.h - https://pastebin.com/D9QqzYWV

**Comment by brandonlehmann** [comment]
To clarify, @GerryMosha is testing the CN Soft Shell implementation on a new fork of the project and the bug he has reported does not exist on the mainline TurtleCoin code.

@GerryMosha would you mind taking a look at #569 as bugs were found in the CN Soft Shell implementation that you may be running into?

**Comment by GerryMosha** [comment]
@brandonlehmann after I switched to your fork and it was working i realized i had not cleared the CryptoNoteCheckpoints.h file. I cleared the checkpoints and then recompiled and got the same error. So I switched back to https://github.com/turtlecoin/turtlecoin/tree/soft_shell because if i was getting the same error i preferred to be on the official turtlecoin soft_shell branch. that is what i am currently running that is not working. I will try the following right now: https://github.com/turtlecoin/turtlecoin/pull/569/commits/37fe9542d45a0ab3c8b2b1581a0772fdd55e94a2

**Comment by brandonlehmann** [comment]
You're gonna need more than just that commit. That entire branch is an overhaul of the Soft Shell code.

**Comment by GerryMosha** [comment]
So should i stay on https://github.com/turtlecoin/turtlecoin/tree/soft_shell and not switch back https://github.com/brandonlehmann/turtlecoin/tree/soft_shell_v3?

**Comment by brandonlehmann** [comment]
Try https://github.com/brandonlehmann/turtlecoin/tree/soft_shell_v3 that's the one with the updates
