### ISSUE TITLE
Error in JSON serialization in multiple RPC methods

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#603]
### System Information

**Operating System**: All (Windows, Linux, Mac)
**OS Version**: All
**CPU Make, Model, & Speed**: All
**Amount of RAM**: Any
**Hard Drive Type**: N/A
**Hard Drive Size**: N/A
**Volume Type**: N/A

### TurtleCoin Build Information

**Version:** All builds
**Binary Source:** All builds

### Issue Report

**Binary Reported:** TurtleCoind & turtle-service

#### Expected Behavior

Transaction details via the RPC return valid values for their type.

#### Current Behavior

When examining the transaction details of the following transactions:

```
b01a22c8d729acd78adb23a1f1ac1ca2c2b071ab55f38aeb01ba6949a07c3502
ec54aeb57a15cf1387f15c3af6c52bb7ae5808ac4348421713a740e77bc2222f
f8f1229b41b0ef04b33e3e74557f0ed66ba8fcb54657b01c0dd64679c9247dff
```

The transaction details return a negative value (`-2`) for for the `unlock_time`. `unlock_time` is specified as a `uint64_t` which is an unsigned value and thus should not return a negative value. This is an error in the serialization to JSON of the value as the blockchain data holds the correct value (`18446744073709551614`).

This issue very likely exists in `turtle-service` as well; however, as the transactions above are not **mine** they do not show up in my wallet and thus I cannot confirm. As this is a serialization error, the error likely exists across the project.

#### Impact

The node (daemon) handles the correct value of the `unlock_time` appropriately; however, as a result of the serialization error, wallets *may* not recognize the `unlock_time` of the transaction properly. While this would *normally* be an issue, the correct values (`18446744073709551614`) are interpreted by the network according to the rules as outlined in §3.4 of [CNS004: Cryptonote Transactions](https://cryptonote.org/cns/cns004.txt)

```
   Creating a transaction, the sender specifies the unlock_time. If this
   value is less than CRYPTONOTE_MAX_BLOCK_NUMBER (500000000), then it
   is interpreted as the block height at which the funds are unlocked.
   Otherwise, the value is interpreted as the UNIX timestamp.

   unlock_time is used as a way to temporarily lock the funds.
   Precisely, each output can only be spent (or referenced by an input,
   even if it is not really spent) after the unlock_time elapses. Until
   then these funds are considered locked and non-spendable.
```

Given that the value (`18446744073709551614`) exceeds [CRYPTONOTE_MAX_BLOCK_NUMBER](https://github.com/turtlecoin/turtlecoin/blob/aa0314217efc4c66481f0cf8b6caa21f6ddfb49b/src/config/CryptoNoteConfig.h#L21) this value is interpreted as a unix timestamp. The result is that these transactions will unlock on or around:

`12/04/292277026596 @ 3:30pm (UTC)`

Yeah, you read that right, in the year two hundred ninety-two billion, two hundred seventy-seven million, twenty-six thousand, five hundred ninety-six 👋 

##### Screen Shots

Sample data shortened for brevity:

```javascript
{
  "status": "OK",
  "transactions": [
    {
      "blockHash": "b412b7d72fe08bfe8d8e983cc728c6f3d219429c98d12e6643de89bb6d03d2de",
      "blockIndex": 88269,
      "extra": {},
      "fee": 10,
      "hash": "b01a22c8d729acd78adb23a1f1ac1ca2c2b071ab55f38aeb01ba6949a07c3502",
      "inBlockchain": true,
      "inputs": [],
      "mixin": 5,
      "outputs": [],
      "paymentId": "cad826dac837aa45954bd48e66173f0cf6ff653e42055855b88ccb34d074324a",
      "signatures": [],
      "signaturesSize": 1,
      "size": 550,
      "timestamp": 1515531707,
      "totalInputsAmount": 1000,
      "totalOutputsAmount": 990,
      "unlockTime": -2
    },
    {
      "blockHash": "62de62dbae8fa7edd11de66b668071fc2f2ed065000ec655c3f239fd06e891ec",
      "blockIndex": 93405,
      "extra": {},
      "fee": 100,
      "hash": "ec54aeb57a15cf1387f15c3af6c52bb7ae5808ac4348421713a740e77bc2222f",
      "inBlockchain": true,
      "inputs": [],
      "mixin": 1,
      "outputs": [],
      "paymentId": "ca33a08ece81f33535711936f2b215712b4afa2ea73a473157a8082522eee73d",
      "signatures": [],
      "signaturesSize": 1,
      "size": 362,
      "timestamp": 1515691191,
      "totalInputsAmount": 1000000,
      "totalOutputsAmount": 999900,
      "unlockTime": -2
    },
    {
      "blockHash": "bb67b6ff2e919749854a192728285cbf475c3a1189fa122dde61388df3b7ad2d",
      "blockIndex": 93481,
      "extra": {},
      "fee": 100,
      "hash": "f8f1229b41b0ef04b33e3e74557f0ed66ba8fcb54657b01c0dd64679c9247dff",
      "inBlockchain": true,
      "inputs": [],
      "mixin": 1,
      "outputs": [],
      "paymentId": "6d4ca8733a47606c00d0dd3082b9f7bcd6cfff4b3e2e5dd8a0b6aca6b4747ace",
      "signatures": [],
      "signaturesSize": 1,
      "size": 326,
      "timestamp": 1515693654,
      "totalInputsAmount": 100000,
      "totalOutputsAmount": 99900,
      "unlockTime": -2
    }
  ]
}
```

#### Steps to Reproduce

1. Request transaction details via one of the following methods for the above transaction hashes:
a. **f_transaction_json**
b. **queryblockslite**
c. **get_block_details_by_height**
d. **get_blocks_details_by_heights**
e. **get_blocks_details_by_hashes**
f. **get_blocks_hashes_by_timestamps**
g. **get_transaction_details_by_hashes**
2. Send a transaction with a very large `unlock_time` value and examine the outputs of the following RPC commands:
a. **get_pool_changes**
b. **get_pool_changes_lite**

#### Possible Solution

1. Replace the serialization library used for RPC services with a library that can properly serialize the `uint64_t` value.
2. Extend and/or repair the current serialization library such that it properly encodes a `uint64_t` value

@zpalmtree can provide a link to the area of the serialization library which is likely the cause for this issue.

This issue is being opened for tracking and full disclosure purposes.

**Comment by zpalmtree** [comment]
I believe the cause for this serialization error is here: https://github.com/turtlecoin/turtlecoin/blob/development/src/Common/JsonValue.h#L34

\- A uint64_t is serialized as an int64_t

**Comment by brandonlehmann** [comment]
Thanks @zpalmtree

**Comment by ngeojiajun** [comment]
Is it possible to fix by change in the directly to uint64? Or we should apply special serialization for uint64 such as prefixing it using + sign etc?

**Comment by zpalmtree** [comment]
@ngeojiajun We can't just change int64_t to uint64_t, otherwise serialization of signed stuff wouldn't work. It *might* be possible to just add uint64_t support to the serialization, but it looked like a lot of places it needed changing.

**Comment by ngeojiajun** [comment]
I will attempt to work on it

**Comment by ngeojiajun** [comment]
@zpalmtree but the deserialization code seems like reject negative value `for (;;) {
    int i = in.peek();
    if (i >= '0' && i <= '9') {
      in.read(&c, 1);
      text += c;
    } else  if (i == '.') {
      in.read(&c, 1);
      text += '.';
      ++dots;
    } else {
      break;
    }
  }`

**Comment by brandonlehmann** [comment]
No, it’s not. Adding a plus in front of positive numbers is not the correct method. 

Also, if you read the issue closely, it lists testing in the RPC calls which is required. 

The expected behavior is to serialize uint64_t properly.

**Comment by ngeojiajun** [comment]
But how we can differentiate the signed and unsigned when it is being deserialized?

**Comment by brandonlehmann** [comment]
JavaScript and thus JSON has no concept of unsigned or signed. A number is a number. Unsigned numbers are “supported” in JavaScript using different handling methods. 

Prefixing a plus sign is not the right way to handle this by any means. 

All that needs fixed is that the uint64t needs properly dumped to a numeric form without a plus sign in front.

**Comment by brandonlehmann** [comment]
So here's the tough question, as there is no number in JS that's bit enough to handle a uint64_t... do we encode the numeric value it as a string... or varint encode it as a string?
