### ISSUE TITLE
Resource temporary unavailable

### ISSUE THREAD

**Issue by quantumproducer** [turtlecoin/turtlecoin#612]
### System Information

**Operating System**: OSX
**OS Version**: 10.13.6
**CPU Make, Model, & Speed**: 2.6 intel i7
**Amount of RAM**: 16GB 
**Hard Drive Type**: SSD
**Hard Drive Size**: 1TB
**Volume Type**: NTFS

### TurtleCoin Build Information

I downloaded the latest mac release. I ran TurtleCoinD, got this

```
 TurtleCoin v0.10.0.1279 ()
 This software is distributed under the General Public License v3.0

 Copyright 2018, The TurtleCoin Developers

 Additional Copyright(s) may apply, please see the included LICENSE file for more information.
 If you did not receive a copy of the LICENSE, please visit:
 https://github.com/turtlecoin/turtlecoin/blob/master/LICENSE


2018-Nov-21 09:04:55.886832 INFO    Program Working Directory: ./TurtleCoind
2018-Nov-21 09:04:55.886979 INFO    Loading Checkpoints for faster initial sync...
2018-Nov-21 09:04:55.887127 INFO    Loaded 187 default checkpoints
2018-Nov-21 09:04:55.887232 INFO    Opening DB in /Users/quantum/.TurtleCoin/DB
2018-Nov-21 09:04:55.888575 ERROR   DB Error. DB can't be opened in /Users/quantum/.TurtleCoin/DB. Error: IO error: While lock file: /Users/quantum/.TurtleCoin/DB/LOCK: Resource temporarily unavailable
2018-Nov-21 09:04:55.888746 ERROR   Exception: IO error
```

**Comment by brandonlehmann** [comment]
This typically has to do with system limits regarding the number of open files.

Please provide the output of the following commands on your system:

`sysctl -a | grep maxproc | grep =`
`ulimit -u`

**Comment by quantumproducer** [comment]
```
ulimit -u
1418
```

I tried running again, I get "Segmentation Fault 11". Is there an error log I can paste?

**Comment by brandonlehmann** [comment]
Did you run both of the commands?

**Comment by brandonlehmann** [comment]
You can’t run the miner pointed at the local daemon if the local daemon isn’t running and fully synced. 

Please run the other command I asked about and post the results:

sysctl -a | grep maxproc | grep =

**Comment by quantumproducer** [comment]
```
~/sysctl -a | grep maxproc | grep =
~/ulimit -u
1418
~/
```

**Comment by quantumproducer** [comment]
```
sysctl -a | grep maxproc
kern.maxproc: 2128
kern.maxprocperuid: 1418
```

**Comment by brandonlehmann** [comment]
This is related to #617
