### ISSUE TITLE
Turtule POW V8 / What about?

### ISSUE THREAD

**Issue by Desmond168** [turtlecoin/turtlecoin#629]
What about this encasement in future? Any movements?
The hashrate is really unusual.
It's very possible from new ASIC Machine, I guess.

**Comment by zpalmtree** [comment]
The hashpower may be coming from merged mining, or FPGA's, who knows. Either way, we have a hard fork prepared. See https://github.com/turtlecoin/turtlecoin/tree/cn_turtle

**Comment by caokun320** [comment]
i know ASIC mining this coin.

**Comment by zpalmtree** [comment]
Do you have a source on that claim?

**Comment by brandonlehmann** [comment]
Please see the issue https://github.com/turtlecoin/meta/issues/74 on the meta repo
