### ISSUE TITLE
TurtleCoind.exe does not have a "save" command

### ISSUE THREAD

**Issue by themolco** [turtlecoin/turtlecoin#63]
In 0.3.2, TurtleCoind.exe (Windows 10) opens after sync with this line:
` Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.`

There is, however, no "save" command:
`Unknown command: save `

It does save on exit, obviously.

**Comment by ereptor81** [comment]
This was fixed in a recent commit and should be in the next release:  https://github.com/turtlecoin/turtlecoin/commit/4fe68e2242b73efb50a47340a83729027f28015c

**Comment by themolco** [comment]
will close. thanks for the link.
