### ISSUE TITLE
When 

### ISSUE THREAD

**Issue by hehanbo1990** [turtlecoin/turtlecoin#682]
![image](https://user-images.githubusercontent.com/6762674/50840026-8ba23480-139c-11e9-893b-35e534615ba1.png)

1.latest TurtleCoin-Nest-0.36-Mac.zip
2.In the page showing your seed after registration, click OK and nothing happen just stay there
3.MAC OS Sierra 10.12.6 (16G1618)

**Comment by brandonlehmann** [comment]
Thanks @hehanbo1990. I've moved this issue over to the proper project at https://github.com/turtlecoin/turtle-wallet-go/issues/53
