### ISSUE TITLE
can't compile WINDOWS 10

### ISSUE THREAD

**Issue by WIKAD** [turtlecoin/turtlecoin#691]
Native arch: FALSE
-- Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
-- Compiler options: /FI"winapifamily.h"
-- Compiler definitions: CRYPTOPP_DISABLE_SSSE3;CRYPTOPP_DISABLE_SSSE4;_WIN32_WINNT=0x0A00
-- Build type: Release
-- GFLAGS library is disabled
-- SNAPPY library is disabled
-- LZ4 library is disabled
-- ZLIB library is disabled
-- XPRESS is disabled
-- ZSTD library is disabled
-- JEMALLOC library is disabled
-- Enabling RTTI in Debug builds only (default)
-- JNI library is disabled
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory C:/turtlecoin
   used as include directory in directory C:/turtlecoin
   used as include directory in directory C:/turtlecoin/external
   used as include directory in directory C:/turtlecoin/external/miniupnpc
   used as include directory in directory C:/turtlecoin/external/miniupnpc
   used as include directory in directory C:/turtlecoin/external/cryptopp
   used as include directory in directory C:/turtlecoin/external/cryptopp
   used as include directory in directory C:/turtlecoin/external/cryptopp
   used as include directory in directory C:/turtlecoin/external/cryptopp
   used as include directory in directory C:/turtlecoin/external/rocksdb
   used as include directory in directory C:/turtlecoin/external/rocksdb
   used as include directory in directory C:/turtlecoin/external/rocksdb
   used as include directory in directory C:/turtlecoin/external/rocksdb
   used as include directory in directory C:/turtlecoin/external/rocksdb/third-party/gtest-1.7.0/fused-src/gtest
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src
   used as include directory in directory C:/turtlecoin/src

**Comment by zpalmtree** [comment]
Is boost installed? What download link did you use? What cmake command did you use? Where is boost located?

**Comment by WIKAD** [comment]
boost is located in c:\boost_1_68_0
commands ? i just copy & pasted the "tutorial build on windows" commands

**Comment by zpalmtree** [comment]
You need to change
```
cmake -G "Visual Studio 15 2017 Win64" .. -DBOOST_ROOT=C:/local/boost_1_68_0
```
to
```
cmake -G "Visual Studio 15 2017 Win64" .. -DBOOST_ROOT=C:/boost_1_68_0
```
then

**Comment by zpalmtree** [comment]
As per the instructions:

> If you have errors on this step about not being able to find the following static libraries, you may need to update your cmake. Open 'Visual Studio Installer' and click 'Update'.

**Comment by zpalmtree** [comment]
That said, your cmake does look new enough.

**Comment by WIKAD** [comment]
Visual Studio Installer is up to date

can't finde the issue :-/

**Comment by WIKAD** [comment]
damn you are my hero !!!!!!
it works !!

just compiling  ( i see some red text, but i think its normal )
