### ISSUE TITLE
Daemon had corrupted blockchain 2 times during last 2 days on v0.12.0 on different servers

### ISSUE THREAD

**Issue by minerrocks** [turtlecoin/turtlecoin#694]
Daemons stopped working periodically on different servers/public cloud instances/, and then failed to start, giving logs:
```
2019-Jan-17 13:22:18.073971 INFO    [Core] Importing blocks from blockchain storage
2019-Jan-17 13:22:18.084632 ERROR   [Core] Corrupted blockchain. Block with index 1152103 and hash 77e0f0b7ff661854f238460f15fd95052c3765e145ceea735fab68d7abb01fee has previous block hash 3c1f4bea6df864466c47b4f273bddf35c5ef28cb1dd61af487ef0d362566b083, but parent has hash 0838b65872c658a7f3867ba90c67f5356e4f538d67dcd73c1f7f8c300f505568. Resynchronize your daemon please.
2019-Jan-17 13:22:18.152946 INFO    [RocksDBWrapper] Closing DB.
2019-Jan-17 13:22:18.161456 ERROR   [daemon] Exception: Blockchain storage is corrupted
```

### System Information

**Operating System**: Ubuntu
**OS Version**: 16.04
**CPU Make, Model, & Speed**: Intel Xeon Processor (Skylake, IBRS) 2100 MHz
**Amount of RAM**: 8 Gb
**Hard Drive Type**: Attached volume (public cloud)
**Hard Drive Size**: 80 Gb
**Volume Type**: ext4

### TurtleCoin Build Information

**Version:** 0.12.0.1280
**Binary Source:** precompiled -> https://github.com/turtlecoin/turtlecoin/releases/download/v0.12.0/turtlecoin-v0.12.0-linux.tar.gz

### Issue Report

**Binary Reported:** TurtleCoind

#### Expected Behavior

Daemon started and running fine.

#### Current Behavior

1) Daemon failed to start, giving logs:
```
2019-Jan-17 13:22:18.073971 INFO    [Core] Importing blocks from blockchain storage
2019-Jan-17 13:22:18.084632 ERROR   [Core] Corrupted blockchain. Block with index 1152103 and hash 77e0f0b7ff661854f238460f15fd95052c3765e145ceea735fab68d7abb01fee has previous block hash 3c1f4bea6df864466c47b4f273bddf35c5ef28cb1dd61af487ef0d362566b083, but parent has hash 0838b65872c658a7f3867ba90c67f5356e4f538d67dcd73c1f7f8c300f505568. Resynchronize your daemon please.
2019-Jan-17 13:22:18.152946 INFO    [RocksDBWrapper] Closing DB.
2019-Jan-17 13:22:18.161456 ERROR   [daemon] Exception: Blockchain storage is corrupted
```

#### Steps to Reproduce

1. Run the daemon for some time, for example using Hetzner public cloud with attached volume.

#### Possible Solution

Only advices:
1. Automatically pop some blocks and try to sync again.
2. Provide ability to pop some blocks manually - so resync from scratch will not be needed, as it takes several hours each time.

**Comment by brandonlehmann** [comment]
Is that mounted volume SSD? Platter based? Hybrid?

What's your I/O throughput to the volume look like?

Generally speaking, `Blockchain storage is corrupted` is due to the daemon being force-ably killed while it's trying to shut down. Do you have something else attempting to control or otherwise handle the daemon?

**Comment by minerrocks** [comment]
> Is that mounted volume SSD? Platter based? Hybrid?

It is Hetzner cloud volume - It is SSD, but how its attached, by network, or physically i do not have info.

Daemon running as systemctl service, with `Type=simple`
When Turtled stucked at specific height for hours - i restarted it via systemctl.

Stucked daemon before restart logs:
```
2019-Jan-17 16:41:01.590497 INFO    [protocol] New Top Block Detected: 1157281
2019-Jan-17 16:41:14.646875 INFO    [protocol] [104.129.6.214:57053 INC] Successfully synchronized with the TurtleCoin Network.
2019-Jan-17 16:41:34.552526 INFO    [protocol] New Top Block Detected: 1157282
2019-Jan-17 16:41:35.313749 INFO    [protocol] [94.130.68.62:63951 INC] Your TurtleCoin node is syncing with the network (99.99% complete) You are 1 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the ra
... some time passed ...
2019-Jan-17 23:01:38.361664 INFO    [protocol] New Top Block Detected: 1158044
2019-Jan-17 23:01:41.268732 INFO    [protocol] [94.130.68.62:52961 INC] Your TurtleCoin node is syncing with the network (99.93% complete) You are 763 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the
... asked to restart via systemctl ...
2019-Jan-17 23:01:46.635574 INFO    [node_server] Stop signal sent, please only EXIT or CTRL+C one time to avoid stalling the shutdown process.
2019-Jan-17 23:01:46.635830 INFO    [node_server] Stopping NodeServer and its 7 connections...
2019-Jan-17 23:01:47.652601 INFO    [node_server] NodeServer loop stopped
2019-Jan-17 23:01:47.653565 INFO    [daemon] p2p net loop stopped
2019-Jan-17 23:01:47.654219 INFO    [daemon] Stopping core rpc server...
2019-Jan-17 23:01:47.654936 INFO    [daemon] Deinitializing p2p...
2019-Jan-17 23:01:48.056520 INFO    [daemon]


████████╗██╗  ██╗██████╗ ████████╗██╗    ██████╗ █████╗ █████╗ ██╗███╗   ██╗
╚══██╔══╝██║  ██║██╔══██╗╚══██╔══╝██║    ██╔═══╝██╔═══╝██╔══██╗██║████╗  ██║
   ██║   ██║  ██║██████╔╝   ██║   ██║    ████╗  ██║    ██║  ██║██║██╔██╗ ██║
   ██║   ██║  ██║██╔══██╗   ██║   ██║    ██╔═╝  ██║    ██║  ██║██║██║╚██╗██║
   ██║   ╚█████╔╝██║  ██║   ██║   ██████╗██████╗╚█████╗╚█████╔╝██║██║ ╚████║
   ╚═╝    ╚════╝ ╚═╝  ╚═╝   ╚═╝   ╚═════╝╚═════╝ ╚════╝ ╚════╝ ╚═╝╚═╝  ╚═══╝
```

After that it can not start anymore with `Blockchain storage is corrupted`.

IO stats from:
https://www.lowendtalk.com/discussion/152858/hetzner-cloud-additional-volumes
```
I/O speed(1st run)   : 304 MB/s
I/O speed(2nd run)   : 178 MB/s
I/O speed(3rd run)   : 178 MB/s
Average I/O speed    : 220.0 MB/s
```

**Comment by brandonlehmann** [comment]
What signal is sent for the restart? Or does it just get killed?

**Comment by bobbieltd** [comment]
For info :
Seriously ? Issue template now 😂. SSD or HDD or USB Key, hardwares, ... are irrelevant with corruption.
3 daemons died like this. One died by itself (no restarting or whatever touches). Two died after some restarts.
It is not rocksdb issue. I deleted DB and reimported blockchain unsuccessfully.
With error message like this, “corruption” is not sure. I guess it put wrong hash from wrong chan and can not pop blocks like Monero forks by itself. Auto pop blocks is good feature for daemons.

**Comment by brandonlehmann** [comment]
Hi @bobbieltd thanks for the **constructive** feedback. 

The type of storage, the I/O contention and other hardware is VERY related to this error. You're absolutely right that the isn't with RocksDB, it's with the .bin files which are *heavily affected by I/O contention*

Perhaps you'd like to take a look at https://github.com/turtlecoin/turtlecoin/blob/development/src/CryptoNoteCore/SwappedVector.h and submit a PR that will allow you to "pop blocks like Monero" and "auto pop blocks".

Myself, others, and I'm sure @minerrocks would appreciate the effort.

**Comment by minerrocks** [comment]
> 
> 
> What signal is sent for the restart? Or does it just get killed?

Default behavior of systemd used `SIGTERM` adn in 60 seconds `SIGKILL`. 
Logs shows that daemon got the signal to stop, and was closed gracefully:
```
2019-Jan-17 23:01:46.635574 INFO    [node_server] Stop signal sent, please only EXIT or CTRL+C one time to avoid stalling the shutdown process.
2019-Jan-17 23:01:46.635830 INFO    [node_server] Stopping NodeServer and its 7 connections...
2019-Jan-17 23:01:47.652601 INFO    [node_server] NodeServer loop stopped
2019-Jan-17 23:01:47.653565 INFO    [daemon] p2p net loop stopped
2019-Jan-17 23:01:47.654219 INFO    [daemon] Stopping core rpc server...
2019-Jan-17 23:01:47.654936 INFO    [daemon] Deinitializing p2p...
... and here it was started back ...
2019-Jan-17 23:01:48.056520 INFO    [daemon]
```

**Comment by brandonlehmann** [comment]
@minerrocks

Can you run the latest dev build? It will dump additional logs at daemon shut down that will give additional information on what’s going on.

**Comment by brandonlehmann** [comment]
Any updates?

**Comment by minerrocks** [comment]
no problems so far

**Comment by bobbieltd** [comment]
Chain is spliting now. Not much info at log. This behaviour is common at DeroGold (same codebase).

2019-Feb-25 13:46:54.222373 INFO    [protocol] [89.234.182.12:11897 OUT] Your TurtleCoin node is syncing with the network (99.99% complete) You are 8 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race!
2019-Feb-25 13:46:56.718719 INFO    [protocol] [128.199.184.104:11897 OUT] Your TurtleCoin node is syncing with the network (99.99% complete) You are 6 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race!
2019-Feb-25 13:47:10.716143 INFO    [protocol] [104.129.6.214:12897 OUT] Your TurtleCoin node is syncing with the network (99.99% complete) You are 9 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race!
2019-Feb-25 13:47:10.716273 INFO    [protocol] New Top Block Detected: 1268693
2019-Feb-25 13:47:16.903395 INFO    [protocol] [128.199.184.104:11897 OUT] Your TurtleCoin node is syncing with the network (99.99% complete) You are 6 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race!
2019-Feb-25 13:47:19.145877 INFO    [protocol] [88.130.0.223:11897 OUT] Your TurtleCoin node is syncing with the network (99.99% complete) You are 4 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race!
2019-Feb-25 13:47:19.934653 INFO    [protocol] [89.234.182.12:11897 OUT] Your TurtleCoin node is syncing with the network (99.99% complete) You are 9 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race!
2019-Feb-25 13:47:29.442295 INFO    [daemon]


████████╗██╗  ██╗██████╗ ████████╗██╗    ██████╗ █████╗ █████╗ ██╗███╗   ██╗
╚══██╔══╝██║  ██║██╔══██╗╚══██╔══╝██║    ██╔═══╝██╔═══╝██╔══██╗██║████╗  ██║
   ██║   ██║  ██║██████╔╝   ██║   ██║    ████╗  ██║    ██║  ██║██║██╔██╗ ██║
   ██║   ██║  ██║██╔══██╗   ██║   ██║    ██╔═╝  ██║    ██║  ██║██║██║╚██╗██║
   ██║   ╚█████╔╝██║  ██║   ██║   ██████╗██████╗╚█████╗╚█████╔╝██║██║ ╚████║
   ╚═╝    ╚════╝ ╚═╝  ╚═╝   ╚═╝   ╚═════╝╚═════╝ ╚════╝ ╚════╝ ╚═╝╚═╝  ╚═══╝

 TurtleCoin v0.12.1.1281 ()
 This software is distributed under the General Public License v3.0

 Copyright 2018, The TurtleCoin Developers

 Additional Copyright(s) may apply, please see the included LICENSE file for more information.
 If you did not receive a copy of the LICENSE, please visit:
 https://github.com/turtlecoin/turtlecoin/blob/master/LICENSE


2019-Feb-25 13:47:29.442780 INFO    [daemon] Program Working Directory: "/"
2019-Feb-25 13:47:29.442932 INFO    [daemon] Loading Checkpoints for faster initial sync...
2019-Feb-25 13:47:29.443076 INFO    [daemon] Loaded 222 default checkpoints
2019-Feb-25 13:47:29.443182 INFO    [RocksDBWrapper] Opening DB in /home/turtlecoindaemon/.TurtleCoin/DB
2019-Feb-25 13:47:29.525656 INFO    [RocksDBWrapper] DB opened in /home/turtlecoindaemon/.TurtleCoin/DB
2019-Feb-25 13:47:29.526241 INFO    [daemon] Initializing core...
2019-Feb-25 13:47:29.570632 INFO    [Core] Importing blocks from blockchain storage
2019-Feb-25 13:47:33.655214 ERROR   [Core] Corrupted blockchain. Block with index 1268643 and hash ccaba96030dec598219c2fe4a1775c3415449b654731e19e3b884e015a6aeb55 has previous block hash 065687bc6168d1ac78e2c81bb7c75cbff9e992ee798e3f727b275c5ded0dcc3b, but parent has hash 8c706f6d6fae7357941a1a6171d68891aea8a83219aa51a206ceb709e70e2fd1. Resynchronize your daemon please.
2019-Feb-25 13:47:33.656154 INFO    [RocksDBWrapper] Closing DB.
2019-Feb-25 13:47:34.644989 ERROR   [daemon] Exception: Blockchain storage is corrupted
2019-Feb-25 13:47:35.683215 INFO    [daemon]

**Comment by brandonlehmann** [comment]
Network is under extremely heavy load. You may experience issues if your node is not shut down correctly. Update is forthcoming to help deal with the issue.

**Comment by cryptosven76** [comment]
i have the same issue and it blows up at the exact same block : 

2019-Feb-28 21:31:05.445326 INFO    Program Working Directory: "/home/crypt/binaries/turtlecoin/build"
2019-Feb-28 21:31:05.445539 INFO    Loading Checkpoints for faster initial sync...
2019-Feb-28 21:31:05.445756 INFO    Loaded 255 default checkpoints
2019-Feb-28 21:31:05.445889 INFO    Opening DB in /root/.TurtleCoin/DB
2019-Feb-28 21:31:05.499174 INFO    DB opened in /root/.TurtleCoin/DB
2019-Feb-28 21:31:05.501334 INFO    Initializing core...
2019-Feb-28 21:31:05.579569 INFO    Importing blocks from blockchain storage
2019-Feb-28 21:31:05.603061 ERROR   Corrupted blockchain. Block with index 1268643 and hash ccaba96030dec598219c2fe4a1775c3415449b654731e19e3b884e015a6aeb55 has previous block hash 065687bc6168d1ac78e2c81bb7c75cbff9e992ee798e3f727b275c5ded0dcc3b, but parent has hash 8c706f6d6fae7357941a1a6171d68891aea8a83219aa51a206ceb709e70e2fd1. Resynchronize your daemon please.
2019-Feb-28 21:31:05.604750 INFO    Closing DB.
2019-Feb-28 21:31:05.618856 ERROR   Exception: Blockchain storage is corrupted
2019-Feb-28 21:31:05.636851 INFO

i did sync twice from scratch and it fails with the same error

**Comment by brandonlehmann** [comment]
You might want to look at using checkpoints to sync a bit faster.

**Comment by cryptosven76** [comment]
but how does that help with getting over the corruption ?

**Comment by brandonlehmann** [comment]
You'll still have to resync. At this point you have no choice but to resync. Might as well use checkpoints to speed it up.

**Comment by cryptosven76** [comment]
i am already using checkpoints, the question is how can we help get to the bottom of the corruption ?

**Comment by brandonlehmann** [comment]
Your log above shows that you're using the inbuilt checkpoints

2019-Feb-28 21:31:05.445756 INFO Loaded 255 default checkpoints

You'll want to use the full checkpoints at https://github.com/turtlecoin/checkpoints/blob/master/checkpoints.csv

The network was under very heavy load a few days ago and it's very likely to cause corruption for smaller systems when trying to validate blocks. Full checkpoints generally allow smaller systems to work through the data without further issue.

**Comment by cryptosven76** [comment]
sorry i should have been more precise, i usually synchronize with checkpoints but after my DB got corrupted AND a 2nd attempt to sync failed i did a 3rd sync without checkpoints. i didn't post the former outputs but only the last one. i am syncing now again with checkpoints : 
2019-Feb-28 22:06:39.049468 INFO    Loading Checkpoints for faster initial sync...
2019-Feb-28 22:06:40.013303 INFO    Loaded 1238704 checkpoints from /root/.TurtleCoin/checkpoints.csv
2019-Feb-28 22:06:40.013546 INFO    Opening DB in /root/.TurtleCoin/DB
2019-Feb-28 22:06:40.015153 INFO    DB not found in /root/.TurtleCoin/DB. Creating new DB...
2019-Feb-28 22:06:40.063231 INFO    Initializing core...

thx

**Comment by cryptosven76** [comment]
and as i assumed this has nothing to do with checkpoint syncing, there is some real issue : 

2019-Mar-01 01:19:44.804044 INFO    Imported block with index 1264000 / 1270628
2019-Mar-01 01:20:09.303528 INFO    Imported block with index 1265000 / 1270628
2019-Mar-01 01:20:48.737786 INFO    Imported block with index 1266000 / 1270628
2019-Mar-01 01:21:45.597002 INFO    Imported block with index 1267000 / 1270628
2019-Mar-01 01:22:32.944850 INFO    Imported block with index 1268000 / 1270628
2019-Mar-01 01:22:59.895544 ERROR   Corrupted blockchain. Block with index 1268643 and hash ccaba96030dec598219c2fe4a1775c3415449b654731e19e3b884e015a6aeb55 has previous block hash 065687bc6168d1ac78e2c81bb7c75cbff9e992ee798e3f727b275c5ded0dcc3b, but parent has hash 8c706f6d6fae7357941a1a6171d68891aea8a83219aa51a206ceb709e70e2fd1. Resynchronize your daemon please.
2019-Mar-01 01:23:07.770851 INFO    Closing DB.
2019-Mar-01 01:23:37.597219 ERROR   Exception: Blockchain storage is corrupted
root@turtlecoin:/home/crypt/binaries/turtlecoin/build#

can somebody please let me know what debug informations are required to fix this ?

**Comment by zpalmtree** [comment]
>Imported block with index 1264000 / 1270628
Looks like you're importing from the .bin files, instead of resyncing the whole chain. You need to delete the *whole* TurtleCoin folder, otherwise it will keep reimporting from the same, corrupted, files.

**Comment by cryptosven76** [comment]
that maybe the case, let me wipe everything and try checkpoint sync again.
thanks

**Comment by bobbieltd** [comment]
Is there Turtlecoin dev funding system (for bug bouties, new feature implementation,....) ? What is the address ?
I do not see it in Readme or Google. (Don’t tell me to join Discord, I’m not active in others’ Discord).

**Comment by brandonlehmann** [comment]
@bobbieltd the current bounty system is available on discord but you don’t have to join :)

**Comment by cryptosven76** [comment]
@zpalmtree that worked . thanks
