### ISSUE TITLE
Daemon+WalletBackend timestamp adjustments

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#704]
The current /getwalletsyncdata rounds a timestamp to midnight. Depending on what time of the day you start a fresh wallet, you may have no blocks to grab (we need to roll back a bit more than we currently do with the timestamp adjustment), or too many (since it's rounding to midnight which is quite far away).

We should instead just respect the timestamp given, and have a better adjust so we always sync about 100 or so blocks to be safe.

Might require a bit of work, since the timestamp fetching routines I believe hit the two DB caches, which aren't the most fun to work with.

**Comment by zpalmtree** [comment]
Something seriously wrong with this method... converting a timestamp of `1512840544` to a height of `1602960`...

**Comment by ngeojiajun** [comment]
is it ok to just remove the call to roundToMidnight(timestamp) at databaseblockchaincache.cpp#1710?

**Comment by zpalmtree** [comment]
There is also the in memory cache that needs altering. That might fix it, but I'm not sure what other methods need the roundToMidnight - so may be a good idea to dupe the call and just update getWalletSyncData to use the new call instead to prevent breaking anything which relies on the `roundToMidnight` call

**Comment by ngeojiajun** [comment]
the method cannot be removed safely as it was referenced in some critical functions such as DatabaseBlockchainCache::pushBlock.

**Comment by brandonlehmann** [comment]
Re-opening as #933 is being reverted.

**Comment by brandonlehmann** [comment]
Copying from revert thread

> The DatabaseBlockchainCache is created as a node syncs. As this was previously rounding this to midnight, the only indexes that exist are those that are rounded to midnight. #933 had stopped rounding to midnight and thus is passing the straight timestamp in for reading. Unfortunately, there is no index that matches this position in the past and thus we fail to actually get a response to this call and thus breaks a few of the different RPC calls that rely on getClosestTimestampBlockIndex(). While it may not be ideal that the rounding occurs to midnight forcing a resync to rebuild that state data isn't necessarily a good idea either.

**Comment by zpalmtree** [comment]
So.. do we instead use a different method in /getwalletsyncdata and /getrawblocks instead of touching this one? Not sure if that's possible on the codepath we take.

**Comment by brandonlehmann** [comment]
All paths other than rounding to midnight are going to require a full resync because the indexes won't exist in previous sync data. Keeping that in mind, we could proceed however we want **if** we are okay forcing a resync. Otherwise, we're kind of stuck.

**Comment by zpalmtree** [comment]
I'm not sure I follow, because the patch as it stands seems to work fine for /getwalletsyncdata, it's just /getliteblocks which breaks, no?

**Comment by brandonlehmann** [comment]
When i tested before reverting, getwalletsyncdata was also causing it to trip -- with the a deep timestamp.

**Comment by zpalmtree** [comment]
OK

**Comment by brandonlehmann** [comment]
Im going to close this issue as (a) its staleness; and, (b) the fact it’s been open for 18 months; and, (c) it’s going to require a full resync to implement; and, (d) it’s *nice* to speed up wallet sync a wee bit but the return for doing all this is negligible in my opinion. 

If anyone objects, feel free to comment or re-open.
