### ISSUE TITLE
Add https support to cpp-httplib/nigel

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#713]
It looks pretty easy to add SSL support to Nigel and thus wallet-api and zedwallet-beta.
https://github.com/yhirose/cpp-httplib#openssl-support

Relevant code: https://github.com/turtlecoin/turtlecoin/blob/development/src/Nigel/Nigel.cpp#L62

Currently, daemon's don't support SSL, unless proxied through something, so I'm not 100% sure on the best way to test this.

Could link into #712, as the blockchain cache API *does* support SSL

**Comment by brandonlehmann** [comment]
I've got this about 75% complete. Assigning to myself.

**Comment by brandonlehmann** [comment]
WIP: https://github.com/turtlecoin/turtlecoin/tree/walletbackend_ssl_support

**Comment by brandonlehmann** [comment]
Will likely be including the dependency and building it at compile time since it’s finiky
