### ISSUE TITLE
Replace all usage of nlohmann::json with rapidjson

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#714]
We recently migrated from nlohmann::json for wallet saving/loading in #706 

Whilst nlohmann::json is very nice to use, it doesn't perform so well with large data sets. It would be nice to replace all usages of nlohmann::json with rapidjson, so we can get rid of another dependency.

It's mainly used in ApiDispatcher, but there are also a few uses in `include/CryptoTypes.h` and make `include/WalletTypes.h`

Edit [@brandonlehmann]: It's also used in turtle-service and the daemon for dumping and/or loading a configuration file.

**Comment by Macroshock** [comment]
Jesus I was replacing all usage of JsonValue with nlohmann::json

Well at least I didnt get very far

**Comment by zpalmtree** [comment]
oof

**Comment by brandonlehmann** [comment]
I feel like an overall win was had here.

**Comment by brandonlehmann** [comment]
> Jesus I was replacing all usage of JsonValue with nlohmann::json
> 
> Well at least I didnt get very far

You, whoever you are, are a saint. While you're at it check out #603 :)

**Comment by Macroshock** [comment]
> You, whoever you are, are a saint. While you're at it check out #603 :)

This is what motivated the removal of JsonValue, the original idea was to implement uint64_t serialization in the JsonValue library but after a while I decided that removing JsonValue was a better idea since nlohmann was already being used in the project.

Well I guess it's time to check this RapidJson thing.

**Comment by brandonlehmann** [comment]
> > You, whoever you are, are a saint. While you're at it check out #603 :)
> 
> This is what motivated the removal of JsonValue, the original idea was to implement uint64_t serialization in the JsonValue library but after a while I decided that removing JsonValue was a better idea since nlohmann was already being used in the project.
> 
> Well I guess it's time to check this RapidJson thing.

Bless your soul weary traveler. Come and be known http://chat.turtlecoin.lol we have cookies

**Comment by zpalmtree** [comment]
Not suggesting we use either of these, just in case anyone is interested in even *more* performance, I found these two:
https://github.com/chadaustin/sajson
https://github.com/lemire/simdjson

**Comment by brandonlehmann** [comment]
Are they actively maintained ?

**Comment by zpalmtree** [comment]
Neither are suitable for our use case, they're just *really* fast. I thought someone might find it interesting. simdjson certainly is - I found it on HN this morning.

**Comment by brandonlehmann** [comment]
Cool

**Comment by brandonlehmann** [comment]
Working on this now.

**Comment by brandonlehmann** [comment]
Handled in #1076
