### ISSUE TITLE
SimpleWallet's "incoming_transfers" does not show transfer time

### ISSUE THREAD

**Issue by woodyjon** [turtlecoin/turtlecoin#72]
The command _incoming_transfers_ of simplewallet lists the amount and tx id of each transfer, but does not show the time of the transfer, which can be useful. The only time shown, for each transfer, is the present time, which is useless (I guess it must come from the logging script).

If you're ok, I can make the improvement and propose a pull request. (please assign to me if ok)

**Comment by ZedPea** [comment]
Added in https://github.com/turtlecoin/turtlecoin/pull/161
