### ISSUE TITLE
LiteBlocks Payload Duplicaton

### ISSUE THREAD

**Issue by michael-herwig** [turtlecoin/turtlecoin#728]
Once a daemon has a missing transaction in a lite block he requests them but does not add the lite block after.

#### Expected Behavior

After a peer sent the missing transactions the lite block gets added to the blockchain and will be propagated through the p2p network.

#### Current Behavior

The transactions will be pushed to the transaction pool.

#### Steps to Reproduce

1. Send a lite block with a transaction not known to another peer.

#### Possible Solution

Cache the lite block in the peer context who published the block and try to add it once the publisher sent missing transactions. You can look at our implementation [here](https://gitlab.com/galaxia-project/blockchain/xi/blob/lite-blocks/src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp#L590).

#### Explanation

Due to the hop increment of other nodes the node which has missed some transactions will not be notified again. Even that it has received the transactions potentially. On the next sync request, the node sees itself behind the network height and start a `NOTIFY_REQUEST_GET_OBJECTS::request` which will send the entire blocks with all transactions again which were just requested.

**Comment by brandonlehmann** [comment]
Thanks again @michael-herwig  We'll work to get the fix incorporated.

**Comment by brandonlehmann** [comment]
See #730
