### ISSUE TITLE
LiteBlocks Alternative Chains Not Resolvable

### ISSUE THREAD

**Issue by michael-herwig** [turtlecoin/turtlecoin#729]
When a daemon receives missing transactions of a lite block they will be tried to push into the transaction pool as the `NOTIFY_NEW_TRANSACTIONS::request` is used. That way alternative blocks may never get fully known as their transactions is invalid on the main chain.

#### Expected Behavior

The knowledge of known transactions is queried from the entire blockchain.

#### Current Behavior

The transactions will only be queried from the transaction pool.

#### Steps to Reproduce

1. Mine a block at a specific height including a transaction.
2. Mine a second block at the previous height with the same transaction.

#### Possible Solution

Query the entire blockchain for transaction hashes in a lite block. Implement a dedicated message type for handling missing transactions from a lite block. You can find our implementation [here](https://gitlab.com/galaxia-project/blockchain/xi/blob/lite-blocks/src/CryptoNoteProtocol/CryptoNoteProtocolHandler.h#L89) and [here](https://gitlab.com/galaxia-project/blockchain/xi/blob/lite-blocks/src/CryptoNoteCore/Core.cpp#L944)

#### Explanation

As the `NOTIFY_NEW_TRANSACTIONS::request` is used the transaction missing will always be pushed to the transaction pool. The transaction may have spent keys or is already mined in the main chain. Thus the lite block will never be able to gather all pieces of information as the transactions will never be available in the pool.

**Comment by brandonlehmann** [comment]
Another good find. Thank you sir!

**Comment by brandonlehmann** [comment]
See #730
