### ISSUE TITLE
add RPC method to validate address

### ISSUE THREAD

**Issue by vladyslavstartsev** [turtlecoin/turtlecoin#733]
Can you please add method to validate public address is right by RPC call.
I mean all the the address that I will give the node should pass all the rules of address.
Similar to 
BTC http://chainquery.com/bitcoin-api/validateaddress
WAVES https://nodes.wavesplatform.com/api-docs/index.html#!/addresses/validate_2
NEO https://github.com/neo-project/docs/blob/master/en-us/node/cli/2.9.3/api/validateaddress.md

**Comment by zpalmtree** [comment]
This would be very easy to add to wallet-api, just need to expose https://github.com/turtlecoin/turtlecoin/blob/development/src/Errors/ValidateParameters.cpp#L280

Probably want to add a parameter to configure whether integrated addresses are allowed, or add that to the response data.
