### ISSUE TITLE
Failed to get genesis block reward in configurated wallet. Bug??

### ISSUE THREAD

**Issue by guile124** [turtlecoin/turtlecoin#738]
I did it exactly step by step as forking guide say, I compile the binary files, wallet created and add this address to the arguments to run daemon, get the hex and replace in the code, recompile in seeds and local machine, but the reward doesnt appear in wallet after mined 100 blocks, in spite of the print_bc 1 shows the reward in first block:

![20190220_132016](https://user-images.githubusercontent.com/37140613/53102018-2c067f80-352b-11e9-8032-456608e6ed8d.jpg)

This is my genesis config:

![20190220_115712](https://user-images.githubusercontent.com/37140613/53102159-6d972a80-352b-11e9-9ff0-6bd2e26f3cfb.jpg)

The getting hex after run daemon with arguments:

![20190220_085817](https://user-images.githubusercontent.com/37140613/53102245-928b9d80-352b-11e9-9538-129744849a65.jpg)

**Comment by brandonlehmann** [comment]
I take it you got it to work?

**Comment by guile124** [comment]
Yes! it works fixing mixing levels, thanos!
