### ISSUE TITLE
TurtleCoind JSON-RPC on_getblockhash returns one block height lower than expected's block hash

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin#745]
### System Information

**Operating System**: Manjaro Linux
**OS Version**: 18.02 
**CPU Make, Model, & Speed**: Intel I7 7700k 4.2ghz
**Amount of RAM**: 16gb
**Hard Drive Type**: SSD
**Hard Drive Size**: 2TB
**Volume Type**: ext4

### TurtleCoin Build Information

**Version:**  TurtleCoin v0.12.1.1281
**Binary Source:** self compiled 
**If self compiled, please provide all the build commands you used**
```
yay turtlecoin-git
```

**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:
```
don't have this at the moment, will recompile and post asap
```

### Issue Report

**Binary Reported:** TurtleCoind

#### Expected Behavior

Calling JSON-RPC method on_getblockhash on a specific block returns the block hash of that specific block.

#### Current Behavior

Calling JSON-RPC method on_getblockhash on a specific block returns the block hash of the block immediately before the requested block, i.e. requesting 1275890 returns block hash for 127589.

##### Log excerpts & Explanation

I am utilizing the turtlecoin-rpc npm package here: https://www.npmjs.com/package/turtlecoin-rpc
and calling `daemon.getBlockHash()`, this example for block 1275890. Here is the call and response:

```
2019-Feb-27 18:54:49.183613 TRACE   JSON-RPC request: {"jsonrpc":"2.0","method":"on_getblockhash","params":[1275890]}
2019-Feb-27 18:54:49.183690 TRACE   JSON-RPC response: {"jsonrpc":"2.0","result":"e3369079381966b705201c09e57a8359e4f272b00351e1cc98038007f2e670f1"}
```
If we look in the explorer, that hash is actually for block 1275889: 
https://explorer.turtlecoin.lol/block.html?hash=e3369079381966b705201c09e57a8359e4f272b00351e1cc98038007f2e670f1

Interestingly, if we go back in the log a few moments prior, we can see the daemon adding that hash as height 1275889:
```
2019-Feb-27 18:54:48.424380 DEBUG   Request to add block 1275889 (e3369079381966b705201c09e57a8359e4f272b00351e1cc98038007f2e670f1)
2019-Feb-27 18:54:48.437464 DEBUG   push block with hash e3369079381966b705201c09e57a8359e4f272b00351e1cc98038007f2e670f1, and 2 transactions
```

I at first thought this might be a bug with the npm package, but it seems like its requesting the correct height according to the daemon logs. I've also tested on a laptop with Windows 10, Ryzen 7, 16gb ram and it exhibits the same behavior.

**Comment by brandonlehmann** [comment]
Off by one. BlockIndex starts at 0, not 1.

**Comment by ExtraHash** [comment]
So this is intentional?

**Comment by brandonlehmann** [comment]
Not so much intentional as there would be a lot of dependencies to update down the chain of resolved. 

Perhaps, this issue would be best addresses in the laundry list of items for API changes and thus a major semver change down the road?
