### ISSUE TITLE
Block Transactions Blob Shuffle

### ISSUE THREAD

**Issue by michael-herwig** [turtlecoin/turtlecoin#748]
Transactions can be shuffled in the block blob to enforce daemons get incompatible chains.

### Expected Behavior

The block header transactions hash array order is checked against the order of the included blobs.

### Current Behavior

The order is not checked such that multiple daemons can retrieve different blobs resulting in different cache states.

### Steps to Reproduce
1. Create a custom daemon shuffling transaction blobs randomly in mined blocks.
2. Create multiple, none published, small transactions with the same amounts and mine them into a block.
3. Send a differently shuffled block to each daemon, will not work using lite blocks.
4. Compute the global indices of the new amounts in the databases of the daemons according to the order they received.
5. Send transactions using these indices such that they are valid on a partial state of received orderings.

### Possible Solution

Check the transaction blobs ordering against the order in the block header. You can see a running example [here](https://gitlab.com/galaxia-project/blockchain/xi/blob/develop/src/CryptoNoteCore/Core.cpp#L718-734)

### Explanation

The transactions pushed to caches are extracted from the blob, see [here](https://github.com/turtlecoin/turtlecoin/blob/development/src/CryptoNoteCore/Core.cpp#L992). As these can have different orders the cache gets a slightly different state. This is then abused to create transactions that are only compatible on chains with a given state by an attacker. This step can then be repeated until most daemons get out of sync with different local information about transactions, mining blocks that are not valid for the others.

**Comment by brandonlehmann** [comment]
The reordering of the transaction hashes in the block blob would result in a different block hash, yes? Therefore won’t the daemon see alternative presentations of the same block as an alternate chain that would ultimately be resolved through further mining on one of the chains (confirmations)? Furthermore, won’t the input signature verification fail if the state of the cache (global indicies of the outputs) don’t match what each local daemon has?

**Comment by michael-herwig** [comment]
Regarding the block hash, I do not think so. The data used for hash calculation is not the entire block and only the block hashing binary array [here](https://github.com/turtlecoin/turtlecoin/blob/development/src/CryptoNoteCore/CachedBlock.cpp#L35). Some lines below [below](https://github.com/turtlecoin/turtlecoin/blob/development/src/CryptoNoteCore/CachedBlock.cpp#L83) you can see the call to [here](https://github.com/turtlecoin/turtlecoin/blob/development/src/CryptoNoteCore/CachedBlock.cpp#L22)) to retrieve the transactions hashes included in the hashing binary array. But this method uses only the block template precomputed transaction hashes. As you are able to send those block templates plus the transaction blobs from the p2p network those data must not be necessarily correct.

That signature case may be true, or you use inputs that are locked or not locked for a global index based on the order they received them.

As the block hashes are the same but actually encode different orders of global indices the chains will not even notice as long these differences are not used. Thus you do not have an alternative chain, you have the same chain with different local caches. Once you resync ie. to another daemon you would retrieve the transactions in the right order and be compatible to him. However, if you use these inputs that are on some daemons/locked or not locked then this block is only valid for a partial part of the daemons and not an alternative block rather an invalid one with locked inputs. Further, you could not switch to them as an alternative chain as the split index already contains the previous blocks with altered transaction orderings. Thus the indexes used on the side chain may still be locked in your local representation of the cache, before the fork.

**Comment by brandonlehmann** [comment]
Interesting. 

The full transaction block is hashed to create the transaction ID that is included in the block template. Altering the transaction blob would change the transaction hash and thus that wouldn’t validate either and thus cause block validation to fail IIRC. (I may be misunderstanding what you’re saying). 

In regards to the signatures, I’m 99% sure that validation would fail as the indicies pull the keys and using the wrong keys (due to an invalid cache state) would cause the ring signature verification to fail and thus the transaction, and ultimately the block, would be rejected. 

This is something I think we will have to check on a testnet.

**Comment by michael-herwig** [comment]
But the indices and the keys are actually identical, they are just from a different transaction, that was also included in the block, just on a different index in the blob. You can reproduce that by running a local testnet with two daemons and mine to one address from one of them, wait for about 20 blocks and use the pgservice to send many small identical transactions. You have to disable light blocks though because I used a map [here](https://github.com/turtlecoin/turtlecoin/blob/development/src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp#L591) to ensure the ordering is correct. Further, you need to shuffle the transaction blob in the block relay method. After one or two accepted blocks with transactions, the daemon with the shuffled blobs should fork but accepted the initial faulty blocks.
