### ISSUE TITLE
Timestamp Locked Input Transactions

### ISSUE THREAD

**Issue by michael-herwig** [turtlecoin/turtlecoin#749]
Transactions with timestamp encoded unlock can be abused to force block creation that is only valid for a partial group of the chain based on their local timestamp.

### Expected Behavior

A block will never contain a transaction which unlocks after the timestamp of the block.

### Current Behavior

The transactions included are based on the local timestamp of the daemon instance.

### Steps to Reproduce
1. Send a lot of small transactions using locked outputs that are close to the current time.

### Possible Solution

Check the transaction unlock timestamp in the fill block template routine against the chosen timestamp that is used for the template. Check if a timestamp locked input is unlocked in a block using the timestamp of that block.

### Explanation

If a block contains transactions with inputs locked on timestamp base the unlock is validated against the local timestamp. But this timestamp is not necessarily the same on all daemons, thus if chosen toxic you can let people mine blocks that are only partially valid in the blockchain.

**Comment by brandonlehmann** [comment]
For clarity: If I understand this correctly you’re referring to a transaction using inputs that are technically still locked due to local time variations?

**Comment by michael-herwig** [comment]
Yes, they are locked on a partial subset of daemons, in the network, having a lower timestamp.

**Comment by brandonlehmann** [comment]
Got it. Thank you.

**Comment by brandonlehmann** [comment]
I've given this a bit more thought to this and I believe we should be validating that the inputs are not currently locked before they even enter the transaction pool. The transaction pool is in essence the first line of defense for preventing invalid transactions. Filtering garbage out of the input side of the pool is better than clogging up the pool and filtering it on the output side IMO.

So, I dug in a bit to follow the rabbit through our transaction checking as this is something that would be a glaring oversight if it's not actually accounted for. I started with finding our references to locked outputs (now inputs) [here](https://github.com/turtlecoin/turtlecoin/blob/2c18d00c4c470066fd18d459d1fdcae72b537423/src/CryptoNoteCore/Core.cpp#L1805) as a result of the call to `extractOutputKeys` [here](https://github.com/turtlecoin/turtlecoin/blob/2c18d00c4c470066fd18d459d1fdcae72b537423/src/CryptoNoteCore/Core.cpp#L1800).

As `validateTransaction` is called in `addBlock` [here](https://github.com/turtlecoin/turtlecoin/blob/2c18d00c4c470066fd18d459d1fdcae72b537423/src/CryptoNoteCore/Core.cpp#L1051) and `isTransactionValidForPool` [here](https://github.com/turtlecoin/turtlecoin/blob/2c18d00c4c470066fd18d459d1fdcae72b537423/src/CryptoNoteCore/Core.cpp#L1445) 

Following that rabbit hole, we're taken into the both BlockchainCache and DatabaseBlockchainCache that ultimate refers to 
https://github.com/turtlecoin/turtlecoin/blob/2c18d00c4c470066fd18d459d1fdcae72b537423/src/CryptoNoteCore/BlockchainCache.cpp#L806

and

https://github.com/turtlecoin/turtlecoin/blob/2c18d00c4c470066fd18d459d1fdcae72b537423/src/CryptoNoteCore/DatabaseBlockchainCache.cpp#L963

Which both refer to `currency.lockedTxAllowedDeltaSeconds()`

Which ultimately leads us to:

https://github.com/turtlecoin/turtlecoin/blob/2c18d00c4c470066fd18d459d1fdcae72b537423/src/config/CryptoNoteConfig.h#L144

Which means that we permit wiggle room of +/- 30s to account for the fact that the network does not have an authoritative (centralized) time source. If you did not want to allow this wiggle room, I believe changing `CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_BLOCKS` to `0` would tighten that up and stop the behavior you've described.

All of the above is true, if I followed the code path correctly. I'd appreciate it if a few people validated or provided an alternate code path.

**Comment by brandonlehmann** [comment]
I guess the question becomes, would invalidating such a transaction for the pool but allowing it for a block make the most sense?

**Comment by michael-herwig** [comment]
Great job, good analysis, in my opinion, I agree on every point. Especially the part about `CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_BLOCKS` thought of removing this part entirely as I cannot think of any advantage and, for me, just makes the algorithm more complicated and looks kinda abusable. Here is how I tried to solve that issue.

I implemented a new transaction pool implementation, thus some parts may not look familiar but I try to explain what their intent is.

First I implemented a new structure called (`Eligible Index`)[https://gitlab.com/galaxia-project/blockchain/xi/blob/develop/src/CryptoNoteCore/EligibleIndex.h]. This is basically a wrapper on parameters of the current unlock state of the blockchain.
```cpp
  uint32_t Height;     ///< The minimum blockchain height for all transaction inputs to be valid.
  uint64_t Timestamp;  ///< The minimum timestamp for all transaciton inputs to be valid.
```
I implemented that to distinguish two cases. First, a new transaction comes in and the daemon does not know the timestamp of the next block thus has to argue on the local time configuration. Second, you may want to validate a block in which case you may want to use the block timestamp.

Next, as you already pointed out this must be somehow used in `isTransactionSpendTimeUnlocked`. I did a slightly different approach on this, rather than locked or not locked I preferred to get the information when the transaction will be eligible and decide if it will be accepted based on the context.
```cpp
auto queryResult = chain().extractKeyOutputs(
      amount, chain().getTopBlockIndex(), {indices.data(), indices.size()},
      [&, this](const CachedTransactionInfo &info, PackedOutIndex index, uint32_t globalIndex) {
        XI_UNUSED(globalIndex);
        if (info.unlockTime < currency().maxBlockHeight()) {
          minHeight = std::max<uint32_t>(minHeight, static_cast<uint32_t>(info.unlockTime));
        } else {
          minTimestamp = std::max(minTimestamp, info.unlockTime);
        }
        outputKeys.push_back(boost::get<KeyOutput>(info.outputs[index.data.outputIndex]).key);
        return ExtractOutputKeysResult::SUCCESS;
      });
```
I altered the extraction method to do this and finally return an eligible index for the transaction that must be satisfied based on the context evaluating. The entire implementation is [here](https://gitlab.com/galaxia-project/blockchain/xi/blob/develop/src/CryptoNoteCore/Transactions/TransactionValidator.cpp#L186).

I wanted to distinguish these cases for the future to maybe allow transactions in the pool that only get valid in a day or so but still only mine those that are valid for the block. To accomplish this my pool implementation has this interface.
```cpp
  /*!
   * \brief eligiblePoolTransactions queries pool transactions ready to be mined and sorts them to prioratize more
   * profitable transactions.
   * \param index The eligble index of the blockchain the returned transactions must be eligible
   * \return all transactions contained in the pool satisfying the index requirement
   */
  virtual std::vector<CachedTransaction> eligiblePoolTransactions(
      EligibleIndex index) const = 0;
```
Full interface declaration is [here](https://gitlab.com/galaxia-project/blockchain/xi/blob/develop/src/CryptoNoteCore/Transactions/ITransactionPool.h). Based on the knowledge of the eligibe index of pool transactions (cached) we can change the `fillBlockTemplate` routine [here](https://gitlab.com/galaxia-project/blockchain/xi/blob/develop/src/CryptoNoteCore/Core.cpp#L2172).
```cpp
const EligibleIndex blockIndex{height, block.timestamp};
// We assume eligible transactions are ordered, such that the first transactions are most profitible. Using this
// we now implement a greedy search algorithm to fill the transaction.
std::vector<CachedTransaction> poolTransactions = m_transactionPool->eligiblePoolTransactions(blockIndex);
```
The block timestamp to mine was already filled into the black once this method gets called. Last as you wrote the transactions must be validated in the block validation itself. I did this, or actually I missed it, but here is how I guess I will implement it now, using the extraction output routine.
```cpp
ExtractOutputKeysResult BlockchainCache::extractKeyOutputKeys(uint64_t amount, uint32_t blockIndex,
                                                              Common::ArrayView<uint32_t> globalIndexes,
                                                              std::vector<Crypto::PublicKey>& publicKeys,
                                                              uint64_t timestamp)
```
I do not know if i changed that or that is already available but thats just an overload using the provided timestamp instead of the local timestamp for validation. Then this can be used in the block validation providing the new block timestamp.

**Comment by SoreGums** [comment]
looks like you went for flexible allowance into the mempool and rigid consensus into blocks.

ie wallet can send tx with locked inputs as long as it is within some threshold.
and then tx in blocks are only allowed if their unlock time is greater than the timestamp of the block.

I think this makes sense - keep the network block consensus rules strict, yes/no. then if people want to be flexible somewhere else for niceness then that's OK. Easier to implement against yes/no rules instead of a range of valid values.

**Comment by michael-herwig** [comment]
Yes that was the intent, I think whenever you allow a maybe on a block validation that is based on a local state rather then the consensus in the blockchain one may abuse that to create blocks that are only valid for a partial amount of the daemons running. One downside to this approach is the transaction pool synchronization. Transactions may not be valid for other pools as the transaction pool state has no conensus. You may could choose to validate against the minimum timestamp of the time checking zone on the main blockchain +-delta, which is checked to advance for the next block, but that may make the decision if a timestamp based output is unlocked or not a bit confusing if you take the minimum of about 128-1024 blocks (based on configuration).

**Comment by SoreGums** [comment]
that's what lite blocks are for. help get those extra txs that the node doesn't have.

plus there might be cases where some daemons just don't want "maybe txs" and doesn't accept them.

probably best to default to a low number least a spammer comes along and clogs the network with junk and help pool operators that don't code daemons not get kicked off the network due to crashing daemon cause operator also doesn't really understand how things work yet has 15% of the hash...

**Comment by zpalmtree** [comment]
What's wrong with just using the previous block timestamp as our threshold?

```cpp
bool isInputUnlocked(input, previousBlock) {
    return input.unlockTime >= previousBlock.timestamp;
}
```

Seems to me a hell of a lot simpler, and there's no consensus issue, as everyone will have the same timestamp. Works the same both when adding a transaction to the pool, and validating a new block.

**Comment by michael-herwig** [comment]
Yes, that should partially work, you would still need to change the `fillBlockTemplate` as timestamps are not guaranteed to be greater than the previous one. If you add this validation into the transaction pool then you may invalidate transactions in the pool with blocks jumping back in time.

**Comment by MysticCraftYT** [comment]
:)

**Comment by armitage0** [comment]
Why @MysticCraftYT?
