### ISSUE TITLE
Re-move DB path

### ISSUE THREAD

**Issue by Turcy086** [turtlecoin/turtlecoin#75]
Dear support,
Can you tell how can I modify the default DB path?
I do not want to use C:\ drive
T U
Matthew

**Comment by ZedPea** [comment]
`TurtleCoind --data-dir = D:\whatever`

Will need to use a symlink if you're using the GUI wallet

**Comment by paulie-g** [comment]
This isn't support, it's a bug tracker. If you want support, you should be using #help on our discord.

You can do what @ZedPea says, or you can create a junction from the standard directory to wherever you want it to be.

**Comment by Turcy086** [comment]
Thank you!

**Comment by CaptainMeatloaf** [comment]
I'm glad your problem was resolved, but in the future, you should direct such questions to the #help channel on the Discord server - this is a bug tracker
