### ISSUE TITLE
Question: how to disable mixing correctly

### ISSUE THREAD

**Issue by jwwi** [turtlecoin/turtlecoin#754]
hello guys !   (btw sorry for my bad english)

i'am playing around with forking "the great turtle", and i need help with zeromixing (new blockchain = no matching outputs issue)
i want that the blockchain collect some transaction first, and than at blockhight 300000 to set mixing "3".

but now i get some ERRORS:
ERROR   Failed to get any matching outputs for amount 20000 (20.000 SCR). Further explanation here: https://gist.github.com/zpalmtree/80b3e80463225bcfb8f8432043cb594c
Note: If you are a public node operator, you can safely ignore this message. It is only relevant to the user sending the transaction.

this is what i have:

/* This section defines our minimum and maximum mixin counts required for transactions */
const uint64_t MINIMUM_MIXIN_V1                              = 0;
const uint64_t MAXIMUM_MIXIN_V1                              = 1;

const uint64_t MINIMUM_MIXIN_V2                              = 3;
const uint64_t MAXIMUM_MIXIN_V2                              = 3;

const uint64_t MINIMUM_MIXIN_V3                              = 4;
const uint64_t MAXIMUM_MIXIN_V3                              = 4;

/* The heights to activate the mixin limits at */
const uint32_t MIXIN_LIMITS_V1_HEIGHT                        = 0;
const uint32_t MIXIN_LIMITS_V2_HEIGHT                        = 300000;
const uint32_t MIXIN_LIMITS_V3_HEIGHT                        = 1200000;

/* The mixin to use by default with zedwallet and turtle-service */
/* DEFAULT_MIXIN_V0 is the mixin used before MIXIN_LIMITS_V1_HEIGHT is started */
const uint64_t DEFAULT_MIXIN_V0                              = 1;
const uint64_t DEFAULT_MIXIN_V1                              = MAXIMUM_MIXIN_V1;
const uint64_t DEFAULT_MIXIN_V2                              = MAXIMUM_MIXIN_V2;
const uint64_t DEFAULT_MIXIN_V3                              = MAXIMUM_MIXIN_V3;

walletsettings:
/* Is a mixin of zero disabled on your network? */
    const bool mixinZeroDisabled = true;

/* If a mixin of zero is disabled, at what height was it disabled? E.g.
   fork height, or 0, if never allowed. This is ignored if a mixin of
   zero is allowed */

   const uint64_t mixinZeroDisabledHeight = CryptoNote::parameters::MIXIN_LIMITS_V2_HEIGHT;

electronwalletshell - ws_config.js settings:
// default mixin/anonimity for transaction
config.defaultMixin = 0;

**Comment by zpalmtree** [comment]
Your config appears to be correct, however, your default mixin is 1. Either set this to zero, or add an option in the wallet for the user to choose the mixin.

I think you have also configured zedwallet correctly to automatically offer retrying the transaction with 0 mixin if it fails. What wallet are you attempting to send the transaction with?

**Comment by jwwi** [comment]
the transaction was made with the electron wallet ( and in the ws_config.js is set config.defaultMixin = 0;

**Comment by zpalmtree** [comment]
That variable is, I believe, not actually used. You can confirm by viewing the turtle-service logs for the RPC request sent.

**Comment by jwwi** [comment]
roger ty, i suggest to setting
const uint64_t MINIMUM_MIXIN_V1 = 0;
const uint64_t MAXIMUM_MIXIN_V1 = 0;

~ const uint64_t DEFAULT_MIXIN_V1 = MAXIMUM_MIXIN_V1;

is there a command to set the mixing before transaction manually ( i use zedwalletbeta )

**Comment by jwwi** [comment]
btw thankyou for the great work on turtlecoin, and the others (many ) turtlecoin projects.
your tutorials and well documented code help me to learn how it works, how the blockchain works

**Comment by zpalmtree** [comment]
There is no option to set mixin manually in zedwallet-beta, as it was written after we moved to a static mixin. However, it would be relatively trivial to add support for this, if you have a little programming knowledge.

**Comment by jwwi** [comment]
hmm with the mixing "0" settings above, still have the issue in electron wallet.
the zedwallet is fine.

the electron wallet not accept the 0 mixing and it want still mixing.
>>>>
Failed to get enough matching outputs for amount 100000 (100.000 SCR). Requested outputs: 2, found outputs: 1. Further explanation here: https://gist.github.com/zpalmtree/80b3e80463225bcfb8f84
>>>>
config.defaultMixin = 0;

in ws_api.js
class WalletShellApi {
    constructor(args) {
        args = args || {};
        if (!(this instanceof WalletShellApi)) return new WalletShellApi(args);
        this.service_host = args.service_host || '127.0.0.1';
        this.service_port = args.service_port || config.walletServiceRpcPort;
        this.service_password = args.service_password || "WHATEVER1234567891";
        this.minimum_fee = (args.minimum_fee !== undefined) ? args.minimum_fee : (config.minimumFee * config.decimalDivisor);
        this.anonimity = config.defaultMixin;
    }

I'll try to fix it tomorrow

**Comment by zpalmtree** [comment]
Did you recompile your turtle-service?

**Comment by jwwi** [comment]
in the block 36:  info below  i make 2 transaction with the zedwallet   500.000 and 100.000 

block_id: 153301a78fb3c06342cb62a70581fecaed80fc413e68a8c6d7f866cb5981f6ae
{"major_version":5,"miner_tx":{"extra":"014827009d1029f32ed79fde20378aa6065796ace04bb98d46b2285577878af45b","unlock_time":45,"version":1,"vin":[{"type":"ff","value":{"height":35}}],"vout":[{"amount":1,"target":{"data":{"key":"b505ceb126bad05838b05e0a79c4f72b4198707c9202c41e2b296362930095d3"},"type":"02"}},{"amount":80,"target":{"data":{"key":"bb3b7abfd861f8288aede0c99e1cde50a217924bac80ce9ecd1e7d100d7a300e"},"type":"02"}},{"amount":700,"target":{"data":{"key":"9debca66cf540c30b3e0bd32e2b1a7c9ca2c6f3ee16b63437d312c255e2a0270"},"type":"02"}},{"amount":4000,"target":{"data":{"key":"1503db6d9edd7b5839a25fe751141f6f335275384d0576c840f90afe526b5625"},"type":"02"}},{"amount":10000,"target":{"data":{"key":"a088bb74ba48538f6f5de2b149095317f91a1cd3ef59dba8dd8b6f20d7846019"},"type":"02"}}]},"minor_version":0,"parent_block":{"majorVersion":0,"minerTx":{"extra":"0321001de3e81d6c67f5eb85d876b1972a7d155c1999b778bd1d1a73841c1e640640c0","unlock_time":0,"version":0,"vin":[],"vout":[]},"minorVersion":0,"nonce":"d3d99b29","numberOfTransactions":1,"prevId":"0000000000000000000000000000000000000000000000000000000000000000","timestamp":1552442741},"prev_id":"724b00c89391f8b05417865a7c82cd603894584190c0f56d3fb9b2c60871bf6d","tx_hashes":[]}

**Comment by jwwi** [comment]
> Did you recompile your turtle-service?

oh maybe not :D
iam fool :D

**Comment by jwwi** [comment]
recompiled and works great ;)
