### ISSUE TITLE
static_assert c11 feature breaks in some build environments

### ISSUE THREAD

**Issue by paulie-g** [turtlecoin/turtlecoin#76]
See #54 

We're currently redefining static_assert to _Static_assert for Clang, it might also be a good thing to do for gcc, either all the time or under some conditions. I suspect it's a buggy build environment as static_assert ought to work with -std=c11/gnu11 but it's a buggy build environment that is likely to come up again if we don't apply a fix.

Does anyone have a Centos 6 box handy to test what a minimum required fix is?

**Comment by RocksteadyTC** [comment]
@paulie-g can you elaborate a little bit? I have a CentOS box with recent build here if you have a minute.

**Comment by RocksteadyTC** [comment]
>apply a barrel of salt.

Thanks Paulie, I forgot you had a sense of humor :) Good to hear back from you and thank you for taking a minute to get us up to date on this. Unless you disagree, I think we can close this one, but if you'd like to add supplementary info, feel free to see that it is reopened. 

Also, tell this user that we said thanks for supporting us :)
