### ISSUE TITLE
Blockchain stop Sync every 2 days for pool

### ISSUE THREAD

**Issue by TarakanovOleg** [turtlecoin/turtlecoin#78]
Hello! Every two days I have some issue:
Exception in connectionHandler: _Map_base::at
2018-Feb-21 04:53:43.153785 INFO    Sync data returned unknown top block: 205002 -> 205643 [641 blocks (0 days) behind] 
2018-Feb-21 04:53:43.153785 INFO    SYNCHRONIZATION started
Why it happen and how to fix this for future?
I have over 4-6 hours wrong blockchain and lost my mining result, because I make wrong cache
Last issue make lose finding block - they orphaned

I use Dockerfile from this repo and have version:
TurtleCoin v0.3.2.1253
TurtleCoin wallet v0.3.2.1253

**Comment by CaptainMeatloaf** [comment]
I can confirm these map base errors on at least one of my daemons that refused to sync also, on turtlepool

**Comment by RocksteadyTC** [comment]
Can everyone who is having sync issues please post the results of this command to see if the hard drives are being encumbered

`iostat ­-xz 1`

Please list your stats during block propagation as well between blocks as far as IO load and Idle

**Comment by brandonlehmann** [comment]
@CaptainMeatloaf @TarakanovOleg 

Are you still experiencing the issue after updating to the latest release?

**Comment by CaptainMeatloaf** [comment]
Less frequent, but still an occurrence unfortunately.

**Comment by RocksteadyTC** [comment]
@CaptainMeatloaf does the issue persist with 0.4.3?

**Comment by minerrocks** [comment]
The issue exists in v0.12.0

**Comment by brandonlehmann** [comment]
Please open a NEW issue using the template provide, including build logs, daemon logs, etc.
