### ISSUE TITLE
SQLite initial sync is too slow compared to SwappedVector

### ISSUE THREAD

**Issue by rashedmyt** [turtlecoin/turtlecoin#780]
# Using SQLite for the blockchain cache is slower than using the original SwappedVector code
# Using external checkpoints is worse than without using external checkpoints

### Expected
Using external checkpoints should speed up the sync process as showed below

| Blocks | Without | With |
| ------ | --- | ---- |
| 0 - 20k | 2:40 sec | 1:30 sec |
| 0 - 50k | 6:30 sec | 6min |
| 0 - 100k | 13:30sec | 12min |

### Actual
Using external checkpoints with SQLite performs worse than without using them.. Below are some numbers

| Blocks | Without | With |
| ------ | --- | ---- |
| 0 - 20k | 6 min | 7 min |
| 0 - 50k | 30 min | 35 min |
| 0 - 100k | 1:44 hr | >2 hr |

**Comment by brandonlehmann** [comment]
Not a good comparison.  SQLite does not replace rocksdb. It’s two different subsystems. 

That being said, the original implementation is swappedvector which is binary data dumped to a file with separate indexes. The only experimental is sqlite3 which is known to be slower for this use case.

**Comment by rashedmyt** [comment]
> The only experimental is sqlite3 which is known to be slower for this use case.

is this a problem of SQLite or our code.. becoz the difference is quite huge

**Comment by brandonlehmann** [comment]
You’re welcome to **read** the code; however, there isn’t much there. SQLite is not incredibly fast when doing bulk inserts... especially when there is an index involved. We could skip the index but that would kill block lookup times.

**Comment by zpalmtree** [comment]
One simple optimization I noticed post merge is that we calculate the blocks count every time we need it, rather than initializing it once, and using a class variable to keep track of it. Not sure if this is on the hotpath, but could possibly help.

**Comment by brandonlehmann** [comment]
That may help a wee bit. I’ve seen the same slowness on bulk inserts in other projects as well though so I more or less consider it “normal”. Worth checking out for sure.

**Comment by rashedmyt** [comment]
# Using external checkpoints is worse than without using external checkpoints

### Storage - _Mechanical HDD Seagate 1TB_

### Expected
Using external checkpoints should speed up the sync process as showed below

| Blocks | Without | With |
| ------ | --- | ---- |
| 0 - 20k | 2:40 sec | 1:30 sec |
| 0 - 50k | 6:30 sec | 6min |
| 0 - 100k | 13:30sec | 12min |

### Actual
Using external checkpoints with SQLite performs worse than without using them.. Below are some numbers

| Blocks | Without | With |
| ------ | --- | ---- |
| 0 - 20k | 6 min | 7 min |
| 0 - 50k | 30 min | 35 min |
| 0 - 100k | 1:44 hr | >2 hr |

**Comment by brandonlehmann** [comment]
Updated topic and OP message to help combine the two issues.

**Comment by brandonlehmann** [comment]
Could also shave some time off by switching to rapid json :)

**Comment by brandonlehmann** [comment]
We'll see if #779 helps at all as it looks like he swapped the json to rapidjson in the sqlite code as well :)

**Comment by brandonlehmann** [comment]
Nothing to "fix" here as it's an experimental feature that will likely be removed anyways.
