### ISSUE TITLE
Using external checkpoints with SQLite making sync slow

### ISSUE THREAD

**Issue by rashedmyt** [turtlecoin/turtlecoin#781]
### Expected
Using external checkpoints should speed up the sync process as showed below

| Blocks | Without | With |
| ------ | --- | ---- |
| 0 - 20k | 2:40 sec | 1:30 sec |
| 0 - 50k | 6:30 sec | 6min |
| 0 - 100k | 13:30sec | 12min |

### Actual
Using external checkpoints with SQLite performs worse than without using them.. Below are some numbers

| Blocks | Without | With |
| ------ | --- | ---- |
| 0 - 20k | 6 min | 7 min |
| 0 - 50k | 30 min | 35 min |
| 0 - 100k | 1:44 hr | >2 hr |

**Comment by brandonlehmann** [comment]
Is this a dupe of #780? Can you just update that one instead please?

**Comment by rashedmyt** [comment]
Why would it be a dupe.. #780 compares two different subsystems as you mentioned.. but this one points out the performance hit using SQLite **with** and **without** checkpoints

**Comment by brandonlehmann** [comment]
The discussion regarding SQLite speed is over there. Drag this bad boy over there as it’s talking about SQLite speed.
