### ISSUE TITLE
Enhancement: Scan height range

### ISSUE THREAD

**Issue by derp-derp-derp** [turtlecoin/turtlecoin#793]
It would be cool if zedwallet allowed you to enter not only the starting block to scan for transactions, but also the ending block... like a range.

_e.g._ I have a wallet, and I know I only used it from block x to block x, but the import still takes a long time per having to scan all of the blocks after the starting point, as opposed to stopping at a certain block.

**Comment by zpalmtree** [comment]
Should it scan this range, and then resume scanning from the 'current' height, or just stop there and never scan more blocks?

**Comment by derp-derp-derp** [comment]
Great question. Resuming scanning from the current height makes sense I think.

**Comment by RocksteadyTC** [comment]
+1 resume

**Comment by mrrovot** [comment]
In the future couldn't we add to this feature by:

1 - take a synced wallet
2 - export to JSON file all block heights where transactions happened
3 - have the `scanRange` function with an option to import a JSON file
4 - if you need to import the wallet from scratch, just have import it together with the JSON file and the new sync will be really quick

just an idea

**Comment by brandonlehmann** [comment]
> In the future couldn't we add to this feature by:
> 
> 1 - take a synced wallet
> 2 - export to JSON file all block heights where transactions happened
> 3 - have the `scanRange` function with an option to import a JSON file
> 4 - if you need to import the wallet from scratch, just import it together with the JSON file and the new sync will be really quick
> 
> just an idea

If you only ask a node, of which a lot of uses use remote ones, for *interesting* blocks you’re telling the node operator exactly which funds are yours. ;)

**Comment by zpalmtree** [comment]
Implemented in #1093
