### ISSUE TITLE
TurtleCoin fork: how to define addresses prefix for miner?

### ISSUE THREAD

**Issue by Chovanec** [turtlecoin/turtlecoin#798]
I forked TurtleCoin and customized some config including addresses pefix. I compiled it on Windows using Visual Studio. `Wallet` and `daemon` work fine but `miner` do not work. When I start miner and add address get this message:

    Address is not valid: The address does not have the correct prefix corresponding to this coin - it appears to be an address for another cryptocurrency.

Where can I define addresses pefix for `miner`?

I followed these steps: https://github.com/turtlecoin/turtlecoin#windows

**Comment by zpalmtree** [comment]
`config/WalletConfig.h`
