### ISSUE TITLE
[BlockchainSynchronizer] Failed to query outdated pool transaction: NodeErrorCategory:3, Network error

### ISSUE THREAD

**Issue by limulidae** [turtlecoin/turtlecoin#81]
got this failure when running simplewallet.

how to fix it?

**Comment by ereptor81** [comment]
Should just need to run turtlecoind and let it sync. It has to be running and syncd when you open simplewallet.

**Comment by lucianot54** [comment]
Same error on MAX OS X with version v0.3.2.
turtlecoind was sync and when I execute simplewallet and import my wallet i have same error.

**Comment by istvanszoboszlai** [comment]
I think this error message should be more clear. This is not an error. This is just a condition.

**Comment by SoreGums** [comment]
this is fixed - new simplewallet takes care of this
