### ISSUE TITLE
Trying to fork Turtlecoin, but I tried mining and after around 50 blocks, it made my daemon crash. It said 'core dump'.

### ISSUE THREAD

**Issue by crypthusiast0** [turtlecoin/turtlecoin#810]
Unfortunately, I cant put the output from terminal here, but I can tell you that when I try to mine, it kills the daemon. What's happening here?

**Comment by zpalmtree** [comment]
Run under valgrind to figure out where it is segfaulting. Ensure you are not building in debug mode.

**Comment by crypthusiast0** [comment]
from where whats the dir?

**Comment by zpalmtree** [comment]
Huh?

**Comment by crypthusiast0** [comment]
How do you run valgrind

**Comment by SoreGums** [comment]
basically, your issue is not something we can help with directly without information. you've said you can't supply the information, that's fine. so now you need to debug your situation and figure it out.

alternatively - undo all your changes and do one at a time and see which one breaks it, then present that here and we'll see if there is anything obvious to make of the situation.

google is your friend now to go about figuring it out on your own - else share information :)

**Comment by bobbieltd** [comment]
Try previous codes (git checkout master). The latest codes will “core dump”.

**Comment by crypthusiast0** [comment]
Ok will post output with set_log as 4

**Comment by bobbieltd** [comment]
set log 4 with your coin, curl getblocktemplate to see if core dump like my case or not.

**Comment by crypthusiast0** [comment]
Here is the miner output: `Failed to parse block template from daemon. Received data:
{"error":{"code":-5,"message":"Internal error: failed to create block template"},"jsonrpc":"2.0"}
Parse error: [json.exception.out_of_range.403] key 'result' not found
Failed to parse block template from daemon. Received data:
{"error":{"code":-5,"message":"Internal error: failed to create block template"},"jsonrpc":"2.0"}
Parse error: [json.exception.out_of_range.403] key 'result' not found
Failed to parse block template from daemon. Received data:
{"error":{"code":-5,"message":"Internal error: failed to create block template"},"jsonrpc":"2.0"}
Parse error: [json.exception.out_of_range.403] key 'result' not foundFailed to parse block template from daemon. Received data:
{"error":{"code":-5,"message":"Internal error: failed to create block template"},"jsonrpc":"2.0"}
Parse error: [json.exception.out_of_range.403] key 'result' not found
Failed to parse block template from daemon. Received data:
{"error":{"code":-5,"message":"Internal error: failed to create block template"},"jsonrpc":"2.0"}
Parse error: [json.exception.out_of_range.403] key 'result' not found
Failed to parse block template from daemon. Received data:
{"error":{"code":-5,"message":"Internal error: failed to create block template"},"jsonrpc":"2.0"}
Parse error: [json.exception.out_of_range.403] key 'result' not found`



And here is the Daemon output:
`2019-May-09 16:18:51.024605 ERROR   difficulty overhead.
2019-May-09 16:18:51.025137 ERROR   Failed to create block template
2019-May-09 16:18:52.027551 ERROR   difficulty overhead.
2019-May-09 16:18:52.028070 ERROR   Failed to create block template
2019-May-09 16:18:53.029683 ERROR   difficulty overhead.
2019-May-09 16:18:53.030209 ERROR   Failed to create block template`

**Comment by crypthusiast0** [comment]
Here is the Core dump output:

2019-May-09 16:30:44.521359 INFO    New Top Block Detected: 1
2019-May-09 17:12:42.528375 INFO    New Top Block Detected: 29
TurtleCoind: /home/ubuntu/yeetcoin/src/CryptoNoteCore/Core.cpp:275: virtual uint64_t CryptoNote::Core::getBlockTimestampByIndex(uint32_t) const: Assertion `!(timestamps.size() == 1)' failed.
Aborted (core dumped)`

**Comment by zpalmtree** [comment]
As I mentioned
>Ensure you are not building in debug mode.

Compile with `cmake .. -DCMAKE_BUILD_TYPE=Release`

**Comment by crypthusiast0** [comment]
Ok, also this happens around block 60.just fyi

**Comment by bobbieltd** [comment]
![99667783-6585-4FD8-BC9F-3F6BC89E95B3](https://user-images.githubusercontent.com/29669374/57476832-a12f5880-72c1-11e9-9956-b3823788a195.jpeg)
Same core dump that I encountered with Turtlecoin. Same line in core.cpp

**Comment by zpalmtree** [comment]
You need to compile in release mode.

> > Ensure you are not building in debug mode.
> 
> Compile with `cmake .. -DCMAKE_BUILD_TYPE=Release`

**Comment by bobbieltd** [comment]
I did not remember but my batch build file had -DCmake...=Release, I will double check it later

**Comment by zpalmtree** [comment]
Asserts are only enabled in debug mode, so somewhere that must be getting enabled.

**Comment by crypthusiast0** [comment]
I recompiled, but no luck. Same output as before.

**Comment by zpalmtree** [comment]
Can you post the cmake output of your compilation.

**Comment by crypthusiast0** [comment]
I compiled the files, but still got the difficulty overhead failed to create block template error on my Daemon when i try to mine.

**Comment by zpalmtree** [comment]
Difficulty overhead is unrelated to the core dump issue, no? Usually because you stopped mining. Build not defaulting to release has been fixed in #812

**Comment by crypthusiast0** [comment]
Here is the cmake output:
`-- FORCE_USE_HEAP: ENABLED
-- HW AES: ENABLED
-- OPTIMIZED_ARM_MULTIPLICATION: ENABLED
-- Found Git: /usr/bin/git
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- Boost Found: /usr/include
-- OpenSSL Found: /usr/include
-- OpenSSL Libraries: /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a;dl
-- *************************************************************************
The Crypto++ library does not officially support CMake. CMake support is a
community effort, and the library works with the folks using CMake to help
improve it. If you find an issue then please fix it or report it at
https://github.com/noloader/cryptopp-cmake.
-- *************************************************************************
-- CMake version 3.13.3
-- Performing Test CRYPTOPP_IA32_SSE2
-- Performing Test CRYPTOPP_IA32_SSE2 - Success
-- Performing Test CRYPTOPP_IA32_SSSE3
-- Performing Test CRYPTOPP_IA32_SSSE3 - Success
-- Performing Test CRYPTOPP_IA32_SSE41
-- Performing Test CRYPTOPP_IA32_SSE41 - Failed
-- Performing Test CRYPTOPP_IA32_SSE42
-- Performing Test CRYPTOPP_IA32_SSE42 - Success
-- Performing Test CRYPTOPP_IA32_CLMUL
-- Performing Test CRYPTOPP_IA32_CLMUL - Success
-- Performing Test CRYPTOPP_IA32_AES
-- Performing Test CRYPTOPP_IA32_AES - Success
-- Performing Test CRYPTOPP_IA32_AVX
-- Performing Test CRYPTOPP_IA32_AVX - Success
-- Performing Test CRYPTOPP_IA32_AVX2
-- Performing Test CRYPTOPP_IA32_AVX2 - Success
-- Performing Test CRYPTOPP_IA32_SHA
-- Performing Test CRYPTOPP_IA32_SHA - Success
-- Performing Test CRYPTOPP_MIXED_ASM
-- Performing Test CRYPTOPP_MIXED_ASM - Success
-- Platform: x86_64
-- Native arch: FALSE
-- Compiler: /usr/bin/g++-8
-- Compiler options:  -std=c++17  -Wall -Wextra -Wpointer-arith -Wvla -Wwrite-strings  -Wno-error=extra -Wno-error=unused-function -Wno-error=sign-compare -Wno-error=strict-aliasing -Wno-error=type-limits -Wno-unused-parameter -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wno-error=unused-result -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=clobbered -Wno-error=unused-but-set-variable -Wno-error=odr -Wno-reorder -Wno-missing-field-initializers  -maes -pthread -DCRYPTOPP_DISABLE_SSE4
-- Compiler definitions: 
-- Build type: Release
-- Enabling RTTI in Debug builds only (default)
-- JNI library is disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/yeetcoin/build/rocksdb
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/yeetcoin/build
`

**Comment by crypthusiast0** [comment]
Here is the error at log level 4:

```
2019-May-10 13:25:13.220221 ERROR   difficulty overhead.
2019-May-10 13:25:13.220413 ERROR   Failed to create block template
2019-May-10 13:25:13.220634 TRACE   JSON-RPC response: {"error":{"code":-5,"message":"Internal error: failed to create block template"},"jsonrpc":"2.0"}
2019-May-10 13:25:14.221683 TRACE   RPC request came: 
POST /json_rpc HTTP/1.1
Host: 127.0.0.1
accept: */*
content-length: 191
content-type: application/json
host: 127.0.0.1:10001
user-agent: cpp-httplib/0.2

{"jsonrpc":"2.0","method":"getblocktemplate","params":{"reserve_size":0,"wallet_address":"dappce7w9dcVfyhvFBwudEA7QmtnYyjX9MbCPHcPt7thebRLgw65ivPhHnuBc2qfT71vnJzeihSP1Nq5gEKgMmzG9HoFkRULFW"}}
2019-May-10 13:25:14.222753 TRACE   JSON-RPC request: {"jsonrpc":"2.0","method":"getblocktemplate","params":{"reserve_size":0,"wallet_address":"dappce7w9dcVfyhvFBwudEA7QmtnYyjX9MbCPHcPt7thebRLgw65ivPhHnuBc2qfT71vnJzeihSP1Nq5gEKgMmzG9HoFkRULFW"}}
```

**Comment by crypthusiast0** [comment]
And here is the miner:

```
Failed to parse block template from daemon. Received data:
{"error":{"code":-5,"message":"Internal error: failed to create block template"},"jsonrpc":"2.0"}
Parse error: [json.exception.out_of_range.403] key 'result' not found
Failed to parse block template from daemon. Received data:
{"error":{"code":-5,"message":"Internal error: failed to create block template"},"jsonrpc":"2.0"}
Parse error: [json.exception.out_of_range.403] key 'result' not found
```

**Comment by SoreGums** [comment]
so isn't this diff problem about not mining blocks?

mine a block, mine a block, stop mining, come back 5 days after, diff problem can't mine diff < 0

**Comment by crypthusiast0** [comment]
In the long run, I can't just keep deleting folders and starting all over again, also you can just run ./TurtleCoind --resync simultaniously on both of the nodes for quicker datdir delettion. What do I do about launching my coin in the long run?

**Comment by SoreGums** [comment]
mine it 24/7 and don't stop?

**Comment by crypthusiast0** [comment]
Hmmmm. Is that how turtle works?
It seems a little buggy.

**Comment by SoreGums** [comment]
yes, the blockchain requires being mined 24/7
not sure how blocks are meant to come out every 30secs if blocks don't come out every 30secs

**Comment by SoreGums** [comment]
so are you getting core dumps now?
that is what you came here initial with

and --rewind-to-height works, needs to be done on all nodes of course.

**Comment by crypthusiast0** [comment]
Hello all,
I have tried to mine 24/7, butt I have been getting the core dump errors. I need to have someone  save my butt. Why is this happening? Please help me. THanks for all the help.

**Comment by zpalmtree** [comment]
A core dump is not a difficulty overhead. It's quite hard to help when you're reporting two different issues as the same. If you're getting asserts hit, you're haven't compiled correctly. If you're getting difficulty overhead, you're not mining 24/7.

Post exact errors, please.

**Comment by thinkpol2** [comment]
The "core dump" (asserts) issue was fixed by @zpalmtree in #812. Pull the latest code from the development branch and build again. Once you're up and running again, don't stop mining.

**Comment by bobbieltd** [comment]
Ohhh Yeahhh, ca roule. No more core dump. Thanks devs !

**Comment by crypthusiast0** [comment]
No,, I haave the latest code. It still core dumps on the miner.

**Comment by thinkpol2** [comment]
Please post the error you're seeing from the miner.

**Comment by crypthusiast0** [comment]
`Segmentation fault(core dump).`

**Comment by crypthusiast0** [comment]
With both miner and daemon

**Comment by crypthusiast0** [comment]
please help me!

**Comment by crypthusiast0** [comment]
My coin is linked here: https://github.com/crypthusiast0/yeetcoin

**Comment by brandonlehmann** [comment]
https://github.com/crypthusiast0/yeetcoin/blob/8a8991996f201a4b4d69454e1471b95899b16a39/src/config/CryptoNoteConfig.h#L19

Good luck with that one... another fork is running 5s and the chain flies apart at times. 1s target is pretty lofty.

**Comment by zpalmtree** [comment]
We cannot help debug segfaults without more information. Run under valgrind (as mentioned in the very first post...) to get information on where the code is crashing.

**Comment by crypthusiast0** [comment]
How do you run valgrind? You never told me.

**Comment by zpalmtree** [comment]
Cmon man, do I have to hold your hand the whole way? You're coming to us with a problem, don't make us help you gather all the information we need to fix it as well.
