### ISSUE TITLE
Remove no longer relevant asserts

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#811]
Since pretty much everyone runs the daemon in release mode, instead of debug mode, we've ended up where we have a number of asserts which constantly trigger, due to altered/moved/rewritten sections of code.

We probably want to remove or update all these asserts to ensure they are still indeed checking things which should be 'impossible'.

It would also be nice to add more assertions to new code.

I'm not aware how many asserts there are in the current codebase, but it would probably be a good idea to separate this into multiple PR's for ease of reviewing and testing.

**Comment by brandonlehmann** [comment]
`grep -Hrni 'assert('`

**Comment by zpalmtree** [comment]
Looks like about a 1000 :grimacing:

**Comment by brandonlehmann** [comment]
On second thought, this is a horrible `good first issue`. 

![giphy](https://user-images.githubusercontent.com/20562132/89133896-15b96d00-d4ee-11ea-8adb-f25b2fcf0687.gif)

**Comment by brandonlehmann** [comment]
This item will not be addressed.
