### ISSUE TITLE
Zedwallet crashing when parsing extra

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#839]
Seems extra isn't stored as hex in WalletGreen -
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  fromHex: invalid string size
```

To reproduce, either open a wallet and let it scan for a transaction, or send it a transaction, then do `list_transfers`.

Not sure how the extra is stored to correctly convert to a `std::vector<uint8_t>`.

Bug introduced by #836

**Comment by brandonlehmann** [comment]
If it's not a string, are you sure it's not already a `BinaryArray`?

**Comment by zpalmtree** [comment]
It is a `std::string`, I'm just not sure what's stored in the string - I think there might be a `fromString` method to go from a `std::string` to a `std::vector<uint8_t>`

**Comment by brandonlehmann** [comment]
There is it's `Common::asBinaryArray(std::string)`

https://github.com/turtlecoin/turtlecoin/blob/c9908d5622ec12bebecaecc388973fe6244e6c35/src/Common/StringTools.cpp#L55

**Comment by FrenChain** [comment]
I am having this problem too when trying to sync up my wallet. It says New transaction found, then shows the details of the transfer. Immediately after this is shown. This is for a TRTL fork by the way.

terminate called after throwing an instance of 'std::runtime_error'
  what():  fromHex: invalid string size
Aborted (core dumped)
