### ISSUE TITLE
print_bc = no output

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtlecoin#85]
windows 10 x64
TurtleCoin v0.3.2.1253 (0.1-g7fcc6ad)

```
print_bc
need block index parameter
print_bc  238560
print_bc  238561
print_bc  238550 238561
print_bc  238550 238565
end block index parameter shouldn't be greater than 238562
print_bc  238562 238561
end block index should be greater than starter block index
print_bc  238563
end block index should be greater than starter block index
print_bc  238564
end block index should be greater than starter block index
print_bc  238561
:(
```

![image](https://user-images.githubusercontent.com/317/36956107-16487bc6-205f-11e8-88d2-4ece565a63c5.png)

everything else about print_cn seems to work with regards to validating the params of the command, once you get the params correct it seems to just bail.

**Comment by yamiM0NSTER** [comment]
As of right now print_bc is only placeholder and has no functionality implemented for printing out blockchan info in given blocks.

**Comment by SoreGums** [comment]
this appears to be the answer ;)

created the issue as RockSteady thought it should be working.
what isn't tracked, isn't worked on etc.

**Comment by SoreGums** [comment]
I've been playing with this in v0.4.2
Works pretty good, thanks @yamiMonster
