### ISSUE TITLE
walletd RPC interface does not put content-type header in HTTP response

### ISSUE THREAD

**Issue by BebopTC** [turtlecoin/turtlecoin#86]
Currently, the only HTTP headers in walletd's JSON-RPC responses are:
```
{
  'content-length': '178',
  server: 'CryptoNote-based HTTP server'
}
```
where content-length is the actual length of the response. The headers should at least additionally include a `content-type: application/json`.

This is important for downstream consumers that rely on content-type to properly parse, for example.

**Comment by ereptor81** [comment]
This is fixed in master: https://github.com/turtlecoin/turtlecoin/commit/3ec8ab8a0c573bf0a8226b9cc0aa143af9a9f341
