### ISSUE TITLE
Use matches property in ApiDispatcher regex

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#862]
Some calls in the [ApiDispatcher](https://github.com/turtlecoin/turtlecoin/blob/development/src/walletapi/ApiDispatcher.cpp) use a regex, for example, `getTransactionDetails`. They then extract the query parameters like so:

```cpp
std::tuple<Error, uint16_t> ApiDispatcher::getTransactionDetails(
    const httplib::Request &req,
    httplib::Response &res,
    const nlohmann::json &body) const
{
    std::string hashStr = req.path.substr(std::string("/transactions/hash/").size());
```

We could instead extract `hashStr` using the `matches` property on the `req` object, by adding a capture group to the hash regex. Once this is done, the code would be something like

```cpp
std::tuple<Error, uint16_t> ApiDispatcher::getTransactionDetails(
    const httplib::Request &req,
    httplib::Response &res,
    const nlohmann::json &body) const
{
    std::string hashStr = req.matches[0];
```

It is not much of a gain in readability here, but there are some methods which have multiple parameters needing to be extracted which would benefit.

**Comment by brandonlehmann** [comment]
I think I just made this worse :)

**Comment by brandonlehmann** [comment]
Handled in #1092
