### ISSUE TITLE
SimpleWallet, delay background sync init until after finished with wallet generation/opening text/info

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtlecoin#87]
As per the screenshot below:
**Height** is getting injected from the Background sync thread within the wallet generation text.

![image](https://user-images.githubusercontent.com/317/37076120-af4e6480-2207-11e8-8bef-ea745b307ac3.png)

Ereptor has suggested this background thread be delayed until after all the startup/welcome/etc text has been sent to the screen.

Here is a video of it in action as well (yes this is from the rock testnet - still same code as here though)
https://youtu.be/q_ipbVW6p80

**Comment by ereptor81** [comment]
I believe this is now a non-issue since Z's simplewallet rewrite

**Comment by SoreGums** [comment]
probably correct. Let's close for now
