### ISSUE TITLE
weak for block 1800001

### ISSUE THREAD

**Issue by lazarekm** [turtlecoin/turtlecoin#870]
## System Information

**Operating System**: linux
**OS Version**: Ubuntu 18.04.3 LTS
**CPU Make, Model, & Speed**: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
**Amount of RAM**: 6GB
**Hard Drive Type**: SSD
**Hard Drive Size**: 500GB
**Volume Type**: ext4

### TurtleCoin Build Information

**Version: v0.18.1.1291
**Binary Source: precompiled binnaries https://github.com/turtlecoin/turtlecoin/releases/download/v0.18.1/turtlecoin-v0.18.1-linux.tar.gz

### Issue Report
**Binary Reported:** TurtleCoind

#### Current Behavior
After upgrade turtlecoind node to v0.18.1.1291, and successfully syncing with the network, occure in log warning about block 1800001:

2019-Aug-30 07:30:33.509686 WARNING [Core] Proof of work too weak for block 1800001 (553e4b67d72e1a1afa6a268cb791b946f91403b38c7518f2c10bc51f181a9262)

#### Steps to Reproduce
1. turtlecoind version v0.18.0.1290, was stucked at block 1800012
2. stop the daemon v0.18.1.1291
3. start the new version daemon 
4. wait some time for syncing, here is part of log
2019-Aug-30 07:05:11.544769 INFO    [daemon] Starting core rpc server on address 0.0.0.0:11898
2019-Aug-30 07:05:11.545460 INFO    [daemon] Core rpc server started ok
2019-Aug-30 07:05:11.545660 INFO    [daemon] Starting p2p net loop...
2019-Aug-30 07:05:11.545881 INFO    [node_server] Starting node_server
2019-Aug-30 07:05:12.600536 INFO    [protocol] [13.70.26.95:11897 OUT] Your TurtleCoin node is syncing with the network (99.99% complete) You are 1 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race! 
2019-Aug-30 07:05:12.600830 INFO    [protocol] New Top Block Detected: 1800012
2019-Aug-30 07:05:30.294136 INFO    [protocol] [167.99.0.68:11897 OUT] Your TurtleCoin node is syncing with the network (99.97% complete) You are 471 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race! 
2019-Aug-30 07:05:30.294309 INFO    [protocol] New Top Block Detected: 1800482
2019-Aug-30 07:05:36.155429 INFO    [Core] Resolved: 1800008 (4195fd5b48fd6cc8058c6e56772e0a56914a9df50b9c64b7fd71b3c9ec47a69c), Previous: 1800010 (1577fa6c75aa1d80bc46155cc2fb65c93674a8e5d3e01fc59eb9396dc6ac29d3)
2019-Aug-30 07:05:36.638207 INFO    [protocol] [13.125.157.231:44074 INC] Your TurtleCoin node is syncing with the network (99.99% complete) You are 15 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race! 
2019-Aug-30 07:05:39.891478 INFO    [protocol] [13.70.26.95:11897 OUT] Successfully synchronized with the TurtleCoin Network.
2019-Aug-30 07:06:33.422106 INFO    [protocol] [91.239.237.54:51948 INC] Your TurtleCoin node is syncing with the network (99.97% complete) You are 472 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race! 
2019-Aug-30 07:06:33.422249 INFO    [protocol] New Top Block Detected: 1800484
2019-Aug-30 07:06:34.228830 INFO    [protocol] [130.185.202.159:11897 OUT] Your TurtleCoin node is syncing with the network (99.97% complete) You are 472 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race! 
2019-Aug-30 07:06:43.114710 INFO    [Core] Resolved: 1800002 (365ef71a02c1b5814e940abc9acfb09ab16aa6bfcec779d2620cfbbb95c181c8), Previous: 1800011 (479b4dbe3a8e71a1cf104e4210f6592bce4d3e8d4374bc77df593dfd46e8b660)
2019-Aug-30 07:06:50.972581 INFO    [protocol] [145.131.30.157:11897 OUT] Your TurtleCoin node is syncing with the network (99.97% complete) You are 466 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race! 
2019-Aug-30 07:07:13.134208 INFO    [Core] Block 1800100 (2df29dba99a3cf428ec657d6c2cac98b0ff20cd7f3ac1a9e70a07a4f2cb13348) added to main chain
2019-Aug-30 07:07:53.222926 INFO    [protocol] New Top Block Detected: 1800485
2019-Aug-30 07:07:53.224212 INFO    [protocol] New Top Block Detected: 1800486
2019-Aug-30 07:10:00.462569 INFO    [protocol] New Top Block Detected: 1800487
2019-Aug-30 07:10:00.464159 INFO    [protocol] New Top Block Detected: 1800488
2019-Aug-30 07:10:31.761985 INFO    [protocol] [106.14.155.66:37470 INC] Your TurtleCoin node is syncing with the network (99.98% complete) You are 294 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race! 
2019-Aug-30 07:10:31.853100 INFO    [Core] Block 1800200 (fad54f70c4fdd9d0f25b29eefb3283b36ba22381d2887f7acb12b856acfb2e01) added to main chain
2019-Aug-30 07:10:50.933574 INFO    [Core] Block 1800300 (31eadb6c81b2b0478391cd94fd8886787e1f7bebc0e2522f3cc2c7b8e176ef06) added to main chain
2019-Aug-30 07:11:06.599029 INFO    [protocol] [168.235.104.92:11897 OUT] Your TurtleCoin node is syncing with the network (99.99% complete) You are 154 blocks (0 days) behind the current peer you're connected to. Slow and steady wins the race! 
2019-Aug-30 07:11:06.599217 INFO    [protocol] New Top Block Detected: 1800489
2019-Aug-30 07:11:26.436418 INFO    [protocol] New Top Block Detected: 1800490
2019-Aug-30 07:11:33.265934 INFO    [protocol] New Top Block Detected: 1800491
2019-Aug-30 07:11:36.124664 INFO    [Core] Block 1800400 (3c6613794d2c1f44c6921d07a1b6c85c9a94885ba470e4e4d1698966735d5dc6) added to main chain
2019-Aug-30 07:12:13.979206 INFO    [protocol] New Top Block Detected: 1800492
2019-Aug-30 07:12:32.933801 INFO    [protocol] New Top Block Detected: 1800493
2019-Aug-30 07:12:55.905649 INFO    [protocol] New Top Block Detected: 1800494
2019-Aug-30 07:13:19.548147 INFO    [protocol] [130.185.202.159:11897 OUT] Successfully synchronized with the TurtleCoin Network.
2019-Aug-30 07:13:19.853178 INFO    [protocol] [168.235.104.92:11897 OUT] Successfully synchronized with the TurtleCoin Network.
2019-Aug-30 07:13:19.939139 INFO    [protocol] New Top Block Detected: 1800495
2019-Aug-30 07:13:36.957050 INFO    [protocol] New Top Block Detected: 1800496
2019-Aug-30 07:14:35.452637 INFO    [protocol] New Top Block Detected: 1800497
2019-Aug-30 07:14:41.294869 INFO    [protocol] New Top Block Detected: 1800498
2019-Aug-30 07:15:15.233063 INFO    [protocol] New Top Block Detected: 1800499
2019-Aug-30 07:15:18.380088 WARNING [Core] Proof of work too weak for block 1800001 (553e4b67d72e1a1afa6a268cb791b946f91403b38c7518f2c10bc51f181a9262)
2019-Aug-30 07:15:48.218139 INFO    [protocol] New Top Block Detected: 1800500
2019-Aug-30 07:16:34.919356 INFO    [protocol] New Top Block Detected: 1800501
2019-Aug-30 07:16:36.237848 INFO    [Core] Block 1800500 (717e9782684001781a2f0d7e3bd3eb3aed46da6a9335fa839f5d018d1d8f121a) added to main chain
2019-Aug-30 07:16:36.990357 INFO    [protocol] New Top Block Detected: 1800502
2019-Aug-30 07:16:52.441708 INFO    [protocol] New Top Block Detected: 1800503
2019-Aug-30 07:17:18.562424 INFO    [protocol] New Top Block Detected: 1800504
2019-Aug-30 07:18:23.677334 INFO    [protocol] New Top Block Detected: 1800505
2019-Aug-30 07:18:30.873602 INFO    [protocol] New Top Block Detected: 1800506
2019-Aug-30 07:18:37.707498 WARNING [Core] Proof of work too weak for block 1800001 (553e4b67d72e1a1afa6a268cb791b946f91403b38c7518f2c10bc51f181a9262)
2019-Aug-30 07:18:45.620929 WARNING [Core] Proof of work too weak for block 1800001 (553e4b67d72e1a1afa6a268cb791b946f91403b38c7518f2c10bc51f181a9262)

**Comment by zpalmtree** [comment]
This is just a warning, it is nothing to worry about if your height is > 18000001 (you can check with `status`)
The warning will be turned to a debug log message with #869

**Comment by brandonlehmann** [comment]
Log level dropped in #869 for this message. PR has been merged.
