### ISSUE TITLE
Feature request: ask where to store/find the blockchain

### ISSUE THREAD

**Issue by seanspotatobusiness** [turtlecoin/turtlecoin#874]
For users with SSDs as their system drives it may not make sense for them to store blockchains on their limited SSD space and it would be nice to be able to choose an alternative location when running Turtlecoind.exe for the first time.

I have used a symlink to move my blockchain manually but it seems that whenever I download a new version of the wallet (CLI), I have to temporarily remove my symlink or else I get the error: "2019-Sep-03 16:12:02.153825 ERROR   [daemon] Exception: Can't create directory: C:\Users\seanv\AppData\Roaming/TurtleCoin" when running Turtlecoind.exe.

**Comment by zpalmtree** [comment]
There is a flag `--data-dir` which allows you to set the location, however, I understand command line flags are not the easiest for people not used to terminals. Interactively asking the user for this would be helpful for these users.

On the other hand, the daemon is designed to be a kinda 'launch and forget it' program, where you don't really want to pause for interactive input - this could certainly mess up a lot of service operators scripts.

**Comment by seanspotatobusiness** [comment]
Oh that's good. What about if it said something like "run with --help to get a list of advanced options" or something like that, as one of the first things it prints to the screen (after the copyright information) when you run it so users are alerted that they can do more than just click on it and run it? I will use --data-dir in the future; thanks very much!

**Comment by SoreGums** [comment]
Instead of running in a cli, a shortcut can be created and add `- - data-dir "d:\some other\folder"` to the end of the command.

**Comment by brandonlehmann** [comment]
Use the `--data-dir` argument as designed and documented in `--help`

`./TurtleCoind --data-dir /archive/blockchains/TurtleCoin`
