### ISSUE TITLE
Pool forking out of main chain

### ISSUE THREAD

**Issue by bobbieltd** [turtlecoin/turtlecoin#88]
I manage a Turtlecoin pool. Today, my pool forked itself out of mainnet to another direction with its own blockchain.
I’m trying to trace this issue. It’s my first time. It’s not NiceHash pool forking because my pool has only 1% network (it’s not > 50% Nicehash case).
It kept mining its own chain for 2 hours. It only came back to main chain when I restarted turtlecoin daemon.
My questions :
1. Is it normal sometime pool forks itself with small fluctuating coin like Turtlecoin ?
2. How can I avoid this in the future ? (my temporary solution is to put high mature required number to have time if it happens again)

Thanks for anyone who can give info.

**Comment by bobbieltd** [comment]
I asked Venthos about this issue and I have a quite clear explanation for this self hard fork today. It is possible that the pool’s node lost connections with peers and hard fork itself to different path. My solution is to add nodes to communicate with more peers and an  checking notification.

**Comment by RocksteadyTC** [comment]
Keep us posted of the result, and note the process so others can also benefit.

**Comment by bobbieltd** [comment]
I’m still mot sure adding peer will diminish this problem. Still need time to follow. By the way, daemon often get out of sync (5-6 times per days for 5-15 minutes at first). I tried to solve it by add priority node with daemon.turtle.link , it solved out of sync by some how and I launch officially my pool to public but oufff the pool forked out (I guess because of “good” synchronization).
I’m not hard coders. I check by list peers with daemon, there are alot of peers.
My temporary solution now is running two nodes and keep them peering to see if it changes this behaviour. There are 4 seed nodes in turtlecoin codes, I’m not sure if devs add more seeds and check if they are healthy (not overloaded) to make the network more healthy.
You can see this new issue #89

**Comment by bobbieltd** [comment]
Holly xxx ! It forks again today. I still don’t know the cause of it.

**Comment by netmonk** [comment]
:)

**Comment by SoreGums** [comment]
i added a total of 7 peers to a daemon pool of 8.
it didn't help.
they all lost sync with network and needed to be restarted.

the only real solution right now is run the https://github.com/turtlecoin/turtlecoind-ha and connect to other daemons and compare info, when things don't match, kill and restart.

**Comment by bobbieltd** [comment]
@SoreGums Thank you for your tweak. I also realise that we can not avoid it. What makes me worry about restarting daemon is payments. If payments is running and daemon is restarted in the process, it can make some negative consequences. The best solution (also very complicated) is to check payments process before restarting daemon.

**Comment by SoreGums** [comment]
yes indeed.

I was testing this during the testnet that was run for the 350k algo change.
I am pretty sure payments got swallowed when i was randomly restarting things.
when chatting with the others, pool ops said that payments were resilient to interruptions.
I'm not so sure that is true...

really the pool payments processor needs a 3 stage process.
1. to be paid - starting
2. being paid - working
3. got paid - finished, all good (recorded tx number for verification later)

I'm not sure what that would take to implement, however that is out of scope for this repo as it is the pool software and not the daemon. however if your daemon is being weird, payments are still up in the air anyways...

part of the deal of running a service ;)

**Comment by RocksteadyTC** [comment]
@bobbieltd please give 0.4.3 a shot and let us know if the problem persists. If you still have the same issue, please reopen the issue and we can get back at it

**Comment by bobbieltd** [comment]
It seems back to normal now. Good to see that.
