### ISSUE TITLE
Need a MAC miner

### ISSUE THREAD

**Issue by ConfusedKoala** [turtlecoin/turtlecoin#881]
Can this be done? Lots of love from a MAC user. thanks!

**Comment by brandonlehmann** [comment]
The miner binary is included in builds as well as the releases. It can be used to solo mine. If you are looking for a miner that supports pools, please check the miner packages listed in the release notes.

**Comment by ConfusedKoala** [comment]
Thank you. May I also check if I can get a complied version? Am not so much of a sys person ..

**Comment by brandonlehmann** [comment]
The solo miner for Mac is available in the release assets via https://github.com/turtlecoin/turtlecoin/releases/tag/v0.18.1

For the miners supporting pools, please see their repos and releases pages. If they are available they will be there or you can open an issue on those repos.
