### ISSUE TITLE
exit command in daemon isn't working as expected

### ISSUE THREAD

**Issue by rashedmyt** [turtlecoin/turtlecoin#887]
### System Information

**Operating System**:  Windows 10
**OS Version**:  1903 (Build 18362.356)

### TurtleCoin Build Information

**Version:**  0.18.1
**Binary Source:**  GitHub
### Issue Report

**Binary Reported:**  TurtleCoind

#### Expected Behavior

Daemon should exit as it does when CTRL+C is pressed

#### Current Behavior

The log level goes to 4 and the daemon doesn't exit.. it keeps on adding blocks.

##### Screen Shots

**Expected CTRL+C**
![expected_ctrl_c](https://user-images.githubusercontent.com/25506588/65683080-053c9880-e07a-11e9-8fc6-3199afcc1406.png)

**Current Exit**
![current_exit](https://user-images.githubusercontent.com/25506588/65683101-11c0f100-e07a-11e9-97cf-be1c742358a5.png)

#### Steps to Reproduce

1.  Launch the daemon
2.  Press CTRL+C and observe the output.
3. Again launch the daemon
4.  wait for syncing to start
5. type exit in console, hit enter and observe the output

**Comment by brandonlehmann** [comment]
https://github.com/turtlecoin/turtlecoin/pull/685

This is as expected at this time. The daemon must push the blocks into the underlying DB before closing completely as part of the flush process.

**Comment by rashedmyt** [comment]
But the catch here is it ain't closing.. it keeps on pushing blocks..

I have just started a fresh sync and entered exit command when I saw Block 2000 has been added to the main chain.. lets see when it will exit

**Comment by brandonlehmann** [comment]
Depending on how long it’s been running I’ve seen up to 30mins.

**Comment by rashedmyt** [comment]
So its a windows only thing and requires user to press enter two times after typing "exit".
