### ISSUE TITLE
Daemon creating heavy load when peer creates a forked blockchain

### ISSUE THREAD

**Issue by ns1000** [turtlecoin/turtlecoin#89]
I am having many problems trying to keep turtlecoin in sync. I believe I narrowed down the problem to (see log file below) this. An peer running a alternate chain completely out of sync. My node will now create a alternate chain and this causes havoc when it comes to CPU/memory. You can  see in the log, the turtle is seeing peer who is 55000 blocks behind, It then proceeds to download and copy the entire chain from this peer. 

So question is what can we do about this? Why doesn't turtle have checkpoints? Why can't i ban peers (at least not that i saw in the option).

2018-Mar-08 13:27:03.700894 TRACE   [protocol] [85.140.18.240:35669 INC] Sync data returned unknown top block: 247856 -> 192085 [55771 blocks (19 days) ahead]
2018-Mar-08 13:27:03.700894 TRACE   [protocol] SYNCHRONIZATION started
2018-Mar-08 13:27:03.701908 DEBUG   [protocol] Remote top block height: 192085, id: 4b37b163d8455b1c76dc8ece9a241a33323b3a99d6948b850ebd3ef481b6f949
2018-Mar-08 13:27:03.702247 TRACE   [protocol] [85.140.18.240:35669 INC] requesting synchronization
2018-Mar-08 13:27:03.702622 DEBUG   [node_server] [85.140.18.240:35669 INC] writeHandler started
2018-Mar-08 13:27:03.704351 TRACE   [node_server] [110.136.196.128:59115 INC] NEW CONNECTION
2018-Mar-08 13:27:03.704944 DEBUG   [node_server] [110.136.196.128:59115 INC] writeHandler started
2018-Mar-08 13:27:03.705340 TRACE   [protocol] [92.109.131.208:53943 INC] NOTIFY_REQUEST_CHAIN: m_block_ids.size()=20
2018-Mar-08 13:27:41.360738 TRACE   [protocol] [92.109.131.208:53943 INC] -->>NOTIFY_RESPONSE_CHAIN_ENTRY: m_start_height=179599, m_total_height=247856, m_block_ids.size()=10000
2018-Mar-08 13:27:41.364430 TRACE   [protocol] [92.109.131.208:53943 INC] NOTIFY_RESPONSE_GET_OBJECTS
2018-Mar-08 13:27:41.365338 TRACE   [protocol] Observed height updated: 245135
2018-Mar-08 13:27:41.379244 DEBUG   [Core] Request to add block came for block d56a45e8b376ae179c62220d5fbc35c8cee5f844e5c5e47160a69fce20f0a3cb
2018-Mar-08 13:27:43.156166 DEBUG   [Core] Adding alternative block: d56a45e8b376ae179c62220d5fbc35c8cee5f844e5c5e47160a69fce20f0a3cb
2018-Mar-08 13:27:43.156888 DEBUG   [DatabaseBlockchainCache] split at index 190244 started, top block index: 247855
2018-Mar-08 13:27:43.157245 DEBUG   [BlockchainCache] BlockchainCache with start block index: 190244 created
2018-Mar-08 13:27:43.177324 DEBUG   [DatabaseBlockchainCache] pushing block 190244 to child segment
2018-Mar-08 13:27:43.178260 DEBUG   [BlockchainCache] Pushing block c775953062f05dae5a025d0e3a66cd5bca89b9295f1fc6eab0b1e2245442178f at index 190244
2018-Mar-08 13:27:43.188766 DEBUG   [BlockchainCache] Added 40 spent key images
2018-Mar-08 13:27:43.189316 DEBUG   [BlockchainCache] Adding transaction 5ad9f61924d005dfe4dfe3120e2d8a8aa0622b0ebe4c462f82426369d8e7611a at block 190244, index in block 0
2018-Mar-08 13:27:43.189571 DEBUG   [BlockchainCache] Adding 7 transaction outputs
2018-Mar-08 13:27:43.245725 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 3 is 29607 by block index 190244
2018-Mar-08 13:27:43.246137 DEBUG   [BlockchainCache] Key output count for amount 3 requested from parent. Returned count: 29607
2018-Mar-08 13:27:43.315744 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 50 is 32379 by block index 190244
2018-Mar-08 13:27:43.316336 DEBUG   [BlockchainCache] Key output count for amount 50 requested from parent. Returned count: 32379
2018-Mar-08 13:27:43.395889 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 500 is 73799 by block index 190244
2018-Mar-08 13:27:43.396531 DEBUG   [BlockchainCache] Key output count for amount 500 requested from parent. Returned count: 73799
2018-Mar-08 13:27:43.489721 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 3000 is 71838 by block index 190244
2018-Mar-08 13:27:43.490356 DEBUG   [BlockchainCache] Key output count for amount 3000 requested from parent. Returned count: 71838
2018-Mar-08 13:27:43.580679 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 60000 is 111973 by block index 190244
2018-Mar-08 13:27:43.581397 DEBUG   [BlockchainCache] Key output count for amount 60000 requested from parent. Returned count: 111973
2018-Mar-08 13:27:43.653560 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 900000 is 214965 by block index 190244
2018-Mar-08 13:27:43.654143 DEBUG   [BlockchainCache] Key output count for amount 900000 requested from parent. Returned count: 214965
2018-Mar-08 13:27:43.726632 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 2000000 is 218735 by block index 190244
2018-Mar-08 13:27:43.727464 DEBUG   [BlockchainCache] Key output count for amount 2000000 requested from parent. Returned count: 218735
2018-Mar-08 13:27:43.727887 DEBUG   [BlockchainCache] Transaction 5ad9f61924d005dfe4dfe3120e2d8a8aa0622b0ebe4c462f82426369d8e7611a successfully added
2018-Mar-08 13:27:43.728452 DEBUG   [BlockchainCache] Adding transaction 0d8fb1675449e7e04e691d7850e0192795a8751c7258ebaa7e639bc77328b181 at block 190244, index in block 1
2018-Mar-08 13:27:43.728855 DEBUG   [BlockchainCache] Adding 27 transaction outputs
2018-Mar-08 13:27:43.800207 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 70 is 34343 by block index 190244
2018-Mar-08 13:27:43.800774 DEBUG   [BlockchainCache] Key output count for amount 70 requested from parent. Returned count: 34343
2018-Mar-08 13:27:43.879471 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 100 is 87425 by block index 190244
2018-Mar-08 13:27:43.885101 DEBUG   [BlockchainCache] Key output count for amount 100 requested from parent. Returned count: 87425
2018-Mar-08 13:27:43.990767 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 200 is 73893 by block index 190244
2018-Mar-08 13:27:43.991654 DEBUG   [BlockchainCache] Key output count for amount 200 requested from parent. Returned count: 73893
2018-Mar-08 13:27:44.074004 DEBUG   [DatabaseBlockchainCache] Key outputs count for amount 300 is 74461 by block index 190244

**Comment by bobbieltd** [comment]
I think there is a checkpoint at block 50000. Do you know if adding more checkpoints (at higher heights) can solve this issue.
If nodes keep forking alot, banning is not a solution.

**Comment by bobbieltd** [comment]
Oufff, sorry, I double checked. There is not any checkpoint.

**Comment by ns1000** [comment]
Adding checkpoint will help solve if there are many different forks in the network i believe. 

What i do know is that the daemon suffers tremendously from nodes who are out of sync and all of a sudden introducing their fork. It just happened again to my daemon, height update after 192084, and then all of a sudden my daemon starts to add every thing on the alternate chain. Adding hardcoded checkpoint to me seems like a big change to fix the blockchain, but i've seen others do it.

2018-Mar-08 14:52:45.444175 TRACE   [protocol] [76.14.134.207:50804 INC] NOTIFY_RESPONSE_GET_OBJECTS
2018-Mar-08 14:52:45.445436 TRACE   [protocol] Observed height updated: 192084
2018-Mar-08 14:52:45.457443 DEBUG   [Core] Request to add block came for block d56a45e8b376ae179c62220d5fbc35c8cee5f844e5c5e47160a69fce20f0a3cb
2018-Mar-08 14:52:46.004371 DEBUG   [Core] Adding alternative block: d56a45e8b376ae179c62220d5fbc35c8cee5f844e5c5e47160a69fce20f0a3cb
2018-Mar-08 14:52:46.005436 DEBUG   [DatabaseBlockchainCache] split at index 190244 started, top block index: 247941
2018-Mar-08 14:52:46.005877 DEBUG   [BlockchainCache] BlockchainCache with start block index: 190244 created
2018-Mar-08 14:52:46.011759 DEBUG   [DatabaseBlockchainCache] pushing block 190244 to child segment
2018-Mar-08 14:52:46.013166 DEBUG   [BlockchainCache] Pushing block c775953062f05dae5a025d0e3a66cd5bca89b9295f1fc6eab0b1e2245442178f at index 190244
2018-Mar-08 14:52:46.014110 DEBUG   [BlockchainCache] Added 40 spent key images

**Comment by bobbieltd** [comment]
I approve your regular adding checkpoints solution to diminish this forking issues.

**Comment by BigslimVdub** [comment]
Agreed checkpoints are needed if you run a node 24/7. 

Suggest at:
500
50000
150000
250000
 500000
750000
1000000

That should help for at least another year or two.

**Comment by RocksteadyTC** [comment]
A heavily checkpointed daemon will be available at the 1st of the month for Q2

**Comment by netmonk** [comment]
good
or Just implemented a filter which reject alternate chain let's say 40 blocks older than current blockheight.

**Comment by nnamon** [comment]
How do you know which is the 'current' block height?

**Comment by netmonk** [comment]
Well obviously, if a new peer trying to share with you an alternate blockchain 15000 block behind your current top block from local, and from all you other peers you are connected to, why would you even try to get this alternative blockchain at first. 
Do we need to collect all orphan subchain which havent succeed to be choosen. Can't we think about preventive filtering, more subtle than checkpoint ?
May be im missing something here, and i would be very happy to be explained something i would have not understood.

**Comment by RocksteadyTC** [comment]
Fast syncing procedure with checkpoints fixes this issue. please give it a shot and reopen the issue if the problem persists. Thanks, good luck! 
![image](https://user-images.githubusercontent.com/34389545/38711000-a35377ac-3eb2-11e8-98fb-e0e0b0b64d8d.png)

**Comment by BigslimVdub** [comment]
Thanks. 4.2 syncs wallet pretty quick, daemon not so much. I will need to check out 4.3
