### ISSUE TITLE
Incorrectly resetting instead of rewinding on subwallet import

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#893]
This line <https://github.com/turtlecoin/turtlecoin/blob/103b8efece92212e795f50477d6c51029dbdd5e0/src/walletbackend/WalletBackend.cpp#L848> and [maybe] the one above should be a `rewind`, not a `reset`. If, for example, we had a subwallet created at a height of 100,000, our wallet is synced to 500,000, and we import a subwallet with a scan height of 400,000, we will lose any data from 100,000 to 400,000, due to the reset.

We should instead rewind to the height of 400,000, removing any data after 400,000, but retaining the data before.

I don't think I have implemented rewind in the C++ backend yet, but you can port it from the js backend here - <https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/f367a8e6d66afe5fa285d6acbd8da3a2d8593b7a/lib/WalletBackend.ts#L955>

**Comment by ExtraHash** [comment]
Rewinding seems to still be very buggy even after we changed the method of balance calculation; the balance would be incorrect for some reason until a full rescan was performed, particularly with deep rewinds. Is there no way to only scan for the one extra viewkey rather than rewinding all of them?

**Comment by brandonlehmann** [comment]
> Is there no way to only scan for the one extra viewkey rather than rewinding all of them?

I believe you mean scan for one extra *spend key* as the *view key* doesn't change in subwallets.

**Comment by zpalmtree** [comment]
No, this would greatly complicate the code. This is also a completely unrelated repo

**Comment by ExtraHash** [comment]
Correct, I did mean that. Also, it's not exactly unrelated if rewind is going to be ported out of the js backend

**Comment by brandonlehmann** [comment]
Resolved in #1088
