### ISSUE TITLE
Error while compiling for 32bit architecture

### ISSUE THREAD

**Issue by 0x3h** [turtlecoin/turtlecoin#90]
On windows 32bit version i got this error "const T1 actual parameter with requested alignment of 8 won't be aligned" in `gtest-internal.h:813`, this is what the line look like
 ```
static const bool value =
      sizeof(Helper(ImplicitlyConvertible::MakeFrom())) == 1;
```

I tried remove that `const` however all i got is more errors, can you please provide a 32bit release or what's the possible fix of this?

**Comment by SoreGums** [comment]
not going to work well on most systems then. windows managed pagefile might survive - would take a long time though (I imagine if it succeeded)

**Comment by RocksteadyTC** [comment]
I think this should be closed for now until we have other means of supplying 32 bit builds. Maybe a different DB if it ever came to that.
