### ISSUE TITLE
Remote node sync freeze

### ISSUE THREAD

**Issue by UNIPOOL** [turtlecoin/turtlecoin#92]
Bonjour à tous,

J'ai trouvé le problème qui empêche un pool d'être à jour au niveau du blockchain.

Même si le remote node est synchronisé au maximum une partie dérangeante survient par moment et empêche ainsi le remote node de sync et par la même occasion de répondre au pool:

Durant le processus d'ajout d'ancienne transaction à la DB, le processus de synchronisation freeze et bloque également les réponses demandé par le pool:

Exemple de log:

`2018-Mar-11 10:49:34.830137 DEBUG   [BlockchainCache] Payment id found: face2014b18dbf6fb7f32ed3d14203cb6c50c54572387ce55abb5b50567bae7e
2018-Mar-11 10:49:34.830179 DEBUG   [BlockchainCache] Transaction 5750cdca6d21120389f8520499e8edaa9205738af2f30af820502744205ec66a successfully added
2018-Mar-11 10:49:34.830219 DEBUG   [BlockchainCache] Block c73e9ffd1622ea08b29c12b4ac0c5e60c465eb783577e21556e13101955ca52b successfully pushed
2018-Mar-11 10:49:34.830402 DEBUG   [DatabaseBlockchainCache] pushing block 254095 to child segment
2018-Mar-11 10:49:34.830470 DEBUG   [BlockchainCache] Pushing block ff7df0d0b08082d2823915235633e84bf28a0ffaad5252bebbdc4425fc2f2c99 at index 254095
2018-Mar-11 10:49:34.830513 DEBUG   [BlockchainCache] Added 0 spent key images
2018-Mar-11 10:49:34.830552 DEBUG   [BlockchainCache] Adding transaction 748341888c4a0529d3ca0ced37bf43a26a670acea13f005ea0f04ebb64be44c3 at block 254095, index in block 0
2018-Mar-11 10:49:34.830592 DEBUG   [BlockchainCache] Adding 7 transaction outputs
2018-Mar-11 10:49:34.830631 DEBUG   [BlockchainCache] Transaction 748341888c4a0529d3ca0ced37bf43a26a670acea13f005ea0f04ebb64be44c3 successfully added
2018-Mar-11 10:49:34.830670 DEBUG   [BlockchainCache] Block ff7df0d0b08082d2823915235633e84bf28a0ffaad5252bebbdc4425fc2f2c99 successfully pushed
2018-Mar-11 10:49:34.831894 DEBUG   [DatabaseBlockchainCache] pushing block 254096 to child segment
2018-Mar-11 10:49:34.832083 DEBUG   [BlockchainCache] Pushing block 514b493006ef19295bcb06feca976d15824ba049df8ec917da21f5f87e054f71 at index 254096
2018-Mar-11 10:49:34.832171 DEBUG   [BlockchainCache] Added 66 spent key images
2018-Mar-11 10:49:34.832215 DEBUG   [BlockchainCache] Adding transaction 5700ef7b0dc74f6c131cc5affd402236f78800ebe6adf78b2b1cad966e7fc3f7 at block 254096, index in block 0
`

Cette partie prend beaucoup de temps même avec un gros serveur en SSD.

Une autre partie qui suit ce système et qui prend du temps:

`2018-Mar-11 10:49:47.624220 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214025
2018-Mar-11 10:49:47.624298 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450734
2018-Mar-11 10:49:47.624352 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214024
2018-Mar-11 10:49:47.624434 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450731
2018-Mar-11 10:49:47.624489 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214023
2018-Mar-11 10:49:47.624616 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450700
2018-Mar-11 10:49:47.624671 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214022
2018-Mar-11 10:49:47.624749 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450691
2018-Mar-11 10:49:47.624803 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214021
2018-Mar-11 10:49:47.624910 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450673
2018-Mar-11 10:49:47.624965 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214020
2018-Mar-11 10:49:47.625056 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450655
2018-Mar-11 10:49:47.625111 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214019
2018-Mar-11 10:49:47.625202 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450622
2018-Mar-11 10:49:47.625258 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214018
2018-Mar-11 10:49:47.625337 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450598
2018-Mar-11 10:49:47.625392 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214017
2018-Mar-11 10:49:47.625469 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450584
2018-Mar-11 10:49:47.625524 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214016
2018-Mar-11 10:49:47.625602 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450561
2018-Mar-11 10:49:47.625656 DEBUG   [DatabaseBlockchainCache] Deleting spent outputs for block index 214015
2018-Mar-11 10:49:47.625956 DEBUG   [DatabaseBlockchainCache] Deleting timestamp 1519450540`

Je pense qu'il est possible de créer une méthode asynchrone pour faire disparaître ce freeze, le reste fonctionne très bien quand cette partie ne ce met pas en route.

En attendant j'ai trouvé une astuce pour ce problème en modifiant: apiInterface.js

L'astuce parait être brouillant mais en attendant cela fonctionne:

`        rpcDaemon: function(method, params, callback){
	    var randomRemoteNode = getRandomInt(3);
	    if (randomRemoteNode == 0)
            {
            	rpc(remoteNodeIP1, daemonConfig.port, method, params, callback);
	    }
	    else if (randomRemoteNode == 1)
	    {
            	rpc(remoteNodeIP2, daemonConfig.port, method, params, callback);
	    }
	    else if (randomRemoteNode == 2)
	    {
            	rpc(remoteNodeIP3, daemonConfig.port, method, params, callback);
	    }
        },
`

Voila merci de votre compréhension.

**Comment by bobbieltd** [comment]
Salut ! J’ai aussi cette merde. La pool est souvent interrupté (TCP connection blah blah). 
Est ce que vous avez appliqué votre atuce ? Je voudrais l’utiliser aussi mais je ne voulais pas cacher le pool.

**Comment by RocksteadyTC** [comment]
Est ce que to connait si le neouveau repo de bcndev contient les maimes corrigement de le Alpha daemon que vous avez mentionne? https://github.com/bcndev/bytecoin

**Comment by UNIPOOL** [comment]
Bonjour,

Oui j'ai appliqué cette solution et cela fonctionne @bobbieltd 

@RocksteadyTC Non je ne sais pas malheureusement, je leurs demanderai plus d'information si ils ont le temps de me répondre

**Comment by UNIPOOL** [comment]
Cette issue n'est pas résolu pour autant, lorsque cette étape survient mon problème de block orphaned reviens à nouveau comme si après tout les blocks orphaned envoyé causé un ban IP du remote node par la suite. 

Merci par avance de sortir une nouvelle version du remote node pour empêcher que cette étape de synchronisation soit un problème récurrent.

**Comment by bobbieltd** [comment]
En fait, je n’ai pas utilisé votre atuce. Le problem est que tous les nodes ne sont pas sur le même height de temps en temps. Si tu saute nodes, ça va mélanger les “jobs” (les boulots).

**Comment by UNIPOOL** [comment]
Non le bug qui survient c'est que les blocks que je trouve avant les autres pools ne deviennent valide que 10 secondes.

**Comment by UNIPOOL** [comment]
J'ai remarqué aussi une erreur très bizarre sur leurs remote nodes:

2018-Mar-16 14:11:09.147696 TRACE   [RpcServer] JSON-RPC response: {"id":"0","jsonrpc":"2.0","result":{"blocktemplate_blob":"030093ccb5a5ab2397cef31023969606dc6becc6df730762d31b44996ef24f2b13d50000ed84afd505000000000000000000000000000000000000000000000000000000000000000000000000010000000023032100000000000000000000000000000000000000000000000000000000000000000001febb1001ffd6bb100650028b00d716ea51d44e12e1988e52c597683a02cf0edf7b545948ff8ef0f85a701bac020220d1279f3f888643cebf45905f71fa72aefe604cb51b37e587cc0103134de606f02e02be17e48ab17dadb5f9fbb91c8a92b0f0057313b9389c59829676fd6f7678f643d0860302c94e7a54b1f3d8da1c3acf3d30423b9b99621a1b8c54a5d89713492fa2e13464a0f736025a8c755bd7b5bde39fd2aea48343d15fa5460793ba570c5504c5718523b2c6c780897a024d1f72e5d0f09e5bebe5ab86f60151ad9ddda001bba2a6050cbbc58fd36f59512b01b6ffa8d41e3fbdf800bafe67f8c5fa02794e8388c2099a2e8efc7170cd092b8d0208000000000000000001de6f9eaea10c9395266dc775f98e038d5e32a96c7d1c0ddf818db76370962a80","difficulty":182245042,"height":269782,"reserved_offset":377,"status":"OK"}}
2018-Mar-16 14:11:09.153176 TRACE   [RpcServer] JSON-RPC response: {"id":"0","jsonrpc":"2.0","result":{"blocktemplate_blob":"030093ccb5a5ab2397cef31023969606dc6becc6df730762d31b44996ef24f2b13d50000ed84afd505000000000000000000000000000000000000000000000000000000000000000000000000010000000023032100000000000000000000000000000000000000000000000000000000000000000001febb1001ffd6bb10065002cf9cbe442840883e3cf53e1c06081406566c57312c42a5a4403638b9b31611abac0202f4c387deec64e2ee14477bef7d4891277579b3eb3821c9d24758feecdc0fae9ff02e02dbc09cf0e515786c15dcc8f1ef07e926189b067816fdf65f13ce71655b0178f4d0860302855819b89f142a4fc40d2ea2abba15398f1d08663c5886b8642d004080929054a0f73602086f1e5f7f2d4c8c977da4820b3c175379adf0dab08ab7fda17f9858d523e37c80897a0298cc13010593f75686d41eae4bd39d2bf9a13e66cf9316da61eafc58c7ddaeae2b01bd721f47f0d0de1f2d45a1640b2ea63654022aa28f52046359ed48c5c67ca7760208000000000000000001de6f9eaea10c9395266dc775f98e038d5e32a96c7d1c0ddf818db76370962a80","difficulty":182245042,"height":269782,"reserved_offset":377,"status":"OK"}}

Les blockstemplate_block du même blockchain height change toute les secondes alors que ça devrait être fix.

**Comment by UNIPOOL** [comment]
En général je suis obligé d'attendre une sorte de Deban du remote node et ça remarche.

**Comment by UNIPOOL** [comment]
Problème corrigé 👍

**Comment by UNIPOOL** [comment]
How to for fix remote node freeze after pushing old transaction data:

1. Stop remote node.
2. Remove p2pstate.bin for removing old peer ID banned by the blockchain 
(when the remote node freeze from their function of pushing old transaction data, the pool submit orphaned blocks and make a ban of the remote node on the blockchain side)
3. start the remote node.
4. Stop the pool.
5. Reboot the server of the pool.
6. stop the remote node and remove again p2pstate.bin
7. Start the remote node again.
8. Start the pool.
