### ISSUE TITLE
build error on argon2 current version

### ISSUE THREAD

**Issue by Antonio6666** [turtlecoin/turtlecoin#924]
### System Information

**Operating System**:  Linux corsair 5.3.0-1-amd64 #1 SMP Debian 5.3.7-1 (2019-10-19) x86_64 GNU/Linux
**OS Version**: 
**CPU Make, Model, & Speed**: 
**Amount of RAM**:  4 GB
**Hard Drive Type**: 
**Hard Drive Size**: 
**Volume Type**:  ext4

### TurtleCoin Build Information

**Version:**  v0.20.0
**Binary Source:**  git clone -b master --single-branch https://github.com/turtlecoin/turtlecoin
**If self compiled, please provide all the build commands you used**  export CC=gcc-8 export CXX=g++-8 mkdir build cd build cmake .. make
```
Please insert your build commands here. Example:

- `export CC=gcc-8`
- `export CXX=g++-8`
- `git clone -b master --single-branch https://github.com/turtlecoin/turtlecoin`
- `cd turtlecoin`
- `mkdir build`
- `cd build`
- `cmake ..`
- `make`


**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:
```
Please insert your default verbosity CMake output here
```

### Issue Report

**Binary Reported:** <!-- does this issue affect zedwallet, TurtleCoind, turtle-service, miner? -->

#### Expected Behavior

<!-- please explain what you expected to happen -->

#### Current Behavior

<!-- please explain in detail what actually happened -->

##### Screen Shots





/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
/home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-sse3.c:93:14: note: called from here
   93 |         t0 = _mm_alignr_epi8(D0, D1, 8); \
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-sse3.c:109:9: note: in expansion of macro ‘UNDIAGONALIZE’
  109 |         UNDIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1); \
      |         ^~~~~~~~~~~~~
/home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-template-128.h:34:9: note: in expansion of macro ‘BLAKE2_ROUND’
   34 |         BLAKE2_ROUND(
      |         ^~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:35,
                 from /home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-sse3.c:9:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
/home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-sse3.c:89:22: note: called from here
   89 |         __m128i t1 = _mm_alignr_epi8(B1, B0, 8); \
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-sse3.c:109:9: note: in expansion of macro ‘UNDIAGONALIZE’
  109 |         UNDIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1); \
      |         ^~~~~~~~~~~~~
/home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-template-128.h:34:9: note: in expansion of macro ‘BLAKE2_ROUND’
   34 |         BLAKE2_ROUND(
      |         ^~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:35,
                 from /home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-sse3.c:9:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
/home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-sse3.c:88:22: note: called from here
   88 |         __m128i t0 = _mm_alignr_epi8(B0, B1, 8); \
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-sse3.c:109:9: note: in expansion of macro ‘UNDIAGONALIZE’
  109 |         UNDIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1); \
      |         ^~~~~~~~~~~~~
/home/antonio/Scaricati/turtlecoin/external/argon2/arch/x86_64/lib/argon2-template-128.h:34:9: note: in expansion of macro ‘BLAKE2_ROUND’
   34 |         BLAKE2_ROUND(
      |         ^~~~~~~~~~~~
make[2]: *** [external/argon2/CMakeFiles/argon2.dir/build.make:167: external/argon2/CMakeFiles/argon2.dir/arch/x86_64/lib/argon2-sse3.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:483: external/argon2/CMakeFiles/argon2.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

<!-- please include any screenshots showing the issue in this section, if no screenshots are available this section may be removed -->

#### Steps to Reproduce

<!-- Please provide detailed steps on how we might reproduce this issue -->

1. <!-- step 1 -->
2. <!-- step 2 -->
3. <!-- step 3 -->
4. <!-- add more steps as needed -->

#### Possible Solution

<!-- If you believe you have a possible solution for your reported issue, please provide details of that solution here; otherwise, you may remove this section entirely -->

**Comment by brandonlehmann** [comment]
Please supply the output of the cmake step of the process. It appears that you're trying to compile with gcc-9/g++-9 not 8 as indicated.

**Comment by Antonio6666** [comment]
antonio@corsair:~/Scaricati/turtlecoin/build$ export CXX=g++-8
antonio@corsair:~/Scaricati/turtlecoin/build$ export CC=gcc-8
antonio@corsair:~/Scaricati/turtlecoin/build$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Building for target architecture: native
-- FORCE_USE_HEAP: ENABLED
-- HW AES: ENABLED
-- OPTIMIZED_ARM_MULTIPLICATION: ENABLED
-- Found Git: /usr/bin/git
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
--   thread
--   date_time
--   chrono
--   serialization
--   atomic
-- Boost Found: /usr/include
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found version
"1.1.1d")
-- OpenSSL Found: /usr/include
-- OpenSSL Libraries:
/usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a;dl
-- *************************************************************************
The Crypto++ library does not officially support CMake. CMake support is a
community effort, and the library works with the folks using CMake to help
improve it. If you find an issue then please fix it or report it at
https://github.com/noloader/cryptopp-cmake.
-- *************************************************************************
-- CMake version 3.13.3
-- Performing Test CRYPTOPP_IA32_SSE2
-- Performing Test CRYPTOPP_IA32_SSE2 - Success
-- Performing Test CRYPTOPP_IA32_SSSE3
-- Performing Test CRYPTOPP_IA32_SSSE3 - Success
-- Performing Test CRYPTOPP_IA32_SSE41
-- Performing Test CRYPTOPP_IA32_SSE41 - Success
-- Performing Test CRYPTOPP_IA32_SSE42
-- Performing Test CRYPTOPP_IA32_SSE42 - Success
-- Performing Test CRYPTOPP_IA32_CLMUL
-- Performing Test CRYPTOPP_IA32_CLMUL - Success
-- Performing Test CRYPTOPP_IA32_AES
-- Performing Test CRYPTOPP_IA32_AES - Success
-- Performing Test CRYPTOPP_IA32_AVX
-- Performing Test CRYPTOPP_IA32_AVX - Success
-- Performing Test CRYPTOPP_IA32_AVX2
-- Performing Test CRYPTOPP_IA32_AVX2 - Success
-- Performing Test CRYPTOPP_IA32_SHA
-- Performing Test CRYPTOPP_IA32_SHA - Success
-- Performing Test CRYPTOPP_MIXED_ASM
-- Performing Test CRYPTOPP_MIXED_ASM - Success
-- Platform: x86_64
-- Native arch: FALSE
-- Compiler: /usr/bin/g++-8
-- Compiler options:  -std=c++17  -Wall -Wextra -Wpointer-arith -Wvla
-Wwrite-strings  -Wno-error=extra -Wno-error=unused-function
-Wno-error=sign-compare -Wno-error=strict-aliasing -Wno-error=type-limits
-Wno-unused-parameter -Wno-error=unused-variable -Wno-error=undef
-Wno-error=uninitialized -Wno-error=unused-result -Wlogical-op
-Wno-error=maybe-uninitialized -Wno-error=clobbered
-Wno-error=unused-but-set-variable -Wno-error=odr -Wno-reorder
-Wno-missing-field-initializers -march=native -maes -pthread -w
-Wno-everything
-- Compiler definitions:
-- Build type: Release
ZSTD VERSION 1.4.3
-- Argon2: Processor: x86_64
-- Argon2: Build Type: native
-- Detected Host CPU: k8
-- Performing Test check_cxx_compiler_flag__march_k8
-- Performing Test check_cxx_compiler_flag__march_k8 - Success
-- Performing Test check_cxx_compiler_flag__msse2
-- Performing Test check_cxx_compiler_flag__msse2 - Success
-- Performing Test check_cxx_compiler_flag__mno_sse3
-- Performing Test check_cxx_compiler_flag__mno_sse3 - Success
-- Performing Test check_cxx_compiler_flag__mno_ssse3
-- Performing Test check_cxx_compiler_flag__mno_ssse3 - Success
-- Performing Test check_cxx_compiler_flag__mno_sse4_1
-- Performing Test check_cxx_compiler_flag__mno_sse4_1 - Success
-- Performing Test check_cxx_compiler_flag__mno_sse4_2
-- Performing Test check_cxx_compiler_flag__mno_sse4_2 - Success
-- Performing Test check_cxx_compiler_flag__mno_sse4a
-- Performing Test check_cxx_compiler_flag__mno_sse4a - Success
-- Performing Test check_cxx_compiler_flag__mno_avx
-- Performing Test check_cxx_compiler_flag__mno_avx - Success
-- Performing Test check_cxx_compiler_flag__mno_fma
-- Performing Test check_cxx_compiler_flag__mno_fma - Success
-- Performing Test check_cxx_compiler_flag__mno_bmi2
-- Performing Test check_cxx_compiler_flag__mno_bmi2 - Success
-- Performing Test check_cxx_compiler_flag__mno_avx2
-- Performing Test check_cxx_compiler_flag__mno_avx2 - Success
-- Performing Test check_cxx_compiler_flag__mno_xop
-- Performing Test check_cxx_compiler_flag__mno_xop - Success
-- Performing Test check_cxx_compiler_flag__mno_fma4
-- Performing Test check_cxx_compiler_flag__mno_fma4 - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512f
-- Performing Test check_cxx_compiler_flag__mno_avx512f - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512vl
-- Performing Test check_cxx_compiler_flag__mno_avx512vl - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512pf
-- Performing Test check_cxx_compiler_flag__mno_avx512pf - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512er
-- Performing Test check_cxx_compiler_flag__mno_avx512er - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512cd
-- Performing Test check_cxx_compiler_flag__mno_avx512cd - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512dq
-- Performing Test check_cxx_compiler_flag__mno_avx512dq - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512bw
-- Performing Test check_cxx_compiler_flag__mno_avx512bw - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512ifma
-- Performing Test check_cxx_compiler_flag__mno_avx512ifma - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512vbmi
-- Performing Test check_cxx_compiler_flag__mno_avx512vbmi - Success
-- -- Argon2: Build Flags:  -std=c++17  -Wall -Wextra -Wpointer-arith -Wvla
-Wwrite-strings  -Wno-error=extra -Wno-error=unused-function
-Wno-error=sign-compare -Wno-error=strict-aliasing -Wno-error=type-limits
-Wno-unused-parameter -Wno-error=unused-variable -Wno-error=undef
-Wno-error=uninitialized -Wno-error=unused-result -Wlogical-op
-Wno-error=maybe-uninitialized -Wno-error=clobbered
-Wno-error=unused-but-set-variable -Wno-error=odr -Wno-reorder
-Wno-missing-field-initializers -march=native -maes -pthread -w
-Wno-everything -march=k8 -msse2 -mno-sse3 -mno-ssse3 -mno-sse4.1
-mno-sse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop
-mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er
-mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi
-- Setting up build environment for RocksDB
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc-8
-- LZ4 library is enabled
-- Found Git: /usr/bin/git (found version "2.24.0.rc2")
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER - Success
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Success
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- Enabling RTTI in Debug builds only (default)
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE - Success
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP - Success
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - found
-- Looking for sched_getcpu
-- Looking for sched_getcpu - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- JNI library is disabled
-- Configuring done
-- Generating done
-- Build files have been written to:
/home/antonio/Scaricati/turtlecoin/build/rocksdb
-- Configuring done
-- Generating done
-- Build files have been written to:
/home/antonio/Scaricati/turtlecoin/build

Il giorno ven 1 nov 2019 alle ore 18:33 Brandon Lehmann <
notifications@github.com> ha scritto:

**Comment by Antonio6666** [comment]
I noticed also this :

-- Found Threads: TRUE
-- JNI library is disabled
-- Configuring done
-- Generating done
-- Build files have been written to:
/home/antonio/Scaricati/turtlecoin/build/rocksdb
-- Configuring done
-- Generating done
-- Build files have been written to:
/home/antonio/Scaricati/turtlecoin/build
antonio@corsair:~/Scaricati/turtlecoin/build$ make




*Scanning dependencies of target versionfatal: Nessun tag annotato può
descrivere '638727cd5416d4125369cfff349495e11aea69cb'.Ciò nonostante,
c'erano dei tag non annotati: prova con --tags.CMake Warning at
src/version.cmake:3 (message):  Cannot determine current revision.  Make *
sure that you are building either
  from a Git working tree or from a source archive.


[  0%] Built target version
Scanning dependencies of target upnpc-static
[  0%] Building C object
external/miniupnpc/CMakeFiles/upnpc-static.dir/igd_desc_parse.c.o
[  0%] Building C object
external/miniupnpc/CMakeFiles/upnpc-static.dir/miniupnpc.c.o
[  0%] Building C object
external/miniupnpc/CMakeFiles/upnpc-static.dir/minixml.c.o
[  0%] Building C object
external/miniupnpc/CMakeFiles/upnpc-static.dir/minisoap.c.o
[  1%] Building C object
external/miniupnpc/CMakeFiles/upnpc-static.dir/minissdpc.c.o
[  1%] Building C object
external/miniupnpc/CMakeFiles/upnpc-static.dir/miniwget.c.o
[  1%] Building C object
external/miniupnpc/CMakeFiles/upnpc-static.dir/upnpcommands.c.


Il giorno ven 1 nov 2019 alle ore 18:33 Brandon Lehmann <
notifications@github.com> ha scritto:

**Comment by brandonlehmann** [comment]
Please supply the output of `cat /proc/cpuinfo`

**Comment by Antonio6666** [comment]
antonio@corsair:~/Scaricati/turtlecoin/build$ cat /proc/cpuinfo
processor : 0
vendor_id : AuthenticAMD
cpu family : 15
model : 35
model name : Dual Core AMD Opteron(tm) Processor 180
stepping : 2
microcode : 0x4d
cpu MHz : 2400.000
cache size : 1024 KB
physical id : 0
siblings : 2
core id : 0
cpu cores : 2
apicid : 0
initial apicid : 0
fpu : yes
fpu_exception : yes
cpuid level : 1
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat
pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt lm 3dnowext
3dnow rep_good nopl cpuid pni lahf_lm cmp_legacy 3dnowprefetch vmmcall
bugs : fxsave_leak sysret_ss_attrs null_seg swapgs_fence spectre_v1
spectre_v2
bogomips : 4824.47
TLB size : 1024 4K pages
clflush size : 64
cache_alignment : 64
address sizes : 40 bits physical, 48 bits virtual
power management: ts fid vid ttp

processor : 1
vendor_id : AuthenticAMD
cpu family : 15
model : 35
model name : Dual Core AMD Opteron(tm) Processor 180
stepping : 2
microcode : 0x4d
cpu MHz : 2400.000
cache size : 1024 KB
physical id : 0
siblings : 2
core id : 1
cpu cores : 2
apicid : 1
initial apicid : 1
fpu : yes
fpu_exception : yes
cpuid level : 1
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat
pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt lm 3dnowext
3dnow rep_good nopl cpuid pni lahf_lm cmp_legacy 3dnowprefetch vmmcall
bugs : fxsave_leak sysret_ss_attrs null_seg swapgs_fence spectre_v1
spectre_v2
bogomips : 4824.45
TLB size : 1024 4K pages
clflush size : 64
cache_alignment : 64
address sizes : 40 bits physical, 48 bits virtual
power management: ts fid vid ttp

Il giorno ven 1 nov 2019 alle ore 18:50 Brandon Lehmann <
notifications@github.com> ha scritto:

**Comment by brandonlehmann** [comment]
Excellent. It looks like for whatever reason, cmake believes you have SSE3 support; however, your CPU does not. The quickest way around this for the time being is to re-rerun `cmake .. -DARCH=default` and then attempt to `make` again

**Comment by Antonio6666** [comment]
OK I'm compiling I will let you know . Thanks very much.
Antonio

Il giorno ven 1 nov 2019 alle ore 18:54 Brandon Lehmann <
notifications@github.com> ha scritto:

**Comment by brandonlehmann** [comment]
If you get an extra moment, could you also supply the output of:

`gcc-8 -dM -E - < /dev/null -march=native | grep -E "(MMX|SSE|AVX|XOP)"`

**Comment by Antonio6666** [comment]
sure
antonio@corsair:~$ gcc-8 -dM -E - < /dev/null -march=native | grep -E
"(MMX|SSE|AVX|XOP)"
#define __MMX__ 1
#define __SSE2_MATH__ 1
#define __SSE_MATH__ 1
#define __SSE2__ 1
#define __SSE__ 1
#define __SSE3__ 1


argon2  Done !

Scanning dependencies of target argon2
[ 46%] Building C object
external/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o
[ 46%] Building C object external/argon2/CMakeFiles/argon2.dir/lib/core.c.o
[ 46%] Building C object
external/argon2/CMakeFiles/argon2.dir/lib/encoding.c.o
[ 47%] Building C object
external/argon2/CMakeFiles/argon2.dir/lib/genkat.c.o
[ 47%] Building C object
external/argon2/CMakeFiles/argon2.dir/lib/impl-select.c.o
[ 47%] Building C object
external/argon2/CMakeFiles/argon2.dir/lib/thread.c.o
[ 47%] Building C object
external/argon2/CMakeFiles/argon2.dir/lib/blake2/blake2.c.o
[ 47%] Building C object
external/argon2/CMakeFiles/argon2.dir/arch/generic/lib/argon2-arch.c.o
[ 48%] Linking C static library libargon2.a
[ 48%] Built target argon2

Il giorno ven 1 nov 2019 alle ore 19:07 Brandon Lehmann <
notifications@github.com> ha scritto:

**Comment by brandonlehmann** [comment]
Thanks.

So interestingly enough, the compiler on your system with arch=native activates the SSE3 flag; however, your CPU flags do **not** list SSE3 -- so that appears to be a fault on your system somehow.

> flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat
pse36 clflush mmx fxsr **sse sse2** ht syscall nx mmxext fxsr_opt lm 3dnowext
3dnow rep_good nopl cpuid pni lahf_lm cmp_legacy 3dnowprefetch vmmcall

**Comment by Antonio6666** [comment]
Yes strange In fact, using a new computer with AMD ryzen does not create
problems to compile the turtle!

Il giorno ven 1 nov 2019 alle ore 19:15 Brandon Lehmann <
notifications@github.com> ha scritto:
