### ISSUE TITLE
Please don't give up turtle-service

### ISSUE THREAD

**Issue by yin-june** [turtlecoin/turtlecoin#928]
I am a developer working on a pay system. I use turtlecoin.

I run a full node on my server A.  
Wallet-api + turtle-service on server B.

I get blockCount from wallet-api, and get transactions from turtle-service. The process will be repeat in an interval, about 5 seconds.

I have some troubles with wallet-api:
1. My balance get dirty, I mean some trtl is locked. but these coins should not be locked.
2. My transaction history is not complete, some transaction missed.
3. Wallet-api will initiate hundred (200 ~ 300) of connections to full node. when the node is syncing and get stuck.

I meet these problems when i user version 0.14.6 and 0.18.1.   
I think the reason may be that the full node occasionally stop and restart when the node get stuck.  
But turtle-service works well, my balance is right, and transaction history is complete.
And turtle-service will only initiate 2 or 3 connections.

Wallet-api just crashed today morning. [See my bug report](https://github.com/turtlecoin/turtlecoin/issues/927)

But turtle-service will be removed after v0.20.0, i wish you keep it. because turtle-service is far more stable than wallet-api.

Thank you.

**Comment by brandonlehmann** [comment]
Turtle-service is not being removed after 0.20.0. There is no EOL timeline for turtle-service as of today.

**Comment by brandonlehmann** [comment]
Closing for now.
