### ISSUE TITLE
Possibly force wallet-upgrader to use .wallet extension

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#929]
Proton only looks for wallets with a `.wallet` extension. Possibly this is something that should be fixed on their end, or perhaps we should force a `.wallet` extension when upgrading wallets.

**Comment by ExtraHash** [comment]
This is not something I'm going to fix on my end as it was an intentional change last version release to maintain consistency with zedwallet created wallets

**Comment by brandonlehmann** [comment]
If I'm being honest, I think that confuses users. Changing filenames without them knowing/approving is quite a bit different than creating a backup copy and throwing an extension on the end.

**Comment by ExtraHash** [comment]
Are you saying it's confusing in the scope of wallet creator or proton?

**Comment by brandonlehmann** [comment]
I’m saying it’s confusing to have wallet upgrader rename active files without asking.

**Comment by ExtraHash** [comment]
Perhaps we could simply check if the proper extension is present, and if not warn the user it may break compatibility with some wallets and ask if they'd like to add it
