### ISSUE TITLE
wallet-api create hundreds of connection to node daemon

### ISSUE THREAD

**Issue by yin-june** [turtlecoin/turtlecoin#952]
wallet-api create hundreds of connection to node daemon

### System Information
**Operating System**: ubuntu
**OS Version**: Ubuntu 16.04.6 LTS
**CPU Make, Model, & Speed**: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
**Amount of RAM**: 2GB RAM + 4GB SWAP
**Hard Drive Type**: HHD
**Hard Drive Size**: 50GB

### TurtleCoin Build Information

**Version:** v0.20.0
**Binary Source:** no

### Issue Report

1. sometimes wallet-api process is running, but restful server has down.
2. wallet-api create hundreds of connections to node daemon.

![image](https://user-images.githubusercontent.com/4370991/69700106-9c7aa680-1124-11ea-8c54-2d426287c6bb.png)

**Comment by yin-june** [comment]
wallet-api DDOS turtle node ?

**Comment by zpalmtree** [comment]
This is solved in #903

**Comment by yin-june** [comment]
Is there a new usable release?

**Comment by zpalmtree** [comment]
You can download binaries from here for the threaded-rpc branch: https://github.com/turtlecoin/turtlecoin/commit/7177c02be056e3c0340c026f92c5f84b1e4a2d89/checks?check_suite_id=330732280
Click 'Artifacts' on the top right.

But there are still some issues with this PR that need to be fixed before merging, you may experience crashes with it until then.
