### ISSUE TITLE
 In the new network, the balance cannot be displayed in the wallet. Miner has found the block, but the wallet has no balance

### ISSUE THREAD

**Issue by a20180502** [turtlecoin/turtlecoin#956]
wallet：
Resetting wallet...
Scanning through the blockchain to find transactions that belong to you.
Please wait, this will take some time.

0 of 177
177 of 177
[TRTL a]: 3
Available balance: 0.00 TRTL
Locked (unconfirmed) balance: 0.00 TRTL
Total balance: 0.00 TRTL

Damon：
2019-Nov-29 13:56:59.074972 INFO    New Top Block Detected: 169
2019-Nov-29 13:57:01.821217 INFO    New Top Block Detected: 170
2019-Nov-29 13:57:15.153347 INFO    New Top Block Detected: 171
2019-Nov-29 13:57:45.391148 INFO    New Top Block Detected: 172
2019-Nov-29 13:58:25.275985 INFO    New Top Block Detected: 173
2019-Nov-29 13:58:43.061910 INFO    New Top Block Detected: 174
2019-Nov-29 13:58:54.234922 INFO    New Top Block Detected: 175

miner：
Block found! Hash: 4229f6bb0b73f18c85008b8f95570852963f9afdc7e91a60910eca2ce63b489f

Started mining for difficulty of 3888. Good luck! ;)
Started mining for difficulty of 3269. Good luck! ;)

Mining at 75 H/s

Started mining for difficulty of 3312. Good luck! ;)

Mining at 76 H/s

Started mining for difficulty of 2836. Good luck! ;)

Mining at 76 H/s

Block found! Hash: 797ff25f03b0d37430c3d8c98c4e03bd33bd7af890678dcc9f0fac755809753
turtlecoin/src/config/CryptoNoteConfig.h：

/* This section defines our minimum and maximum mixin counts required for transactions */
        const uint64_t MINIMUM_MIXIN_V1 = 0;

        const uint64_t MAXIMUM_MIXIN_V1 = 0;

        const uint64_t MINIMUM_MIXIN_V2 = 7;

        const uint64_t MAXIMUM_MIXIN_V2 = 7;

        const uint64_t MINIMUM_MIXIN_V3 = 3;

        const uint64_t MAXIMUM_MIXIN_V3 = 3;

        /* The heights to activate the mixin limits at */
        const uint32_t MIXIN_LIMITS_V1_HEIGHT = 188;

        const uint32_t MIXIN_LIMITS_V2_HEIGHT = 500000;

        const uint32_t MIXIN_LIMITS_V3_HEIGHT = 800000;

        /* The mixin to use by default with zedwallet and turtle-service */
        /* DEFAULT_MIXIN_V0 is the mixin used before MIXIN_LIMITS_V1_HEIGHT is started */
        const uint64_t DEFAULT_MIXIN_V0 = 0;

        const uint64_t DEFAULT_MIXIN_V1 = MAXIMUM_MIXIN_V1;

        const uint64_t DEFAULT_MIXIN_V2 = MAXIMUM_MIXIN_V2;

        const uint64_t DEFAULT_MIXIN_V3 = MAXIMUM_MIXIN_V3;

**Comment by brandonlehmann** [comment]
You must launch the wallet with `—scan-coinbase-transactions` to allow it to scan for and find block rewards.

**Comment by a20180502** [comment]
It works,thanks
