### ISSUE TITLE
test

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/turtlecoin#958]
### System Information

**Operating System**: 
**OS Version**: 
**CPU Make, Model, & Speed**: 
**Amount of RAM**: 
**Hard Drive Type**: 
**Hard Drive Size**: 
**Volume Type**: 

### TurtleCoin Build Information

**Version:** 
**Binary Source:** 
**If self compiled, please provide all the build commands you used**
```
Please insert your build commands here. Example:

mkdir build && cd build
cmake .. -DBOOST_ROOT=/home/turtlecoin/boost_1_59_0
make -j4
```

**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:
```
Please insert your default verbosity CMake output here
```

### Issue Report

**Binary Reported:** 

#### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by RocksteadyTC** [comment]
testeeeeng

**Comment by brandonlehmann** [comment]
Clean your room.
