### ISSUE TITLE
save command unavailable in TurtleCoind

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#96]
2018-Mar-14 16:42:23.747935 INFO    TurtleCoin **v0.3.2.1253** (0.1-g7fcc6ad)
2018-Mar-14 16:42:23.749408 INFO    Module folder: /root/trtl/TurtleCoind
2018-Mar-14 16:42:23.757062 INFO    Opening DB in /root/trtl/blockchain/DB
2018-Mar-14 16:42:30.994926 INFO    DB opened in /root/trtl/blockchain/DB
2018-Mar-14 16:42:31.019966 INFO    Initializing core...
2018-Mar-14 16:42:31.567989 INFO    DB has more blocks than blockchain storage, cutting from block index: 264664
2018-Mar-14 16:42:31.568588 INFO    Cutting root segment from index 264664
2018-Mar-14 16:42:31.918262 INFO    Core initialized OK
2018-Mar-14 16:42:31.919194 INFO    Initializing p2p server...
2018-Mar-14 16:42:31.962663 INFO    Binding on 0.0.0.0:11897
2018-Mar-14 16:42:31.963709 INFO    Net service binded on 0.0.0.0:11897
2018-Mar-14 16:42:31.963973 INFO    Attempting to add IGD port mapping.
2018-Mar-14 16:42:35.981485 INFO    No IGD was found.
2018-Mar-14 16:42:35.986350 INFO    P2p server initialized OK
2018-Mar-14 16:42:35.987662 INFO    Starting core rpc server on address 0.0.0.0:11898
2018-Mar-14 16:42:35.989327 INFO    Core rpc server started ok
2018-Mar-14 16:42:35.989571 INFO    Starting p2p net loop...
2018-Mar-14 16:42:35.993096 INFO    Starting node_server
2018-Mar-14 16:42:38.261609 INFO    [45.76.125.170:11897 OUT] Sync data returned unknown top block: 264664 -> 264680 [16 blocks (0 days) behind]
2018-Mar-14 16:42:38.261609 INFO    SYNCHRONIZATION started
2018-Mar-14 16:42:39.845427 INFO    [118.31.18.78:11897 OUT] Sync data returned unknown top block: 264664 -> 264680 [16 blocks (0 days) behind]
2018-Mar-14 16:42:39.845427 INFO    SYNCHRONIZATION started
2018-Mar-14 16:42:47.580979 INFO
2018-Mar-14 16:42:47.580979 INFO    **********************************************************************
2018-Mar-14 16:42:47.580979 INFO    You are now synchronized with the network. You may now start simplewallet.
2018-Mar-14 16:42:47.580979 INFO
2018-Mar-14 16:42:47.580979 INFO    Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "**save**" command.
2018-Mar-14 16:42:47.580979 INFO    Otherwise, you will possibly need to synchronize the blockchain again.
2018-Mar-14 16:42:47.580979 INFO
2018-Mar-14 16:42:47.580979 INFO    Use "help" command to see the list of available commands.
2018-Mar-14 16:42:47.580979 INFO    **********************************************************************
2018-Mar-14 16:42:55.385810 INFO    [118.31.18.78:11897 OUT] SYNCHRONIZED OK
save
**Unknown command: save**

**Comment by RocksteadyTC** [comment]
This is done automatically now, and this is a remnant from when we were RAM based. Thank you, I'll remove this.
