### ISSUE TITLE
Generating genesis block hex throws an error

### ISSUE THREAD

**Issue by prismspecs** [turtlecoin/turtlecoin#962]
When I try generate a genesis hex, it spits out a string of characters just fine. But when I add that to the config and recompile, it throws a "failed to parse coinbase hard coded blob"

Is it necessary to generate a genesis block when forking turtlecoin?

**Comment by brandonlehmann** [comment]
1) You've removed the copyright notice from the bottom of README.md. Please put it back.
2) You do not generate a genesis block via the cli arguments, you generate a genesis transaction.
3) The change you made here -> https://github.com/prismspecs/classcoin/commit/3432e2120512ff107e7a4a1ebfc07c291eb76ffa#diff-10fdaddc0d7a41af2ad19374da50bc69R62 is not a valid transaction in hex. I'm not sure what value you copied or where you copied it from, but transactions start with `01` or `02` 
4) Yes, you should always generate your own new genesis transaction when creating a new chain.

**Comment by prismspecs** [comment]
Thank you. Could you point me to something that explains how to generate a genesis transaction?

**Comment by brandonlehmann** [comment]
> Thank you. Could you point me to something that explains how to generate a genesis transaction?

Use the CLI argument `--print-genesis-tx` when launching the daemon (must be able to compile and execute to do so)

**Comment by prismspecs** [comment]
Ah, that was what I did to get this:
`const char GENESIS_COINBASE_TX_HEX[] = "60d0eebe92deaf1500002101dc692c84fc9ea926cd00f40c66f324f6cdb07b265ffaa350a150f4afeeae1131";`
Any idea on why it might be outputting incorrectly? I ran it on one of my seed nodes, I'm assuming that's correct.
