### ISSUE TITLE
Wallet always generates an address of the wrong length

### ISSUE THREAD

**Issue by prismspecs** [turtlecoin/turtlecoin#963]
I've tried several times and always get the same error.

Invalid address: The address given is the wrong length. It should be 99 chars or 187 chars, but it is 98 chars.

**Comment by zpalmtree** [comment]
You need to update `src/config/WalletConfig.h`

**Comment by prismspecs** [comment]
I updated that, and as it turns out the address it generates is the correct 99 characters, but when typed into the miner it says that it is 98.

**Comment by zpalmtree** [comment]
This is all it's doing. I highly doubt C++ has forgotten how to count the length of strings. https://github.com/turtlecoin/turtlecoin/blob/development/src/errors/ValidateParameters.cpp#L307-L308

**Comment by prismspecs** [comment]
Thanks for your help, I do appreciate it.

In the forking guide it says "Your address length should be 95 + the number of letters in your address prefix." My prefix is 'haha', I wonder if it's meant to be 95+4-1 instead of what is specified in the guide? Commenting out that code you referred to seems to work (we'll see if the rewards actually make their way into the wallet).
