### ISSUE TITLE
Feature request: IPV6 support 

### ISSUE THREAD

**Issue by ngeojiajun** [turtlecoin/turtlecoin#972]
In past the ipv4 is used in addressing the network peer. However, in today the ipv4 pool is being exhausted. This causes a high barrier to users to contribute to the network by running a public node. 

Known problems:
1. The P2P code seems to be hardcorded to using IPV4 at all time
[https://github.com/turtlecoin/turtlecoin/blob/dd70b8553c558a6e2f6c4af4810cd8f11127bb0b/src/platform/windows/system/TcpConnector.cpp#L86](url)
[https://github.com/turtlecoin/turtlecoin/blob/dd70b8553c558a6e2f6c4af4810cd8f11127bb0b/src/platform/windows/system/TcpConnector.cpp#L247](url)
[https://github.com/turtlecoin/turtlecoin/blob/dd70b8553c558a6e2f6c4af4810cd8f11127bb0b/src/p2p/P2pProtocolTypes.h#L12](url)
1. A network protocol upgrade needed to make it works.

Required steps:

- [ ] Replace the TcpConnection, TcpConnector, IPV4Address and IPV4Resolver with something that protocol analgonous.
- [ ] Update all p2p structure to adopt the changes
- [ ] Rehook the networking stack initialization code (Windows)

Notes:
1. Don't integrate Dispatcher interface
1. Avoid platform specific code when possible
1. Async I/O not needed
1. Provide method to specify timeout and implement it using POSIX-compatible way like select()

**Comment by brandonlehmann** [comment]
Labeling this issue as `WONTFIX` as there are no plans at this time to add IPv6 support to this core software.
