### ISSUE TITLE
TurtleCoin v0.22.0 Release Candidate Test Log (RC1)

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin#976]
# TurtleCoin v0.22.0 Release Candidate Test Log

Build from: https://github.com/turtlecoin/turtlecoin/tree/v0.22.0-RC1

Binaries for Testing:
  - Windows: [turtlecoin-cdc00d99997b1ce0a505f04a19498976a1c92280-windows.zip.zip](https://github.com/turtlecoin/turtlecoin/files/4007205/turtlecoin-cdc00d99997b1ce0a505f04a19498976a1c92280-windows.zip.zip)
  - Linux: [turtlecoin-cdc00d99997b1ce0a505f04a19498976a1c92280-linux.tar.gz.zip](https://github.com/turtlecoin/turtlecoin/files/4007203/turtlecoin-cdc00d99997b1ce0a505f04a19498976a1c92280-linux.tar.gz.zip)
  - MacOS: [turtlecoin-cdc00d99997b1ce0a505f04a19498976a1c92280-osx.tar.gz.zip](https://github.com/turtlecoin/turtlecoin/files/4007202/turtlecoin-cdc00d99997b1ce0a505f04a19498976a1c92280-osx.tar.gz.zip)
  - AARCH64: [turtlecoin-cdc00d99997b1ce0a505f04a19498976a1c92280-aarch64.tar.gz.zip](https://github.com/turtlecoin/turtlecoin/files/4007201/turtlecoin-cdc00d99997b1ce0a505f04a19498976a1c92280-aarch64.tar.gz.zip)

### Project
- [x] Currently Passing GH Actions Build Tests
- [x] `Version.h.in` updated to correct semver value
- [x] Release Notes Prepared (https://hackmd.io/@ZL2uKk4cThC4TG0z7Wu7sg/B1A-meBkU)

### TurtleCoind Tests
- Daemon connects to local DB
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Local DB does not require resync
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Peer ID assigned
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Connections to multiple peers are made
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon able to sync with external checkpoints
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon able to sync without external checkpoints
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon able to sync from 0 with external checkpoints
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon able to sync from 0 without external checkpoints
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Daemon stays synchronized for 24 hours
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
 
### ZedWallet Tests
- Connect to local daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Connect to a remote daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Send a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Receive a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Perform a fusion transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Export keys and seeds
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Import from keys and seeds correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Perform a full reset
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Integrated Addresses work
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Scan From Height Works Correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS

### Turtle-Service Tests
- Connect to local daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Connect to a remote daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Send a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Receive a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Perform a fusion transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Export keys and seeds
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Import from keys and seeds correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Perform a full reset
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Integrated Addresses work
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- All RPC endpoints and methods are operational
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS
- Scan From Height Works Correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] MacOS

**Comment by brandonlehmann** [comment]
Release notes prepared

**Comment by brandonlehmann** [comment]
Binaries uploaded

**Comment by old-greywolf** [comment]
*as of 19:30 PST, Dec 28, 2019*

**Operating Systems and versions tested**
- Windows 10 Pro
- Ubuntu 18.10 Linux 4.18.0-25-generic
- macOS Catalina


### TurtleCoind Tests

Daemon connects to local DB
- [ ] Windows
- [x] Linux
- [ ] MacOS
Local DB does not require resync
- [ ] Windows
- [x] Linux
- [ ] MacOS
Peer ID assigned
- [ ] Windows
- [x] Linux
- [ ] MacOS
Connections to multiple peers are made
- [ ] Windows
- [x] Linux
- [ ] MacOS
Daemon able to sync with external checkpoints
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Daemon able to sync without external checkpoints
- [ ] Windows
- [x] Linux
- [ ] MacOS
Daemon able to sync from 0 with external checkpoints
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Daemon able to sync from 0 without external checkpoints
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Daemon stays synchronized for 24 hours
- [ ] Windows
- [ ] Linux **(in progress)**
- [ ] MacOS

### ZedWallet Tests

Connect to local daemon
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Connect to a remote daemon
- [ ] Windows
- [x] Linux
- [ ] MacOS
Send a transaction
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Receive a transaction
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Perform a fusion transaction
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Export keys and seeds
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Import from keys and seeds correctly
- [ ] Windows
- [x] Linux
- [ ] MacOS
Perform a full reset
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Integrated Addresses work
- [ ] Windows
- [ ] Linux
- [ ] MacOS
Scan From Height Works Correctly
- [ ] Windows
- [ ] Linux **(in progress)**
- [ ] MacOS

**Comment by brandonlehmann** [comment]
Closing RC early due to a bug in turtle-service syncing and possibly another.
