### ISSUE TITLE
Error on send

### ISSUE THREAD

**Issue by C0lDsp4c3** [turtlecoin/turtlecoin#98]
![image](https://user-images.githubusercontent.com/26920070/37491277-8c3d7d2c-289d-11e8-80fa-8ca830b3dc23.png)

**Comment by ereptor81** [comment]
As far as I can tell from that error message, unless you've been sending manual commands to walletd directly to create addresses in your wallet, something is messed up in your wallet file. Importing your keys into a new wallet file should fix the issue. If you need a hand w/ that, pop into #help and one of us can walk you through it.
